//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVAsset.h"

@class NSArray;

@interface AVAsset (MGContentSupport)
@property(readonly) NSArray *unsupportedFormatDescriptions;
@property(readonly) NSArray *unsupportedTracks;
@property(readonly) NSArray *supportedTracks;
@property(readonly, getter=isSupportedContainerFormat) BOOL supportedContainerFormat;
@end

