//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImageView, NSTextField, NSTimer, NSView;

@interface MGAboutPanelController : NSObject
{
    NSTimer *_timer;
    unsigned long long _timerIndex;
    NSView *_additionalCopyrightsView;
    NSImageView *_logoImageView;
    NSTextField *_URLTextField;
    NSTextField *_copyrightTextField;
}

+ (id)sharedAboutPanelController;
+ (void)initialize;
- (void)fireTimer:(id)arg1;
- (void)aboutPanelDidHide:(id)arg1;
- (void)aboutPanelWillShow:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)dealloc;
- (id)init;

@end

