//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MGAccountUtilities : NSObject
{
}

+ (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
+ (void)startAccountSetupInMCCWithServiceIdentifier:(id)arg1;
+ (id)accountforUserName:(id)arg1 accountIdentifier:(id)arg2;
+ (BOOL)isInternetRegionAsia;
+ (id)_x99:(id)arg1;

@end

