//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@interface MGApplication : NSApplication
{
}

- (void)terminate:(id)arg1;
- (BOOL)_shouldTerminate;
- (BOOL)isRunningDocumentModalWindowControllers;
- (id)targetForAction:(SEL)arg1 to:(id)arg2 from:(id)arg3;

@end

