//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSDictionary, NSError, NSString;

@interface MGAppleScriptPublishOperation : NSOperation
{
    NSDictionary *_exportParameters;
    NSError *_error;
}

@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) NSString *localizedStatusMessage;
@property(readonly) float progress;
- (void)main;
- (void)dealloc;
- (id)initAppleScriptPublishOperationWithParameters:(id)arg1;
- (id)appleScriptPublishOperationWithParameters:(id)arg1;

@end

