//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMenu, NSMenuItem;

@interface MGApplicationDelegate : NSObject
{
    NSMenuItem *_debugMenu;
    NSMenu *_fileMenu;
    NSMenu *_subtitlesMenu;
    NSMenu *_audioLanguageMenu;
    NSMenu *_baseDockMenu;
    NSMenu *_shareMenu;
}

+ (void)initialize;
- (void)shareToTudou:(id)arg1;
- (void)shareToYouku:(id)arg1;
- (void)shareToiMovie:(id)arg1;
- (void)shareToPodcastProducer:(id)arg1;
- (BOOL)hasUserLoggedInWithPodcastCapture;
- (BOOL)isShareToTudouEnabled;
- (BOOL)isShareToYoukuEnabled;
- (BOOL)isShareToiMovieEnabled;
- (void)stopScreenRecording:(id)arg1;
- (void)togglePlayingInAllMovieDocuments:(id)arg1;
- (void)sleepIndefinitely;
- (void)hangMainThread:(id)arg1;
- (void)orderFrontStandardAboutPanel:(id)arg1;
- (void)showHideShareProgressWindow:(id)arg1;
- (void)showHideInfoWindow:(id)arg1;
- (id)audioLanguageMenu;
- (id)subtitlesMenu;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)menuHasKeyEquivalent:(id)arg1 forEvent:(id)arg2 target:(id *)arg3 action:(SEL *)arg4;
- (void)menuNeedsUpdate:(id)arg1;
- (id)applicationDockMenu:(id)arg1;
- (id)shareMenuItemList:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)delayedApplicationDidFinishLaunching;
- (void)reportLaunchTestResults;
- (void)collectMemoryUsageAndTerminateApp:(id)arg1 label:(id)arg2;
- (BOOL)applicationShouldOpenUntitledFile:(id)arg1;
- (void)dealloc;
- (void)application:(id)arg1 runTest:(unsigned int)arg2 duration:(double)arg3;

@end

