//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, AVAssetImageGenerator, NSArray, NSLocale;

@interface MGAssetChapterController : NSObject
{
    AVAsset *_asset;
    AVAssetImageGenerator *_assetImageGenerator;
    NSLocale *_chapterLocale;
    CDStruct_e83c9415 _chapterTimeRange;
}

+ (id)keyPathsForValuesAffectingChapters;
+ (id)keyPathsForValuesAffectingSystemChapterLocale;
+ (id)keyPathsForValuesAffectingAvailableChapterLocales;
@property(nonatomic) CDStruct_e83c9415 chapterTimeRange; // @synthesize chapterTimeRange=_chapterTimeRange;
@property(copy, nonatomic) NSLocale *chapterLocale; // @synthesize chapterLocale=_chapterLocale;
@property(readonly, nonatomic) NSArray *chapters;
@property(readonly, nonatomic) NSLocale *systemChapterLocale;
@property(readonly, nonatomic) NSArray *availableChapterLocales;
@property(retain, nonatomic) AVAsset *asset;
- (void)dealloc;

@end

