//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, NSDate, NSImage, NSString;

@interface MGAssetInformation : NSObject
{
    NSString *_subtitle;
    NSDate *_creationDate;
    NSString *_duration;
    NSImage *_image;
    AVAsset *_asset;
    NSString *_title;
}

+ (id)assetInformationWithAsset:(id)arg1;
@property(readonly) NSString *title; // @synthesize title=_title;
@property(readonly) AVAsset *asset; // @synthesize asset=_asset;
- (id)imageSubtitle;
- (id)imageTitle;
- (id)imageRepresentation;
- (id)imageRepresentationType;
- (id)imageUID;
@property(readonly) NSString *subtitle;
@property(readonly) NSString *duration;
@property(readonly) NSDate *creationDate;
@property(readonly) NSImage *image;
- (void)dealloc;
- (id)initWithAsset:(id)arg1;

@end

