//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>;

@interface MGAssetValidator : NSObject
{
    NSObject<OS_dispatch_source> *_source;
}

@property(readonly, getter=isCancelled) BOOL cancelled;
- (void)cancel;
- (void)setCompletionHandler:(CDUnknownBlockType)arg1;
- (void)setCompletionQueue:(id)arg1;
- (void)resume;
- (void)suspend;
- (void)finalize;
- (void)dealloc;
- (id)initWithAsset:(id)arg1;
- (id)init;

@end

