//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGAudioExtractor.h"

@class AVAsset, AVAssetReader, AVAssetReaderAudioMixOutput;

@interface MGAssetAudioExtractor : MGAudioExtractor
{
    AVAsset *_asset;
    AVAssetReader *_assetReader;
    AVAssetReaderAudioMixOutput *_assetReaderOutput;
}

@property(readonly, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
- (struct opaqueCMSampleBuffer *)copyNextSampleBuffer;
- (CDStruct_1b6d18a9)duration;
- (void)dealloc;
- (id)initWithNumberOfChannels:(unsigned long long)arg1;
- (id)initWithAsset:(id)arg1 numberOfChannels:(unsigned long long)arg2;

@end

