//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGChapter.h"

@class AVAssetImageGenerator, AVTimedMetadataGroup;

@interface MGAssetChapter : MGChapter
{
    AVTimedMetadataGroup *_chapterMetadataGroup;
    AVAssetImageGenerator *_assetImageGenerator;
    CDStruct_e83c9415 _chapterTimeRange;
}

- (void)extractMetadataImageAsynchronouslyReturningToBlock:(CDUnknownBlockType)arg1;
- (void)extractImageAsynchronouslyForTime:(CDStruct_1b6d18a9)arg1 returningToBlock:(CDUnknownBlockType)arg2;
- (id)name;
- (CDStruct_1b6d18a9)startTime;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithChapterMetadataGroup:(id)arg1 chapterTimeRange:(CDStruct_e83c9415)arg2 assetImageGenerator:(id)arg3;

@end

