//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MGAttributePair : NSObject
{
    id _label;
    id _value;
}

+ (id)attributePairWithLabel:(id)arg1 value:(id)arg2;
- (void)setValue:(id)arg1;
- (id)value;
- (void)setLabel:(id)arg1;
- (id)label;
- (void)dealloc;
- (id)initWithLabel:(id)arg1 value:(id)arg2;

@end

