//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGChapterMenuControllerDelegate.h"
#import "MGTrimViewControllerDelegate.h"
#import "MGVisualContentContainer.h"
#import "NSMenuDelegate.h"

@class MGAnimatedTabView, MGChapterMenuController, MGGroupViewTextFieldPairResizer, MGMediaClip, MGMovieStatusStringController, MGPlayPauseShuttleControllerView, MGPlayerController, MGPopUpLabelView, MGTrimViewController, NSPopUpButton, NSTextField, NSTimer, NSView, NSWindowController, QTHUDGroupViewItem, QTHUDTimeFormatter, QTHUDTimeline;

@interface MGAudioPlaybackViewController : MGDocumentViewController <MGTrimViewControllerDelegate, NSMenuDelegate, MGChapterMenuControllerDelegate, MGVisualContentContainer>
{
    MGPlayerController *_playerControllerForTextFields;
    MGPlayerController *_playerControllerForSlider;
    NSView *_playbackControlsContainerView;
    MGAnimatedTabView *_timelineAndStatusStringTabView;
    QTHUDTimeline *_timeline;
    NSTextField *_elapsedTimeTextField;
    NSTextField *_remainingTimeTextField;
    NSTextField *_durationTextField;
    QTHUDGroupViewItem *_elapsedTimeGroupViewItem;
    QTHUDGroupViewItem *_remainingTimeAndDurationGroupViewItem;
    NSPopUpButton *_chapterPopUpButton;
    MGPlayPauseShuttleControllerView *_playPauseShuttleControllerView;
    NSWindowController *_parentWindowController;
    MGGroupViewTextFieldPairResizer *_textFieldPairResizer;
    MGTrimViewController *_trimViewController;
    MGMediaClip *_trimMediaClip;
    NSTimer *_trimFocusTimeoutTimer;
    MGPopUpLabelView *_trimFocusPopUpLabelView;
    QTHUDTimeFormatter *_trimFocusTimeFormatter;
    id _playerController;
    MGMovieStatusStringController *_movieStatusStringController;
    MGChapterMenuController *_chapterMenuController;
    struct CGSize _initialViewSize;
    struct CGSize _initialTrimViewSize;
    unsigned int _isShowingTrimControls:1;
    unsigned int _isShowingTrimFocus:1;
    unsigned int _didPauseForSheet:1;
    unsigned int _inStateRestore:1;
}

+ (id)keyPathsForValuesAffectingTimelineUpdateResolution;
+ (id)keyPathsForValuesAffectingMaximumContentSize;
+ (id)keyPathsForValuesAffectingMinimumContentSize;
+ (void)initialize;
@property(readonly, nonatomic) QTHUDTimeline *timeline; // @synthesize timeline=_timeline;
@property(readonly, nonatomic) MGMovieStatusStringController *movieStatusStringController; // @synthesize movieStatusStringController=_movieStatusStringController;
@property(readonly, nonatomic) NSWindowController *parentWindowController; // @synthesize parentWindowController=_parentWindowController;
- (void)invalidateRestorableState;
- (void)restoreStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)mainWindowDidEndSheet:(id)arg1;
- (void)mainWindowWillBeginSheet:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)beginGestureWithEvent:(id)arg1;
- (void)gotoPreviousChapter:(id)arg1;
- (void)gotoNextChapter:(id)arg1;
- (void)chapterMenuController:(id)arg1 didSelectChapter:(id)arg2;
- (void)chapterPopUpButtonWillPopup:(id)arg1;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepBackwardCurrentMediaTimeToTime:(CDStruct_1b6d18a9)arg2;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepForwardCurrentMediaTimeToTime:(CDStruct_1b6d18a9)arg2;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willChangeCurrentMediaTimeToTime:(CDStruct_1b6d18a9)arg2;
- (void)trimViewControllerDidStopTrackingCurrentMediaTime:(id)arg1;
- (void)trimViewControllerWillStartTrackingCurrentMediaTime:(id)arg1;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepBackwardSelectionEdge:(int)arg2 toTime:(CDStruct_1b6d18a9)arg3;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepForwardSelectionEdge:(int)arg2 toTime:(CDStruct_1b6d18a9)arg3;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willChangeSelectionEdge:(int)arg2 toTime:(CDStruct_1b6d18a9)arg3;
- (void)trimViewController:(id)arg1 didStopTrackingSelectionEdge:(int)arg2;
- (void)trimViewController:(id)arg1 willStartTrackingSelectionEdge:(int)arg2;
- (void)hideTrimFocus;
- (void)showTrimFocusWithTimeout:(BOOL)arg1 forMediaTime:(CDStruct_1b6d18a9)arg2;
- (void)trimDidEndWithResult:(BOOL)arg1;
- (void)trimViewControllerDidCommitEditing:(id)arg1;
- (void)cancelTrim:(id)arg1;
- (void)confirmTrim:(id)arg1;
- (void)startTrim:(id)arg1;
@property(nonatomic, getter=isShowingTrimControls) BOOL showingTrimControls;
- (BOOL)isShowingModalUserInterface;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) double timelineUpdateResolution;
- (struct CGSize)maximumContentSize;
- (struct CGSize)minimumContentSize;
- (struct CGSize)naturalContentSize;
- (BOOL)prefersConstrainedContentAspectRatio;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
- (void)close;
- (void)resignMainViewControllerForWindowController:(id)arg1;
- (void)becomeMainViewControllerForWindowController:(id)arg1;
- (void)loadView;

@end

