//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSArray, NSImageView, NSTextField;

@interface MGAutoresizingMenuItemView : NSView
{
    NSImageView *_imageView;
    NSTextField *_textField1;
    NSTextField *_textField2;
    NSArray *_textFields;
    BOOL _needsLayoutAndResize;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutAndResizeIfNeeded;
- (void)setNeedsLayoutAndResize;
- (void)dealloc;
- (void)awakeFromNib;

@end

