//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MGAudioSilenceBoundaryLocator : NSObject
{
    unsigned long long _silenceSampleCountThreshold;
    float _silenceThreshold;
    unsigned long long _silentSectionLength;
    unsigned long long _absoluteSampleIndex;
}

- (struct _NSRange)remainingSilenceRange;
- (void)enumerateLocatedSilenceRangesAfterAppendingAmplitudeSamples:(const float *)arg1 count:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)init;
- (id)initWithSilenceAmplitudeThreshold:(float)arg1 silenceSampleCountThreshold:(unsigned long long)arg2;

@end

