//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGAtomicCancelationToken, MGAudioAmplitudeExtractionSession, MGAudioExtractor;

@interface MGAudioAmplitudeExtractionSessionHelper : NSObject
{
    MGAudioAmplitudeExtractionSession *_owner;
    int _ownerLock;
    MGAtomicCancelationToken *_cancelationToken;
    MGAudioExtractor *_uncompressedAudioExtractor;
    unsigned long long _numberOfChannels;
    id *_amplitudeSampleDataArray;
    unsigned long long _numberOfAmplitudeSamplesPerSecond;
    int _numberOfExtractedAmplitudeSamples;
    float _maximumExtractedAmplitude;
    int _maximumExtractedAmplitudeLock;
    int _isExtractionFinished;
}

@property(readonly, nonatomic) unsigned long long numberOfAmplitudeSamplesPerSecond; // @synthesize numberOfAmplitudeSamplesPerSecond=_numberOfAmplitudeSamplesPerSecond;
@property(readonly, nonatomic) MGAudioExtractor *uncompressedAudioExtractor; // @synthesize uncompressedAudioExtractor=_uncompressedAudioExtractor;
- (float)maximumExtractedAmplitude;
- (id)amplitudeSamplesInRange:(struct _NSRange)arg1;
- (BOOL)isExtractionFinished;
- (id)availableAmplitudeSampleIndexes;
- (void)dealloc;
- (void)invalidate;
- (id)init;
- (id)initWithOwner:(id)arg1 uncompressedAudioExtractor:(id)arg2 numberOfAmplitudeSamplesPerSecond:(unsigned long long)arg3;

@end

