//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MGMovieExportSessionHelper.h"

@class AVAssetExportSession, MGMediaComposition, NSRunLoop, NSTimer, NSURL;

@interface MGAVFoundationExportSession : NSObject <MGMovieExportSessionHelper>
{
    AVAssetExportSession *_avSession;
    id <MGMovieExportSessionHelperDelegate> _delegate;
    MGMediaComposition *_mediaComposition;
    NSURL *_tempURL;
    NSURL *_destinationURL;
    NSTimer *_exportProgressTimer;
    NSRunLoop *_sessionRunLoop;
    BOOL _isExtensionHidden;
}

- (void)updateProgress:(id)arg1;
- (void)cancel;
- (void)createExportSessionwithExportParameters:(id)arg1;
- (void)dealloc;
- (id)initWithMediaComposition:(id)arg1 exportParameters:(id)arg2 sessionDelegate:(id)arg3;

@end

