//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, AVAudioMix, AVVideoComposition, MGMediaComposition, NSArray;

@interface MGAVCompositionBuilder : NSObject
{
    MGMediaComposition *_mediaComposition;
    AVAsset *_asset;
    NSArray *_videoCompositionInstructions;
    NSArray *_audioMixInputParameters;
}

+ (id)mediaClipKeyPathsAffectingAVComposition;
+ (id)mediaCompositionKeyPathsAffectingAVComposition;
+ (id)assetWithMediaClip:(id)arg1 inMediaComposition:(id)arg2 videoComposition:(id *)arg3 audioMix:(id *)arg4 assetProvider:(id)arg5;
+ (id)audioTrackAssetWithMediaClip:(id)arg1 inMediaComposition:(id)arg2 assetProvider:(id)arg3;
- (id)additionalMediaTrackAudioAssetTrack;
- (id)mainMediaTrackAudioAssetTrack;
@property(readonly, nonatomic) AVAudioMix *audioMix;
@property(readonly, nonatomic) AVVideoComposition *videoComposition;
@property(readonly, nonatomic) AVAsset *asset;
- (void)dealloc;
- (id)initWithMediaComposition:(id)arg1;
- (id)initWithMediaComposition:(id)arg1 assetProvider:(id)arg2;

@end

