//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MGPassThroughAnimator, NSColor;

@interface MGBackgroundColorView : NSView
{
    NSColor *_backgroundColor;
    id _cachedCGColor;
    MGPassThroughAnimator *_animator;
    unsigned int _flags;
}

+ (id)defaultAnimationForKey:(id)arg1;
@property(copy) NSColor *backgroundColor;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (id)animator;
- (id)hitTest:(struct CGPoint)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (BOOL)wantsDefaultClipping;
- (BOOL)isOpaque;
- (void)displayLayer:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

