//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface MGCaptureCompressionPreset : NSObject
{
    NSDictionary *_presetDescription;
}

+ (id)compressionPresetsNamed:(id)arg1 forDevice:(id)arg2;
- (id)outputFileType;
- (id)outputSettingsWithMediaType:(id)arg1;
@property(readonly, nonatomic) struct CGSize defaultCompressedSize;
- (id)localizedSummaryForMediaTypes:(id)arg1;
@property(readonly, nonatomic) NSString *localizedSummary;
@property(readonly, nonatomic) NSString *localizedName;
@property(readonly, nonatomic) NSString *category;
@property(readonly, nonatomic) NSString *identifier;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)init;
- (id)initWithPresetDescription:(id)arg1;
- (id)objectSpecifier;
- (id)uniqueID;
- (id)name;

@end

