//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVCaptureDevice, NSString;

@interface MGCaptureDeviceInputSourcePair : NSObject
{
    AVCaptureDevice *_device;
    NSString *_inputSourceIdentifier;
}

+ (id)inputSourcePairWithDevice:(id)arg1 inputSourceIdentifier:(id)arg2;
@property(readonly, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
@property(readonly, nonatomic) NSString *localizedDisplayName;
@property(readonly, nonatomic) NSString *inputSourceIdentifier;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)initWithDevice:(id)arg1 inputSourceIdentifier:(id)arg2;

@end

