//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGCaptureDeviceInputSourcePair, MGCaptureDeviceSelectionController, NSSet;

@interface MGCaptureDeviceAndInputSourceSelectionController : NSObject
{
    MGCaptureDeviceSelectionController *_deviceSelectionController;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) MGCaptureDeviceInputSourcePair *audioDevice;
@property(readonly, nonatomic) NSSet *availableAudioDevices;
@property(retain, nonatomic) MGCaptureDeviceInputSourcePair *videoDevice;
@property(readonly, nonatomic) NSSet *availableVideoDevices;
- (id)availableDeviceInputSourcePairsForDeviceSelectionControllerKey:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithDeviceSelectionController:(id)arg1;

@end

