//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface MGChapter : NSObject <NSCopying>
{
}

+ (unsigned long long)indexOfChapterAtTime:(CDStruct_1b6d18a9)arg1 inChapters:(id)arg2;
- (void)extractMetadataImageAsynchronouslyReturningToBlock:(CDUnknownBlockType)arg1;
- (void)extractImageAsynchronouslyForTime:(CDStruct_1b6d18a9)arg1 returningToBlock:(CDUnknownBlockType)arg2;
- (void)extractImageAsynchronouslyReturningToBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) CDStruct_1b6d18a9 startTime;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

