//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGLayerCollectionViewDelegate.h"
#import "MGViewLayoutManager.h"

@class MGChapter, MGChapterPreviewLayerController, MGGridLayerCollectionView, MGLayoutManagedView, MGPageControl, MGPartitionedBackgroundView, NSButton, NSView;

@interface MGChapterViewController : MGDocumentViewController <MGLayerCollectionViewDelegate, MGViewLayoutManager>
{
    MGGridLayerCollectionView *_collectionView;
    MGPartitionedBackgroundView *_backgroundView;
    MGLayoutManagedView *_pageControlsView;
    MGPageControl *_pageControl;
    NSButton *_previousPageButton;
    NSButton *_nextPageButton;
    MGChapter *_currentChapter;
    NSView *_transitionView;
    MGChapterPreviewLayerController *_transitionTargetChapterLayerController;
    struct CGImage *_transitionTargetVideoImage;
    struct CGImage *_transitionTargetMetadataImage;
    unsigned long long _numberOfPendingTransitionTransactions;
    double _minimumOrderInTimeForNextChapterLayer;
    id <MGChapterViewControllerDelegate> _delegate;
    BOOL _showingChapters;
}

+ (void)initialize;
@property(nonatomic) id <MGChapterViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic, getter=isShowingChapters) BOOL showingChapters; // @synthesize showingChapters=_showingChapters;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)beginGestureWithEvent:(id)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)cancel:(id)arg1;
- (void)layerCollectionView:(id)arg1 didChooseRepresentedObjectsAtIndexes:(id)arg2 withEvent:(id)arg3;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)layoutSubviewsOfView:(id)arg1 resizedFromOldSize:(struct CGSize)arg2;
- (void)resetMinimumOrderInTimeForNextChapterLayer;
- (id)layerCollectionView:(id)arg1 layerControllerForRepresentedObjectAtIndex:(unsigned long long)arg2;
- (void)hideChaptersWithFinalCurrentTime:(CDStruct_1b6d18a9)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)showChaptersWithInitialCurrentTime:(CDStruct_1b6d18a9)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setShowingChapters:(BOOL)arg1 withCurrentTime:(CDStruct_1b6d18a9)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)close;
- (void)loadView;

@end

