//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGLayerController.h"

@class CALayer, CATextLayer, MGSuperlayerBoundedContainerLayer;

@interface MGChapterPreviewLayerController : MGLayerController
{
    unsigned long long _chapterIndex;
    BOOL _animatesThumbnailOrderIn;
    double _minimumThumbnailOrderInTime;
    CALayer *_thumbnailContainerLayer;
    CALayer *_thumbnailLayer;
    CALayer *_selectionLayer;
    MGSuperlayerBoundedContainerLayer *_titleContainerLayer;
    CATextLayer *_titleLayer;
    CALayer *_currentChapterIndicatorLayer;
    struct CGSize _thumbnailAspectRatio;
    int _titlePosition;
    BOOL _showsCurrentChapterIndicator;
    BOOL _thumbnailIsVideoFrame;
    BOOL _showsChapterName;
    BOOL _isObservingWhetherRootViewIsFirstResponder;
}

+ (double)orderInTimeIncrement;
+ (double)initialOrderInTimeDelay;
+ (struct CGRect)thumbnailFrameForLayerFrame:(struct CGRect)arg1 thumbnailAspectRatio:(struct CGSize)arg2 titlePosition:(int)arg3;
+ (double)naturalWidthForHeight:(double)arg1 thumbnailAspectRatio:(struct CGSize)arg2 titlePosition:(int)arg3;
+ (id)keyPathsForValuesAffectingChapterName;
+ (id)keyPathsForValuesAffectingViewToLayerScaleFactor;
@property(nonatomic) BOOL thumbnailIsVideoFrame; // @synthesize thumbnailIsVideoFrame=_thumbnailIsVideoFrame;
@property(nonatomic) struct CGSize thumbnailAspectRatio; // @synthesize thumbnailAspectRatio=_thumbnailAspectRatio;
@property(nonatomic) double minimumThumbnailOrderInTime; // @synthesize minimumThumbnailOrderInTime=_minimumThumbnailOrderInTime;
@property(nonatomic) BOOL animatesThumbnailOrderIn; // @synthesize animatesThumbnailOrderIn=_animatesThumbnailOrderIn;
@property(nonatomic) unsigned long long chapterIndex; // @synthesize chapterIndex=_chapterIndex;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (void)windowDidChangeBackingProperties:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) int titlePosition;
- (void)updateLayoutForTitlePosition;
@property(retain, nonatomic) CALayer *thumbnailLayer;
@property(nonatomic) BOOL showsCurrentChapterIndicator;
- (void)updateLayoutForCurrentChapterIndicator;
@property(nonatomic) BOOL showsChapterName;
- (BOOL)shouldShowChapterNameByDefault;
- (id)chapterName;
- (void)layoutSublayersOfLayer:(id)arg1;
- (struct CGSize)viewToLayerScaleFactor;
- (void)setSelected:(BOOL)arg1;
- (void)close;
- (void)loadLayer;

@end

