//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMenuDelegate.h"

@class NSArray, NSMenu, NSMenuItem;

@interface MGChapterMenuController : NSObject <NSMenuDelegate>
{
    NSArray *_chapters;
    CDStruct_1b6d18a9 _currentTime;
    NSMenu *_menu;
    long long _firstChapterItemIndex;
    long long _currentItemCount;
    struct CGSize _placeholderThumbnailAspectRatio;
    NSMenuItem *_currentChapterMenuItem;
    id <MGChapterMenuControllerDelegate> _delegate;
    BOOL _menuItemsNeedToBeRebuilt;
    BOOL _currentChapterMenuItemNeedsUpdate;
    BOOL _menuIsOpen;
}

@property(nonatomic) id <MGChapterMenuControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGSize placeholderThumbnailAspectRatio; // @synthesize placeholderThumbnailAspectRatio=_placeholderThumbnailAspectRatio;
@property(nonatomic) CDStruct_1b6d18a9 currentTime; // @synthesize currentTime=_currentTime;
@property(copy, nonatomic) NSArray *chapters; // @synthesize chapters=_chapters;
- (void)takeChapterFrom:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeMenuItems;
- (void)rebuildMenuItemsIfNeeded;
- (void)setCurrentChapterMenuItemNeedsUpdate;
- (void)setMenuItemsNeedToBeRebuilt;
@property(readonly, nonatomic) NSMenuItem *currentChapterMenuItem;
@property(nonatomic) long long firstChapterItemIndex;
@property(retain, nonatomic) NSMenu *menu;
- (void)dealloc;
- (id)init;

@end

