//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFrameView.h"

@class MGCinematicFrameTitlebarView, NSColor;

@interface MGCinematicFrameView : NSFrameView
{
    MGCinematicFrameTitlebarView *_titlebarView;
    NSColor *_backgroundColor;
    struct CGImage *_backBufferCornerImage;
    struct CGRect _backBufferDirtyRects[2];
    unsigned long long _backBufferDirtyRectsCount;
    long long _resizeFlags;
    unsigned int _movingDisabled:1;
    unsigned int _resizingDisabled:1;
    unsigned int _automaticallyManagesTitlebarFrame:1;
    unsigned int _hasRoundedCorners:1;
    unsigned int _entireBackBufferIsDirty:1;
    unsigned int _useWindowShapeForRoundedCorners:1;
    unsigned int _debugForceNoRoundedCorners:1;
    unsigned int _alphaShapeNeedsUpdate:1;
    unsigned int _hasTexturedBackground:1;
}

+ (struct CGSize)minContentSizeForMinFrameSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;
+ (struct CGSize)minFrameSizeForMinContentSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;
+ (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;
+ (struct CGRect)frameRectForContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;
+ (unsigned long long)_validateStyleMask:(unsigned long long)arg1;
+ (void)initialize;
- (BOOL)_surfaceInheritsWindowOpaqueShape;
- (void)viewDidEndLiveResize;
- (BOOL)_shouldBeTreatedAsInkEventInInactiveWindow:(id)arg1;
- (BOOL)shouldBeTreatedAsInkEvent:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (long long)resizeFlags;
- (void)resizeWithEvent:(id)arg1;
- (BOOL)shouldResizeWithEvent:(id)arg1;
- (BOOL)_isResizable;
- (void)_setFrameNeedsDisplay:(BOOL)arg1;
- (long long)QTHUD_backgroundStyleForRect:(struct CGRect)arg1;
- (double)contentBorderDistanceFromTop;
- (struct CGRect)_maxTitlebarTitleRect;
- (struct CGRect)_defaultTitlebarViewFrame;
- (void)tileAndSetWindowShape:(BOOL)arg1;
- (void)_updateButtonState;
- (void)_updateButtons;
- (void)_resetDragMargins;
- (struct CGSRegionObject *)_regionForOpaqueDescendants:(struct CGRect)arg1 forMove:(BOOL)arg2;
- (struct CGSRegionObject *)_resizeRegion;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)_drawsNothing;
- (void)windowDidChangeBackingProperties:(id)arg1;
- (void)displayIfNeeded;
- (void)_drawBackground;
- (BOOL)needsToDrawRectInBackBuffer:(struct CGRect)arg1;
- (BOOL)preservesContentDuringLiveResize;
- (void)shapeWindow;
- (struct CGSRegionObject *)_createWindowOpaqueShape;
- (void)createWindowShape:(struct CGSRegionObject **)arg1 opaqueShape:(struct CGSRegionObject **)arg2 alphaShape:(struct CGSRegionObject **)arg3 eventShape:(struct CGSRegionObject **)arg4;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (BOOL)isTitlebarVisible;
- (id)fileButton;
@property(nonatomic) BOOL automaticallyManagesTitlebarFrame;
@property(nonatomic, getter=isResizingDisabled) BOOL resizingDisabled;
@property(nonatomic, getter=isMovingDisabled) BOOL movingDisabled;
- (void)addSubviewBelowTitlebar:(id)arg1;
- (id)titlebarView;
@property(nonatomic) BOOL hasTexturedBackground;
@property(nonatomic) BOOL hasRoundedCorners;
@property(copy, nonatomic) NSColor *backgroundColor;
- (void)updateBackgroundLayerProperties;
- (void)setRepresentedURL:(id)arg1;
- (void)setDocumentEdited:(BOOL)arg1;
- (void)setTitle:(id)arg1;
- (id)_displayName;
- (unsigned long long)_shadowFlags;
- (unsigned int)_CAViewFlags;
- (BOOL)isWindowOpaque;
- (BOOL)isOpaque;
- (double)cornerRadiusInPixels;
- (double)cornerRadius;
- (id)contentFill;
- (double)contentAlpha;
- (struct CGRect)dragRectForFrameRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 owner:(id)arg3;

@end

