//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class MGPassThroughAnimator, NSColor;

@interface MGCinematicWindow : NSWindow
{
    MGPassThroughAnimator *_animator;
    unsigned int _flags;
}

+ (double)titlebarHeightForStyleMask:(unsigned long long)arg1;
+ (Class)frameViewClassForStyleMask:(unsigned long long)arg1;
+ (void)initialize;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)decreaseSize:(id)arg1;
- (void)increaseSize:(id)arg1;
- (void)fitToScreen:(id)arg1;
- (void)actualSize:(id)arg1;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)draggingEnded:(id)arg1;
@property(nonatomic) BOOL hasTexturedBackground;
@property(nonatomic) BOOL hasRoundedCorners;
@property(nonatomic) BOOL automaticallyConstrainsFrameRect;
@property(nonatomic) BOOL automaticallyManagesTitlebarFrame;
@property(nonatomic) BOOL ignoresMouseEvents;
@property(nonatomic, getter=isResizingDisabled) BOOL resizingDisabled;
@property(nonatomic, getter=isMovingDisabled) BOOL movingDisabled;
- (id)titlebarView;
- (struct CGRect)constrainFrameRect:(struct CGRect)arg1 toScreen:(id)arg2;
- (id)animator;
- (id)_customImageForStandardWindowButton:(unsigned long long)arg1 state:(unsigned long long)arg2 dirty:(BOOL)arg3 controlTint:(unsigned long long)arg4;
- (BOOL)_hasActiveAppearanceForStandardWindowButton:(unsigned long long)arg1;
- (BOOL)_isDarkWindow;
- (void)sendEvent:(id)arg1;
- (void)setContentView:(id)arg1;
@property(copy, nonatomic) NSColor *backgroundColor;
- (void)dealloc;
- (void)_commonAwake;

@end

