//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGRecordingDocument.h"

#import "MGInspectionAttributeContainer.h"

@class MGCaptureAudioPreviewOutput, MGCaptureCompressionPreset, MGCaptureDeviceSelectionController, MGDeviceRecordingDocumentViewController, NSArray;

@interface MGDeviceRecordingDocument : MGRecordingDocument <MGInspectionAttributeContainer>
{
    MGDeviceRecordingDocumentViewController *_mainViewController;
    MGCaptureDeviceSelectionController *_captureDeviceSelectionController;
    MGCaptureAudioPreviewOutput *_captureAudioPreviewOutput;
    NSArray *_availableCompressionPresets;
    MGCaptureCompressionPreset *_compressionPreset;
    unsigned int _deviceRecordingDocumentFlags;
}

+ (id)keyPathsForValuesAffectingOutputFileType;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingInspectionAttributes;
@property(readonly, nonatomic) NSArray *availableCompressionPresets; // @synthesize availableCompressionPresets=_availableCompressionPresets;
@property(readonly, nonatomic) MGCaptureAudioPreviewOutput *captureAudioPreviewOutput; // @synthesize captureAudioPreviewOutput=_captureAudioPreviewOutput;
@property(readonly, nonatomic) MGCaptureDeviceSelectionController *captureDeviceSelectionController; // @synthesize captureDeviceSelectionController=_captureDeviceSelectionController;
- (void)startRecording;
- (void)workspaceSessionDidBecomeActive:(id)arg1;
- (void)workspaceSessionDidResignActive:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)makeSureDevicesAreSelectedIfPossible;
- (void)updateCaptureSessionRunningState;
- (id)outputFileType;
- (id)baseOutputFileName;
- (void)updateCompressionPresets;
- (void)applyCompressionOptionsToCaptureSession;
@property(retain, nonatomic) MGCaptureCompressionPreset *compressionPreset;
@property(readonly, nonatomic, getter=isAudioOnly) BOOL audioOnly;
- (void)close;
- (void)viewControllerDidLoadView:(id)arg1;
- (id)mainViewController;
- (void)dealloc;
- (id)initWithRecordingType:(int)arg1;
- (id)init;
@property(readonly, nonatomic) NSArray *inspectionInformation;
@property(readonly, nonatomic) NSArray *inspectionAttributes;
- (void)setRate:(float)arg1;
- (float)rate;
- (BOOL)playing;
- (void)setVolume:(float)arg1;
- (float)volume;
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (void)setLoops:(BOOL)arg1;
- (BOOL)loops;
- (id)naturalDimensions;
- (void)setCurrentTimeInSeconds:(id)arg1;
- (id)currentTimeInSeconds;
- (id)durationInSeconds;
- (unsigned long long)dataRate;
- (unsigned long long)dataSize;
- (void)setCurrentMovieCompression:(id)arg1;
- (void)setCurrentAudioCompression:(id)arg1;
- (void)setCurrentVideoRecordingDevice:(id)arg1;
- (void)setCurrentAudioRecordingDevice:(id)arg1;
- (id)currentScreenCompression;
- (id)currentMovieCompression;
- (id)currentAudioCompression;
- (id)currentVideoRecordingDevice;
- (id)currentAudioRecordingDevice;
- (void)handleResumeCommand:(id)arg1;
- (void)handlePauseCommand:(id)arg1;

@end

