//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGAutovisibilityControllerOwner.h"
#import "MGViewLayoutManager.h"
#import "MGVisualContentContainer.h"

@class AVCaptureVideoPreviewLayer, MGAudioLevelIndicator, MGAutovisibilityController, MGCaptureDeviceAndInputSourceSelectionController, MGDocumentWindowController, MGDraggableView, NSButton, NSPopUpButton, NSString, NSTextField, NSTimer, NSView, NSViewController;

@interface MGDeviceRecordingDocumentViewController : MGDocumentViewController <MGAutovisibilityControllerOwner, MGViewLayoutManager, MGVisualContentContainer>
{
    NSView *_captureView;
    MGDraggableView *_controlsView;
    NSView *_controlsBackgroundView;
    NSButton *_theOneButtonToRuleThemAll;
    MGAudioLevelIndicator *_audioLevelIndicator;
    NSTextField *_recordingTimeView;
    NSTextField *_recordingSizeView;
    NSPopUpButton *_optionsPopUp;
    NSView *_finishingView;
    AVCaptureVideoPreviewLayer *_captureLayer;
    MGDocumentWindowController *_parentWindowController;
    struct CGSize _naturalContentSize;
    struct CGSize _initialViewSize;
    MGCaptureDeviceAndInputSourceSelectionController *_deviceSelectionController;
    MGAutovisibilityController *_autovisibilityController;
    NSTimer *_audioLevelIndicatorTimer;
    NSTimer *_recordingTimeAndSizeTimer;
    struct CGRect _savedControlsFrame;
    struct CGRect _boundsWhenControlsFrameWasSaved;
    NSViewController *_noDeviceConnectedViewController;
    NSViewController *_deviceSuspendedViewController;
    unsigned long long _flags;
}

+ (id)keyPathsForValuesAffectingDeviceErrorString;
+ (void)initialize;
@property(readonly, nonatomic) MGCaptureDeviceAndInputSourceSelectionController *deviceSelectionController; // @synthesize deviceSelectionController=_deviceSelectionController;
@property(readonly, nonatomic) MGDocumentWindowController *parentWindowController; // @synthesize parentWindowController=_parentWindowController;
- (void)workspaceSessionDidBecomeActive:(id)arg1;
- (void)workspaceSessionDidResignActive:(id)arg1;
@property(readonly, nonatomic) NSString *deviceErrorString;
@property(readonly, nonatomic) NSString *audioDeviceErrorString;
@property(readonly, nonatomic) NSString *videoDeviceErrorString;
- (void)updateRecordingTimeAndSize:(id)arg1;
- (void)stopRecordingTimeAndSizeTimer;
- (void)startRecordingTimeAndSizeTimer;
- (void)updateAudioLevelIndicator:(id)arg1;
- (void)stopAudioLevelIndicatorTimer;
- (void)startAudioLevelIndicatorTimer;
- (void)changeAudioPreviewVolumeToMinimum:(id)arg1;
- (void)changeAudioPreviewVolumeToMaximum:(id)arg1;
- (void)chooseOutputDirectory:(id)arg1;
- (void)takeSelectedCompressionPresetFromRepresentedObjectOf:(id)arg1;
- (void)takeSelectedAudioDeviceFromRepresentedObjectOf:(id)arg1;
- (void)takeSelectedVideoDeviceFromRepresentedObjectOf:(id)arg1;
- (void)changeRecordingState:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)flagsChanged:(id)arg1;
- (void)windowControllerDidFinishFullScreenAnimation:(id)arg1;
- (void)windowControllerDidStartFullScreenAnimation:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateDeviceSuspendedView;
- (void)updateNoDeviceConnectedView;
- (void)syncUIWithRecordingState;
- (void)resetAutovisibilityController;
- (void)hideForAutovisibilityController:(id)arg1 dueToTimeout:(BOOL)arg2;
- (void)showForAutovisibilityController:(id)arg1;
- (void)setShowsControls:(BOOL)arg1;
- (BOOL)showsControls;
- (BOOL)prefersBorderedOverlays;
- (void)setPrefersUnobscuredContent:(BOOL)arg1;
- (BOOL)prefersUnobscuredContent;
- (BOOL)isShowingDocumentModalInterface;
- (void)menuNeedsUpdate:(id)arg1;
- (void)layoutSubviewsOfView:(id)arg1 resizedFromOldSize:(struct CGSize)arg2;
- (struct CGPoint)defaultControlsFrameOriginWhenAnimatingAndHidden;
- (struct CGSize)maximumContentSize;
- (struct CGSize)minimumContentSize;
- (BOOL)prefersConstrainedContentAspectRatio;
- (struct CGSize)naturalContentSize;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
- (void)dealloc;
- (void)close;
- (void)resignMainViewControllerForWindowController:(id)arg1;
- (void)becomeMainViewControllerForWindowController:(id)arg1;
- (void)loadView;

@end

