//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGJobController.h"

@class MGJob, NSError, NSString, NSURL;

@interface MGDesktopExportJobController : MGJobController
{
    MGJob *_activeJob;
    NSString *_outputFile;
    NSError *_error;
    NSURL *_resultURL;
}

@property(retain, nonatomic) MGJob *activeJob; // @synthesize activeJob=_activeJob;
@property(copy, nonatomic) NSString *outputFile; // @synthesize outputFile=_outputFile;
- (BOOL)restoreFromDictionaryRepresentation:(id)arg1;
- (id)savedDictionaryRepresentation;
- (id)resultURL;
- (id)error;
- (id)statusString;
- (id)icon;
- (id)name;
- (id)identifier;
- (void)dealloc;
- (id)initActiveJobWithMediaComposition:(id)arg1 exportParameters:(id)arg2;

@end

