//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocumentController.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface MGDocumentController : NSDocumentController
{
    NSMutableArray *_URLsToAddToRecentDocumentsSharedFileLists;
    struct OpaqueLSSharedFileListRef *_applicationRecentDocumentsSharedFileList;
    unsigned long long _numberOfRecordingsOpen;
    BOOL _isScreenRecordingDocumentOpen;
    unsigned int _recentDocumentsSharedFileListsNeedsUpdate:1;
    NSObject<OS_dispatch_queue> *_recentsQueue;
}

+ (id)recentDocumentURLPropertyListForURL:(id)arg1;
+ (id)_recentMenuItemTitlesFromURLComponentChains:(id)arg1 includingIcons:(BOOL)arg2;
+ (void)initialize;
@property NSObject<OS_dispatch_queue> *recentsQueue; // @synthesize recentsQueue=_recentsQueue;
- (void)openURLsInQuickTimePlayer7:(id)arg1;
- (BOOL)isQuickTimePlayer7Installed;
- (void)replaceDocument:(id)arg1 withDocument:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)defaultURLScheme;
- (id)supportedURLSchemes;
- (void)enumerateSupportedURLTypesUsingBlock:(CDUnknownBlockType)arg1;
- (id)openNewScreenRecordingDocument;
- (id)openNewDeviceRecordingDocumentWithRecordingType:(int)arg1;
- (void)openURLDocument:(id)arg1;
- (void)newScreenRecordingDocument:(id)arg1;
- (void)newAudioRecordingDocument:(id)arg1;
- (void)newMovieRecordingDocument:(id)arg1;
- (BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;
- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (Class)documentClassForType:(id)arg1;
- (id)typeForContentsOfURL:(id)arg1 error:(id *)arg2;
- (void)_updateRecentDocumentsSharedFileListsIfNeeded;
- (void)updateRecentDocumentsSharedFileListsIfNeeded;
- (void)setRecentDocumentsSharedFileListsNeedsUpdate;
- (void)addURLToRecentDocumentsSharedFileLists:(id)arg1;
@property(readonly) struct OpaqueLSSharedFileListRef *applicationRecentDocumentsSharedFileList;
- (id)_recentDocumentURLsUsingQueue:(id)arg1;
- (void)_installOpenRecentMenus;
- (void)_populateOpenRecentMenu:(id)arg1 includingIcons:(BOOL)arg2;
- (void)_depopulateOpenRecentMenu:(id)arg1;
- (void)_openRecentDocument:(id)arg1;
- (id)recentDocumentURLs;
- (void)noteNewRecentDocumentURL:(id)arg1;
- (void)noteNewRecentDocument:(id)arg1;
- (void)clearRecentDocuments:(id)arg1;
- (BOOL)presentErrorUsingAlternatePresentation:(id)arg1 didRecover:(char *)arg2;
- (id)willPresentError:(id)arg1;
- (BOOL)presentError:(id)arg1;
- (void)presentError:(id)arg1 modalForWindow:(id)arg2 delegate:(id)arg3 didPresentSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (id)makeDocumentWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (id)openDocumentWithContentsOfURL:(id)arg1 display:(BOOL)arg2 error:(id *)arg3;
- (void)removeDocument:(id)arg1;
- (void)addDocument:(id)arg1;
- (id)documentForURL:(id)arg1;
- (void)dealloc;
- (id)init;

@end

