//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSDocument, NSView;

@interface MGDocumentViewController : NSViewController
{
    NSDocument *_document;
    NSView *_initialFirstResponder;
}

@property NSView *initialFirstResponder; // @synthesize initialFirstResponder=_initialFirstResponder;
@property(readonly) NSDocument *document; // @synthesize document=_document;
- (void)loadView;
- (void)close;
- (id)initWithDocument:(id)arg1 nibName:(id)arg2 bundle:(id)arg3;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly, nonatomic, getter=isShowingDocumentModalInterface) BOOL showingDocumentModalInterface;
- (void)resignMainViewControllerForWindowController:(id)arg1;
- (void)becomeMainViewControllerForWindowController:(id)arg1;

@end

