//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocument.h"

@class MGDocumentWindowController;

@interface MGDocument : NSDocument
{
    MGDocumentWindowController *_mainWindowController;
    unsigned long long _editorCount;
}

+ (BOOL)autosavesDrafts;
+ (void)initialize;
- (id)printOperationWithSettings:(id)arg1 error:(id *)arg2;
- (void)objectDidEndEditing:(id)arg1;
- (void)objectDidBeginEditing:(id)arg1;
- (BOOL)isBeingEdited;
- (void)presentError:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)didPresentErrorWithRecovery:(BOOL)arg1 copiedCompletionHandler:(CDUnknownBlockType)arg2;
- (void)viewControllerDidLoadView:(id)arg1;
- (void)viewControllerWillLoadView:(id)arg1;
- (id)mainViewController;
- (id)mainWindowController;
- (void)removeWindowController:(id)arg1;
- (void)makeWindowControllers;
- (void)canCloseDocumentWithDelegate:(id)arg1 shouldCloseSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (void)dealloc;
- (void)setMainWindowController:(id)arg1;
- (id)handlePresentCommand:(id)arg1;
- (void)setPresenting:(BOOL)arg1;
- (BOOL)presenting;

@end

