//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSUserInterfaceValidations.h"
#import "NSWindowDelegate.h"

@class MGBackgroundColorView, MGDocumentViewController<MGVisualContentContainer>, NSDate, NSScreen;

@interface MGDocumentWindowController : NSWindowController <NSWindowDelegate, NSUserInterfaceValidations>
{
    MGDocumentViewController<MGVisualContentContainer> *_currentMainViewController;
    MGBackgroundColorView *_fullScreenAnimationBackgroundView;
    NSScreen *_fullScreenScreen;
    struct CGRect _savedNonFullScreenWindowFrame;
    struct CGSize _currentNaturalContentSize;
    struct CGPoint _cascadeTopLeftPoint;
    unsigned long long _cascadeIndex;
    double _windowContentScaleFactor;
    NSDate *_fullScreenUseDate;
    double _fullScreenUseTimeInterval[2];
    unsigned int _isFullScreen:1;
    unsigned int _isAnimatingFullScreen:1;
    unsigned int _didDisableSuddenTermination:1;
    unsigned int _needsResizeAfterFullScreenExit:1;
    unsigned int _isInInit:1;
    unsigned int _hasAttachedSheet:1;
    unsigned int _hasUserSize:1;
    unsigned int _hasSetInitialSizeForViewController:1;
    unsigned int _isFloating:1;
}

+ (id)keyPathsForValuesAffectingContentFullScreenCapable;
+ (id)keyPathsForValuesAffectingContentResizable;
+ (void)initialize;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)draggingEnded:(id)arg1;
- (void)concludeDragOperation:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)magnifyWithEvent:(id)arg1;
- (BOOL)window:(id)arg1 shouldPopUpDocumentPathMenu:(id)arg2;
- (void)windowDidEndSheet:(id)arg1;
- (void)windowWillBeginSheet:(id)arg1;
- (id)windowWillReturnUndoManager:(id)arg1;
- (BOOL)isShowingDocumentModalInterface;
- (void)updateTitlebarVisibility;
- (void)synchronizeWindowTitleWithDocumentName;
- (void)setFullScreen:(BOOL)arg1 duration:(double)arg2;
- (void)windowDidFailToExitFullScreen:(id)arg1;
- (void)window:(id)arg1 startCustomAnimationToExitFullScreenWithDuration:(double)arg2;
- (id)customWindowsToExitFullScreenForWindow:(id)arg1;
- (void)windowDidFailToEnterFullScreen:(id)arg1;
- (void)window:(id)arg1 startCustomAnimationToEnterFullScreenWithDuration:(double)arg2;
- (id)customWindowsToEnterFullScreenForWindow:(id)arg1;
- (id)_windowBackgroundColorForFullScreenMode:(id)arg1;
@property(nonatomic, getter=isFullScreen) BOOL fullScreen;
- (void)restoreStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)window:(id)arg1 didDecodeRestorableState:(id)arg2;
- (void)window:(id)arg1 willEncodeRestorableState:(id)arg2;
- (void)toggleFloating:(id)arg1;
@property(nonatomic, getter=isFloating) BOOL floating;
- (void)windowDidResize:(id)arg1;
- (void)decreaseSize:(id)arg1;
- (void)increaseSize:(id)arg1;
- (void)stepWindowSize:(long long)arg1;
- (void)fitToScreen:(id)arg1;
- (void)actualSize:(id)arg1;
- (void)resizeWindowToFitContent;
- (struct CGSize)preferredWindowContentSizeForSuggestedWindowContentSize:(struct CGSize)arg1;
- (void)setWindowContentSize:(struct CGSize)arg1 centered:(BOOL)arg2 onScreen:(id)arg3 animate:(BOOL)arg4;
- (BOOL)isContentFullScreenCapable;
- (BOOL)isContentResizable;
- (struct CGSize)naturalWindowContentSizeOnScreen:(id)arg1;
- (struct CGSize)adjustedNaturalContentSize;
- (struct CGSize)maximumWindowContentSizeOnScreen:(id)arg1;
- (struct CGSize)maximumWindowContentSize;
- (struct CGSize)minimumWindowContentSize;
- (struct CGSize)unconstrainedMinimumWindowContentSize;
- (BOOL)shouldCascadeWindows;
- (void)removeDocumentViewsFromWindow;
- (void)addDocumentViewsToWindow;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setWindow:(id)arg1;
- (void)setDocument:(id)arg1;
- (void)setCurrentMainViewController:(id)arg1;
- (id)currentMainViewController;
- (void)logFullScreenUse;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;

@end

