//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

@class MGMediaCompositionViewController, MGPlayerController, NSView;

@interface MGEditViewController : MGDocumentViewController
{
    NSView *_mediaCompositionView;
    MGMediaCompositionViewController *_mediaCompositionViewController;
    MGPlayerController *_playerController;
    BOOL _isInDraggingSourceOperation;
}

@property(nonatomic, getter=isInDraggingSourceOperation) BOOL inDraggingSourceOperation; // @synthesize inDraggingSourceOperation=_isInDraggingSourceOperation;
@property(readonly, nonatomic) NSView *mediaCompositionView; // @synthesize mediaCompositionView=_mediaCompositionView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)invalidateRestorableState;
- (void)restoreStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)parentViewControllerWillHideView:(id)arg1;
- (void)parentViewControllerDidShowView:(id)arg1;
- (void)setShowsAdditionalMediaTrack:(BOOL)arg1;
- (BOOL)showsAdditionalMediaTrack;
- (double)viewHeightShowingAdditionalMediaTrack:(BOOL)arg1;
@property(readonly, nonatomic) double timelineUpdateResolution;
- (void)close;
- (void)loadView;
- (void)dealloc;
- (id)initWithDocument:(id)arg1 nibName:(id)arg2 bundle:(id)arg3;

@end

