//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGEventHotKey;

@interface MGEventHotKeyMonitorToken : NSObject
{
    MGEventHotKey *_hotKey;
    CDUnknownBlockType _handlerBlock;
}

@property(readonly, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handlerBlock;
@property(readonly, nonatomic) MGEventHotKey *hotKey; // @synthesize hotKey=_hotKey;
- (void)dealloc;
- (id)init;
- (id)initWithHotKey:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end

