//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface MGEventHotKey : NSObject <NSCopying>
{
    unsigned long long _modifierFlags;
    NSString *_characters;
}

+ (id)hotKeyWithCharacters:(id)arg1 modifierFlags:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long modifierFlags; // @synthesize modifierFlags=_modifierFlags;
@property(readonly, nonatomic) NSString *characters; // @synthesize characters=_characters;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCharacters:(id)arg1 modifierFlags:(unsigned long long)arg2;

@end

