//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MGExclusiveHighlightView, NSString, NSWindow;

@interface MGExclusiveHighlightWindowController : NSWindowController
{
    NSWindow *_windowToHighlight;
    NSString *_label;
    MGExclusiveHighlightView *_overlayView;
}

- (void)fadeOutDidEndWithRetainedCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fadeOutWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)showWindow:(id)arg1;
- (void)applicationDidChangeScreenParameters:(id)arg1;
- (void)updateHighlightRect:(id)arg1;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;
- (id)initWithWindowToHighlight:(id)arg1 label:(id)arg2;

@end

