//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDictionary, NSImage, NSNumber, NSString;

@interface MGExportPreset : NSObject <NSCopying>
{
    NSDictionary *_presetDescription;
    NSImage *_movieFrameImage;
    double _movieDuration;
    NSNumber *_movieDataSize;
    BOOL _scalesUpWithoutImprovingQuality;
    BOOL _hasAudio;
    BOOL _selected;
    BOOL _alternate;
    BOOL _canPassthrough;
}

+ (id)exportPresetsWithDescriptions:(id)arg1 forAsset:(id)arg2 mediaComposition:(id)arg3;
+ (id)exportPresetsWithDescriptions:(id)arg1 forAsset:(id)arg2 mediaComposition:(id)arg3 previewThumbnailTime:(CDStruct_1b6d18a9)arg4;
+ (id)indexesOfPresetsWithDescriptions:(id)arg1 thatScaleUpToImproveQualityForSourceWithSize:(struct CGSize)arg2;
+ (id)alternateExportSettingsForPresetDescription:(id)arg1;
+ (id)exportSettingsForPresetDescription:(id)arg1;
@property(nonatomic, getter=isAlternate) BOOL alternate; // @synthesize alternate=_alternate;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
- (id)description;
- (BOOL)isAudioOnly;
@property(readonly, nonatomic) int type;
@property(readonly, nonatomic) NSNumber *identifier;
@property(readonly, nonatomic, getter=isEnabled) BOOL enabled;
@property(readonly, nonatomic) unsigned long long alternateEstimatedFileSize;
@property(readonly, nonatomic) unsigned long long estimatedFileSize;
@property(readonly, nonatomic) NSDictionary *passthroughSettings;
@property(readonly, nonatomic) NSDictionary *alternateExportSettings;
@property(readonly, nonatomic) NSDictionary *exportSettings;
@property(readonly, nonatomic) NSString *localizedEstimatedFileSizeDescription;
@property(readonly, nonatomic) NSString *localizedAlternateDescription;
@property(readonly, nonatomic) NSString *localizedDescription;
@property(readonly, nonatomic) NSString *localizedAlternateName;
@property(readonly, nonatomic) NSString *localizedName;
@property(readonly, nonatomic) NSImage *image;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithPresetDescription:(id)arg1 movieFrameImage:(id)arg2 movieDuration:(double)arg3 movieDataSize:(id)arg4 scalesUpWithoutImprovingQuality:(BOOL)arg5 hasAudio:(BOOL)arg6 canPassthrough:(BOOL)arg7;

@end

