//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MGExportPassthroughDescriptor : NSObject
{
    NSArray *_videoCodecs;
    NSArray *_audioCodecs;
    NSArray *_UTIs;
    struct CGSize _dimensions;
    double _videoDataRate;
    double _audioDataRate;
    double _audioSampleRate;
    double _duration;
    unsigned long long _dataSize;
}

+ (id)passthroughDescriptorFromDictionary:(id)arg1;
@property(copy, nonatomic) NSArray *UTIs; // @synthesize UTIs=_UTIs;
@property(nonatomic) unsigned long long maxDataSize; // @synthesize maxDataSize=_dataSize;
@property(nonatomic) double maxDuration; // @synthesize maxDuration=_duration;
@property(nonatomic) double audioSampleRate; // @synthesize audioSampleRate=_audioSampleRate;
@property(nonatomic) double videoDataRate; // @synthesize videoDataRate=_videoDataRate;
@property(nonatomic) double audioDataRate; // @synthesize audioDataRate=_audioDataRate;
@property(nonatomic) struct CGSize dimensions; // @synthesize dimensions=_dimensions;
@property(copy, nonatomic) NSArray *audioCodecs; // @synthesize audioCodecs=_audioCodecs;
@property(copy, nonatomic) NSArray *videoCodecs; // @synthesize videoCodecs=_videoCodecs;
- (id)description;
- (void)dealloc;
- (id)initPassthroughDescriptorFromDictionary:(id)arg1;

@end

