//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CALayer, MGPopUpLabelLayer, NSString;

@interface MGExclusiveHighlightView : NSView
{
    CALayer *_highlightLayer;
    MGPopUpLabelLayer *_highlightLabelLayer;
    struct CGRect _highlightFrame;
    NSString *_highlightLabel;
}

@property(copy, nonatomic) NSString *highlightLabel;
@property(nonatomic) struct CGRect highlightFrame;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

