//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MGFacebookAccount, NSDictionary, NSError, NSString, NSURL;

@interface MGFacebookPublishOperation : NSOperation
{
    MGFacebookAccount *_account;
    NSDictionary *_publishParameters;
    BOOL _finished;
    BOOL _executing;
    NSURL *_revealURL;
    NSError *_error;
    float _progress;
}

+ (id)facebookUploadURL;
@property(readonly) float progress; // @synthesize progress=_progress;
@property(copy) NSError *error; // @synthesize error=_error;
@property(copy) NSURL *revealURL; // @synthesize revealURL=_revealURL;
@property(readonly) NSString *localizedStatusMessage;
- (void)cancel;
- (void)handleUploadDidFinish;
- (void)startUploadOperation;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (void)start;
- (void)dealloc;
- (id)initWithParameters:(id)arg1 account:(id)arg2;

@end

