//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSXMLDocument;

@interface MGFacebookAPIResponse : NSObject
{
    NSData *_data;
    NSXMLDocument *_xmlDoc;
}

@property(copy) NSXMLDocument *xmlDoc; // @synthesize xmlDoc=_xmlDoc;
@property(copy) NSData *data; // @synthesize data=_data;
- (BOOL)isErrorResponse;
- (id)error;
- (id)FQLResponseRowsColumnOrder:(id *)arg1;
- (BOOL)isFQLResponse;
- (id)responseType;
- (id)nodesForXquery:(id)arg1;
- (id)stringForXquery:(id)arg1;
- (id)stringForKey:(id)arg1;
- (BOOL)isSuccess;
- (id)xmlRootElement;
- (id)responseObject:(id *)arg1;
- (void)dealloc;

@end

