//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDelegate.h"

@class NSError, NSString, SLFacebookSession;

@interface MGFacebookAccount : NSObject <NSURLConnectionDelegate>
{
    SLFacebookSession *_fbSession;
    NSError *_error;
    NSString *_accessToken;
    NSString *_userID;
    NSString *_userName;
    BOOL _permissions;
    BOOL _storeInKeyChain;
    BOOL _authorized;
    BOOL _authenticating;
    BOOL _sessionExpired;
    unsigned long long _userMovieSizeLimit;
    CDStruct_1b6d18a9 _userMovieDurationLimit;
}

+ (id)storedAccountWithUserName:(id)arg1;
+ (id)errorWithCode:(long long)arg1 localizedDescription:(id)arg2 HTTPStatusCode:(long long)arg3;
+ (id)humanReadableErrorForErrorCodeAndMessage:(long long)arg1 errorDescription:(id)arg2;
@property(readonly, nonatomic) SLFacebookSession *fbSession; // @synthesize fbSession=_fbSession;
@property(nonatomic) CDStruct_1b6d18a9 userMovieDurationLimit; // @synthesize userMovieDurationLimit=_userMovieDurationLimit;
@property(nonatomic) unsigned long long userMovieSizeLimit; // @synthesize userMovieSizeLimit=_userMovieSizeLimit;
@property(nonatomic) BOOL sessionExpired; // @synthesize sessionExpired=_sessionExpired;
@property(nonatomic, getter=isAuthenticating) BOOL authenticating; // @synthesize authenticating=_authenticating;
@property(nonatomic, getter=isAuthorized) BOOL authorized; // @synthesize authorized=_authorized;
@property(nonatomic) BOOL storeInKeyChain; // @synthesize storeInKeyChain=_storeInKeyChain;
@property(nonatomic) BOOL permissions; // @synthesize permissions=_permissions;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
- (void)terminateCurrentUserSession:(BOOL)arg1;
- (void)validateAuthentication:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)validateUserAuthorization:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithUserName:(id)arg1 password:(id)arg2 accessToken:(id)arg3;

@end

