//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGMovieThumbnailExtractor.h"

@interface MGFigPlaybackItemMovieThumbnailExtractor : MGMovieThumbnailExtractor
{
    struct OpaqueFigPlayer *_player;
    struct OpaqueFigPlaybackItem *_playbackItem;
    CDStruct_977f9211 _availableRange;
}

+ (BOOL)canInitWithMovie:(id)arg1;
- (id)availableThumbnailTimeRanges;
- (id)extractedThumbnailBitmapWithSize:(struct CGSize)arg1 atTime:(CDStruct_900afa40)arg2;
- (void)dealloc;
- (id)initWithMovie:(id)arg1 dispatchQueue:(id)arg2;

@end

