//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class MGFlickrRESTInterface, NSError, NSString;

@interface MGFlickrAccount : NSObject <NSCoding, NSCopying>
{
    MGFlickrRESTInterface *_interface;
    NSString *_authTokenSecret;
    NSString *_authToken;
    NSString *_userName;
    NSString *_password;
    NSError *_error;
    BOOL _authenticated;
}

+ (id)storedAccountWithUserName:(id)arg1;
+ (unsigned long long)maximumMovieDataSizeForFlickr;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) BOOL authenticated; // @synthesize authenticated=_authenticated;
@property(copy, nonatomic) NSString *authTokenSecret; // @synthesize authTokenSecret=_authTokenSecret;
@property(copy, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain) MGFlickrRESTInterface *interface; // @synthesize interface=_interface;
- (id)description;
- (void)checkAuthentication;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithUserName:(id)arg1 password:(id)arg2 authToken:(id)arg3 authTokenSecret:(id)arg4;

@end

