//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGJob.h"

@class MGExportOperation, MGFlickrPublishOperation, MGFlickrPublishStatusOperation, MGFlickrRESTInterface, NSError, NSString, NSURL;

@interface MGFlickrPublishJob : MGJob
{
    MGExportOperation *_exportOperation;
    MGFlickrPublishOperation *_publishOperation;
    MGFlickrPublishStatusOperation *_publishStatusOperation;
    NSString *_name;
    BOOL _progressIndeterminate;
    float _progress;
    NSURL *_resultURL;
    BOOL _canReveal;
    NSString *_runningStatusString;
    NSString *_finishedStatusString;
    NSError *_error;
    NSString *_publishedVideoID;
    MGFlickrRESTInterface *_flickrInterface;
}

@property(copy, nonatomic) NSString *publishedVideoID; // @synthesize publishedVideoID=_publishedVideoID;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(copy, nonatomic) NSString *finishedStatusString; // @synthesize finishedStatusString=_finishedStatusString;
@property(copy, nonatomic) NSString *runningStatusString; // @synthesize runningStatusString=_runningStatusString;
@property(nonatomic) BOOL canReveal; // @synthesize canReveal=_canReveal;
@property(copy, nonatomic) NSURL *resultURL; // @synthesize resultURL=_resultURL;
@property(nonatomic, getter=isProgressIndeterminate) BOOL progressIndeterminate; // @synthesize progressIndeterminate=_progressIndeterminate;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)reveal;
- (id)operations;
- (void)dealloc;
- (id)initWithMediaComposition:(id)arg1 flickrInterface:(id)arg2 publishParameters:(id)arg3;

@end

