//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class MGFlickrRESTInterface, NSDictionary, NSError, NSMutableData, NSString, NSURLConnection, NSURLRequest, NSURLResponse;

@interface MGFlickrPublishOperation : NSOperation <NSURLConnectionDelegate>
{
    NSDictionary *_publishParameters;
    BOOL _finished;
    BOOL _executing;
    float _progress;
    unsigned long long _dataSize;
    NSString *_ticketsString;
    MGFlickrRESTInterface *_flickrInterface;
    NSError *_error;
    NSMutableData *_downloadedData;
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSURLConnection *_currentConnection;
}

+ (id)flickrUploadURL;
@property(readonly) float progress; // @synthesize progress=_progress;
@property(copy, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(copy, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(copy) NSString *ticketsString; // @synthesize ticketsString=_ticketsString;
@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) NSString *localizedStatusMessage;
@property(readonly, nonatomic) NSString *MIMEBoundary;
- (void)cancel;
- (void)handleUploadDidFinish;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (id)processUploadResponseXML:(id)arg1;
- (id)processUploadErrorResponseXML:(id)arg1;
- (void)startUploadOperation;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (void)start;
- (void)dealloc;
- (id)initWithParameters:(id)arg1 flickrInterface:(id)arg2;

@end

