//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MGFormatDescription : NSObject
{
    struct opaqueCMFormatDescription *_formatDescription;
}

+ (id)formatNameForCMFormatDescription:(struct opaqueCMFormatDescription *)arg1;
- (id)formatName;
- (struct CGSize)presentationDimensions;
- (id)localizedSummary;
- (void)dealloc;
- (id)initWithCMFormatDescription:(struct opaqueCMFormatDescription *)arg1;

@end

