//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGLayerCollectionViewDelegate.h"
#import "MGViewLayoutManager.h"

@class MGBackgroundColorView, MGGridLayerCollectionView, MGLayoutManagedView, NSButton;

@interface MGFullScreenChapterViewController : MGDocumentViewController <MGLayerCollectionViewDelegate, MGViewLayoutManager>
{
    MGGridLayerCollectionView *_collectionView;
    MGBackgroundColorView *_backgroundView;
    MGBackgroundColorView *_separatorView;
    MGLayoutManagedView *_layoutManagedView;
    NSButton *_previousPageButton;
    NSButton *_nextPageButton;
    CDStruct_1b6d18a9 _pendingShowChaoterTime;
    struct CGSize _maxThumbnailAspectRatio;
    double _minimumOrderInTimeForNextChapterLayer;
    id <MGFullScreenChapterViewControllerDelegate> _delegate;
    BOOL _isCollectionViewSetUp;
    BOOL _isCurrentChapterIndicatorAssigned;
}

+ (void)initialize;
@property(nonatomic) id <MGFullScreenChapterViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)beginGestureWithEvent:(id)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)cancel:(id)arg1;
- (void)layerCollectionView:(id)arg1 didChooseRepresentedObjectsAtIndexes:(id)arg2 withEvent:(id)arg3;
- (void)layoutSubviewsOfView:(id)arg1 resizedFromOldSize:(struct CGSize)arg2;
- (void)resetMinimumOrderInTimeForNextChapterLayer;
- (id)layerCollectionView:(id)arg1 layerControllerForRepresentedObjectAtIndex:(unsigned long long)arg2;
- (void)showChapterAtTime:(CDStruct_1b6d18a9)arg1;
- (void)close;
- (void)loadView;

@end

