//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGLayerCollectionView.h"

@class CAScrollLayer, NSMapTable;

@interface MGGridLayerCollectionView : MGLayerCollectionView
{
    CAScrollLayer *_contentLayer;
    NSMapTable *_contentContainerLayers;
    unsigned long long _numberOfRows;
    unsigned long long _numberOfColumns;
    unsigned long long _indexOfCurrentPage;
    double _margins[4];
}

+ (id)keyPathsForValuesAffectingCanGoToNextPage;
+ (id)keyPathsForValuesAffectingCanGoToPreviousPage;
+ (id)keyPathsForValuesAffectingNumberOfPages;
@property(nonatomic) unsigned long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(nonatomic) unsigned long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
- (void)keyDown:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeLayerControllerForRepresentedObject:(id)arg1;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)scrollToCurrentPage;
- (struct _NSRange)representedObjectIndexRangeForCurrentPage;
- (struct CGRect)frameForItemAtIndex:(unsigned long long)arg1;
- (struct CGRect)frameInContentLayerForItemAtIndex:(unsigned long long)arg1;
- (void)setMargin:(double)arg1 forEdge:(unsigned long long)arg2;
- (double)marginForEdge:(unsigned long long)arg1;
- (void)goToNextPage:(id)arg1;
@property(readonly, nonatomic) BOOL canGoToNextPage;
- (void)goToPreviousPage:(id)arg1;
@property(readonly, nonatomic) BOOL canGoToPreviousPage;
@property(nonatomic) unsigned long long indexOfCurrentPage;
@property(readonly, nonatomic) unsigned long long numberOfPages;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;

@end

