//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MGHelperProcessClient.h"

@class NSConnection, NSRunLoop, NSTask, Protocol;

@interface MGHelperProcess : NSObject <MGHelperProcessClient>
{
    NSTask *_task;
    NSRunLoop *_taskRunLoop;
    BOOL _taskRunLoopIsAnonymousRunLoop;
    BOOL _running;
    int _taskTerminationStatus;
    NSConnection *_serverReplyConnection;
    id _principalObjectProxy;
    Protocol *_principalObjectProtocol;
    id <MGHelperProcessMainController> _mainControllerProxy;
}

+ (void)stopUsingAnonymousRunLoop;
+ (id)startUsingAnonymousRunLoop;
+ (id)helperProcessWithPrincipalObjectClassName:(id)arg1 protocol:(id)arg2;
- (void)taskDidTerminate:(id)arg1;
- (void)taskDidTerminateOnTaskRunLoop;
- (oneway void)mainControllerDidBecomeAvailable:(id)arg1;
- (void)waitUntilPrincipalObjectBecomesAvailable;
- (void)waitUntilPrincipalObjectBecomesAvailableOnTaskRunLoop;
- (id)principalObjectProxy;
- (int)terminationStatus;
- (void)waitUntilExit;
- (BOOL)isRunning;
- (void)exit;
- (void)launch;
- (void)scheduleInRunLoop:(id)arg1;
- (void)dealloc;
- (id)initWithPrincipalObjectClassName:(id)arg1 protocol:(id)arg2;
- (id)init;

@end

