//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBitmapImageRep, NSString;

@protocol MGHelperProcessMovieThumbnailExtractorImpl <NSObject>
- (bycopy NSBitmapImageRep *)extractedThumbnailBitmapWithSize:(struct CGSize)arg1 atTime:(NSString *)arg2;
- (NSString *)availableTimeRangeString;
- (BOOL)beginExtractionFromMovieWithDataOrURL:(bycopy id)arg1 delegate:(id <MGHelperProcessMovieThumbnailExtractorImplDelegate>)arg2;
@end

