//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MGHelperProcessMovieThumbnailExtractorImplDelegate.h"

@class MGHelperProcessMovieThumbnailExtractor;

@interface MGHelperProcessMovieThumbnailExtractorImplDelegate : NSObject <MGHelperProcessMovieThumbnailExtractorImplDelegate>
{
    MGHelperProcessMovieThumbnailExtractor *_extractor;
}

- (oneway void)thumbnailExtractionSessionImplAvailableTimeRangeDidChange;
- (id)init;
- (id)initWithExtractor:(id)arg1;

@end

