//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTHUDTimelineCell.h"

@class NSTimer;

@interface MGHUDTimelineCell : QTHUDTimelineCell
{
    BOOL _expand;
    double _savedValue;
    double _savedX;
    struct CGRect *_cellFrame;
    unsigned long long _animationCount;
    NSTimer *_animationTimer;
}

- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)fireExpandAnimationTimer:(id)arg1;
- (void)stopTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3 mouseIsUp:(BOOL)arg4;
- (BOOL)continueTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3;
- (BOOL)startTrackingAt:(struct CGPoint)arg1 inView:(id)arg2;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (void)_updateValuesWithPoint:(struct CGPoint)arg1 inView:(id)arg2;
- (void)_expand;
- (BOOL)_frameAccurateScrubbingInView:(id)arg1;
- (BOOL)shouldDetectMouseHold;
- (double)valueAtPoint:(struct CGPoint)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)setDoubleValue:(double)arg1;
@property(nonatomic) BOOL expand;

@end

