//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSTextField, NSTextView;

@interface MGInfoWindowItemView : NSView
{
    NSTextField *_labelTextField;
    NSTextView *_valueTextView;
    int _tag;
}

+ (id)infoItemViewWithLabel:(id)arg1 withClickableValue:(id)arg2;
+ (id)infoItemViewWithLabel:(id)arg1 withValue:(id)arg2;
+ (id)infoItemViewWithAttributedValue:(id)arg1;
+ (id)infoItemViewWithValue:(id)arg1;
+ (id)infoItemViewWithView:(id)arg1;
- (void)setAttributedValue:(id)arg1;
- (void)setValue:(id)arg1;
- (void)setLabel:(id)arg1;
- (id)label;
- (id)value;
- (id)valueTextView;
- (id)labelTextField;
- (void)dealloc;
- (id)initWithLabel:(id)arg1 withValue:(id)arg2;
- (id)initWithLabel:(id)arg1 withClickableValue:(id)arg2;
- (id)initWithAttributedValue:(id)arg1;
- (id)initWithValue:(id)arg1;
- (id)initWithView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

