//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class MGInfoWindowItemView, NSBox, NSMutableArray, NSString, NSView, NSWindow;

@interface MGInfoWindowController : NSWindowController <NSWindowDelegate>
{
    NSWindow *_inspectedDocumentWindow;
    NSView *_detailsView;
    NSView *_topView;
    NSMutableArray *_infoItems;
    MGInfoWindowItemView *_titleView;
    MGInfoWindowItemView *_informationView;
    NSBox *_separatorView;
    NSString *_windowTopLeftPointAutosaveName;
    struct {
        unsigned int isInspector:1;
        unsigned int windowHasInitialPosition:1;
        unsigned int needsUpdate:1;
        unsigned int disableUpdates:1;
    } _flags;
}

+ (BOOL)shouldSharedInfoWindowBeVisibleAtLaunch;
+ (BOOL)isSharedInfoWindowVisible;
+ (id)sharedInfoWindowController;
- (void)updateIfNeeded;
- (void)setNeedsUpdate;
- (void)rearrangeViews;
- (void)updateDetails;
- (void)updateInformation;
- (void)updateAnnotations;
- (void)updateTitle;
- (void)updateSeparator;
- (void)synchronizeWindowTitleWithDocumentName;
- (void)resetInfoPanel;
- (void)infoWindowDidMove:(id)arg1;
- (void)infoWindowWillClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)showHidePanel;
- (void)close;
- (void)infoWindowDidOrderOffScreen:(id)arg1;
- (void)infoWindowWillOrderOnScreen:(id)arg1;
- (void)anyWindowDidBecomeMain:(id)arg1;
- (void)anyWindowDidResignMain:(id)arg1;
- (void)becomeInspectorForDocumentWindow:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setDocument:(id)arg1;
- (id)separatorView;
- (id)informationView;
- (id)titleView;
- (id)detailsView;
- (id)topView;
- (id)windowFrameAutosaevUserDefaultsKey;
- (void)setWindowFrameAutosaveName:(id)arg1;
- (id)windowFrameAutosaveName;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;
- (id)initAsInspector:(BOOL)arg1;

@end

