//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGJobController.h"

@class MGJob, NSError, NSString, NSURL;

@interface MGiTunesJobController : MGJobController
{
    MGJob *_activeJob;
    NSError *_error;
    NSURL *_resultURL;
    NSString *_name;
}

@property(retain, nonatomic) MGJob *activeJob; // @synthesize activeJob=_activeJob;
- (BOOL)restoreFromDictionaryRepresentation:(id)arg1;
- (id)savedDictionaryRepresentation;
- (id)resultURL;
- (id)error;
- (id)statusString;
- (id)icon;
- (id)name;
- (id)identifier;
- (void)dealloc;
- (id)initActiveJobWithMediaComposition:(id)arg1 name:(id)arg2 exportParameters:(id)arg3;

@end

