//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGJob, NSError, NSImage, NSString, NSURL;

@interface MGJobController : NSObject
{
}

+ (id)keyPathsForValuesAffectingProgressIndeterminate;
+ (id)keyPathsForValuesAffectingCanReveal;
+ (id)keyPathsForValuesAffectingProgress;
+ (id)keyPathsForValuesAffectingCancelled;
+ (id)keyPathsForValuesAffectingFinished;
+ (id)keyPathsForValuesAffectingStatusString;
+ (id)keyPathsForValuesAffectingResultURL;
+ (id)keyPathsForValuesAffectingName;
- (id)description;
- (void)reveal;
- (BOOL)restoreFromDictionaryRepresentation:(id)arg1;
- (id)savedDictionaryRepresentation;
@property(readonly, nonatomic) BOOL shouldAutomaticallyRemoveWhenActiveJobIsFinished;
- (void)cancel;
@property(readonly, nonatomic, getter=isProgressIndeterminate) BOOL progressIndeterminate;
@property(readonly, nonatomic) float progress;
@property(readonly, nonatomic) BOOL canReveal;
@property(readonly, nonatomic, getter=isFinished) BOOL finished;
@property(readonly, nonatomic, getter=isCancelled) BOOL cancelled;
@property(readonly, nonatomic) BOOL canUnpublish;
- (void)unpublish;
@property(readonly, nonatomic) NSError *error;
@property(readonly, nonatomic) NSString *statusString;
@property(readonly, nonatomic) NSURL *resultURL;
@property(readonly, nonatomic) NSImage *icon;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) MGJob *activeJob;
@property(readonly, nonatomic) NSString *identifier;

@end

