//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGProgressEstimator, NSError, NSSet, NSString, NSURL;

@interface MGJob : NSObject
{
    unsigned long long _numberOfUnfinishedOperations;
    unsigned int _cancelled:1;
    double _estimatedTimeRemaining;
    MGProgressEstimator *_progressEstimator;
}

+ (id)keyPathsForValuesAffectingStatusString;
+ (id)keyPathsForValuesAffectingCanReveal;
+ (void)initialize;
@property(readonly, nonatomic) double estimatedTimeRemaining; // @synthesize estimatedTimeRemaining=_estimatedTimeRemaining;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)canCancelOperation:(id)arg1;
- (void)cancel;
@property(readonly, nonatomic, getter=isCancelled) BOOL cancelled;
- (void)_decrementNumberOfUnfinishedOperations;
@property(readonly, nonatomic, getter=isFinished) BOOL finished;
- (void)startOnOperationQueue:(id)arg1;
- (void)_beginObservingProgress;
- (void)_periodicUpdateEstimatedTimeRemaining:(id)arg1;
- (void)_updateEstimatedTimeRemaining;
@property(readonly, nonatomic) NSString *statusString;
@property(readonly, nonatomic) BOOL canReveal;
@property(readonly, nonatomic) NSError *error;
@property(readonly, nonatomic) NSString *finishedStatusString;
@property(readonly, nonatomic) NSString *runningStatusString;
@property(readonly, nonatomic) NSURL *resultURL;
@property(readonly, nonatomic) float progress;
@property(readonly, nonatomic) NSSet *operations;
- (void)dealloc;
- (id)init;
@property(readonly, nonatomic, getter=isProgressIndeterminate) BOOL progressIndeterminate;
- (void)reveal;

@end

