//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSUserInterfaceValidations.h"
#import "NSWindowRestoration.h"

@class MGJobManager, NSArray, NSArrayController, NSCollectionView, NSMutableArray, NSScrollView, NSTextField;

@interface MGJobProcessingWindowController : NSWindowController <NSWindowRestoration, NSUserInterfaceValidations>
{
    NSScrollView *jobsScrollView;
    NSCollectionView *jobsCollectionView;
    NSTextField *jobsCountField;
    NSArrayController *jobArrayController;
    BOOL _didAutoShow;
    unsigned long long _countOfJobsToUnpublish;
    NSMutableArray *_unpublishFailedArray;
}

+ (id)keyPathsForValuesAffectingJobControllers;
+ (id)keyPathsForValuesAffectingCanClearJobControllers;
+ (id)keyPathsForValuesAffectingCanUnpublishSelectedJobController;
+ (id)sharedJobProcessingWindowController;
+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)handleUnpublishOver;
- (void)unpublishCompleteAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)unpublishJobController:(id)arg1 didFailWithError:(id)arg2;
- (void)deleteBackward:(id)arg1;
- (void)deleteForward:(id)arg1;
- (void)deleteSelectedJobControllers;
- (void)handleJobsUpdate;
- (void)jobPublishFinished:(id)arg1;
- (void)updateJobControllersCountString;
- (void)terminationAlertAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)displayAlertForApplicationTermination;
- (void)unpublishFromFlickr:(id)arg1;
- (void)unpublishFromYouTube:(id)arg1;
- (void)unpublish:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)clearFinishedJobControllers:(id)arg1;
@property(readonly, nonatomic) BOOL canClearJobControllers;
@property(readonly, nonatomic) MGJobManager *jobManager;
@property(readonly, nonatomic) NSArray *jobControllers;
@property(readonly, nonatomic) unsigned long long countOfJobsToUnpublish;
- (void)close;
- (void)autoShowWindow:(id)arg1;
- (void)unpublishSelectedJobControllers;
- (BOOL)canUnpublishSelectedJobControllersWithIdentifier:(id)arg1;
- (BOOL)canUnpublishSelectedJobController;
- (void)dealloc;
- (id)init;
- (void)windowDidLoad;

@end

