//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCountedSet, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface MGKeyValueProxy : NSObject
{
    id _target;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_queueLocalProxiedKeyValuePairs;
    NSObject<OS_dispatch_queue> *_proxiedKeyTriggerQueue;
    NSMutableDictionary *_proxiedKeysTriggeredByNonProxiedKeysTable;
    NSMutableSet *_proxiedKeysAnalyzedForTriggers;
    NSObject<OS_dispatch_queue> *_observedProxiedKeysQueue;
    NSCountedSet *_observedProxiedKeys;
}

+ (BOOL)shouldProxyValueForKey:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) id target; // @synthesize target=_target;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)_discoverTriggerKeysForKey:(id)arg1;
- (void)didChangeValueForKey:(id)arg1;
- (void)willChangeValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)valueForKey:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)initWithTarget:(id)arg1 queue:(id)arg2;
- (id)MGKeyValueProxyTarget_keyPathsForValuesAffectingValueForKey:(id)arg1;

@end

