//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSArray, NSIndexSet, NSMapTable, NSMutableDictionary, NSTrackingArea;

@interface MGLayerCollectionView : NSView
{
    id <MGLayerCollectionViewDelegate> delegate;
    NSArray *_content;
    NSIndexSet *_selectionIndexes;
    NSMapTable *_contentLayerControllers;
    NSMutableDictionary *_binders;
    NSTrackingArea *_trackingArea;
    id _mouseEnterExitMovedTrackingRepresentedObject;
    id _eventTrackingRepresentedObject;
    BOOL _usesMouseLocationForSelection;
    BOOL _isFirstResponder;
    BOOL _contentLayerControllerIsHandlingEvent;
    unsigned long long _numberOfSelectedLayerControllersThatHandledEvent;
}

+ (void)initialize;
@property(retain, nonatomic) id eventTrackingRepresentedObject; // @synthesize eventTrackingRepresentedObject=_eventTrackingRepresentedObject;
@property(nonatomic) id <MGLayerCollectionViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL usesMouseLocationForSelection; // @synthesize usesMouseLocationForSelection=_usesMouseLocationForSelection;
- (void)flagsChanged:(id)arg1;
- (void)keyUp:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)otherMouseUp:(id)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)otherMouseDragged:(id)arg1;
- (void)rightMouseDragged:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)otherMouseDown:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
@property(retain, nonatomic) id mouseEnterExitMovedTrackingRepresentedObject;
- (id)representedObjectAtPoint:(struct CGPoint)arg1;
- (unsigned long long)indexOfRepresentedObjectAtPoint:(struct CGPoint)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)unbind:(id)arg1;
- (void)bind:(id)arg1 toObject:(id)arg2 withKeyPath:(id)arg3 options:(id)arg4;
- (id)infoForBinding:(id)arg1;
- (void)removeLayerControllerForRepresentedObject:(id)arg1;
- (id)layerControllerForRepresentedObjectAtIndex:(unsigned long long)arg1;
- (BOOL)isFirstResponder;
@property(copy, nonatomic) NSIndexSet *selectionIndexes;
@property(copy, nonatomic) NSArray *content;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (unsigned long long)accessibilityIndexOfChild:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityItemForIndex:(unsigned long long)arg1;

@end

