//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MGLanguage, NSString;

@interface MGLanguageAlternate : NSObject <NSCopying>
{
    id _identifier;
    MGLanguage *_language;
    NSString *_customLocalizedName;
}

+ (id)languageAlternateWithLanguage:(id)arg1 identifier:(id)arg2 customLocalizedName:(id)arg3;
@property(readonly, nonatomic) id identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) MGLanguage *language; // @synthesize language=_language;
- (id)description;
@property(readonly, nonatomic) NSString *localizedName;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithLanguage:(id)arg1 identifier:(id)arg2 customLocalizedName:(id)arg3;

@end

