//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGLayerCollectionView;

@interface MGLayerCollectionViewAccessibilityItem : NSObject
{
    MGLayerCollectionView *_collectionView;
    unsigned long long _index;
}

@property(readonly, nonatomic) unsigned long long index; // @synthesize index=_index;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (struct CGRect)accessibilityRect;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (id)representedLayerController;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithParentView:(id)arg1 index:(unsigned long long)arg2;

@end

