//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSResponder.h"

@class CALayer, NSView;

@interface MGLayerController : NSResponder
{
    CALayer *_layer;
    NSView *_rootView;
    id _representedObject;
    BOOL _selected;
}

@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(retain, nonatomic) id representedObject; // @synthesize representedObject=_representedObject;
@property(nonatomic) NSView *rootView; // @synthesize rootView=_rootView;
- (void)close;
- (void)setLayer:(id)arg1;
- (void)loadLayer;
- (BOOL)isLayerLoaded;
- (id)layer;
- (void)dealloc;

@end

