//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface MGLayoutManagedView : NSView
{
    id <MGViewLayoutManager> _layoutManager;
}

@property id <MGViewLayoutManager> layoutManager; // @synthesize layoutManager=_layoutManager;
- (void)drawRect:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;

@end

