//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSLocale, NSString;

@interface MGLanguage : NSObject <NSCopying>
{
    id _languageCode;
    int _type;
}

+ (id)systemLanguage;
+ (id)languageWithLanguageCode:(id)arg1 type:(int)arg2;
@property(readonly, nonatomic) int type; // @synthesize type=_type;
@property(readonly, nonatomic) id languageCode; // @synthesize languageCode=_languageCode;
- (id)description;
- (BOOL)isEqualToSystemLanguage;
@property(readonly, nonatomic) NSLocale *locale;
@property(readonly, nonatomic) NSString *localizedName;
- (id)localeIdentifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithLanguageCode:(id)arg1 type:(int)arg2;
- (id)init;

@end

