//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGLayerCollectionView, MGLayerController, NSEvent, NSIndexSet;

@protocol MGLayerCollectionViewDelegate <NSObject>

@optional
- (void)layerCollectionView:(MGLayerCollectionView *)arg1 didChooseRepresentedObjectsAtIndexes:(NSIndexSet *)arg2 withEvent:(NSEvent *)arg3;
- (MGLayerController *)layerCollectionView:(MGLayerCollectionView *)arg1 layerControllerForRepresentedObjectAtIndex:(unsigned long long)arg2;
@end

