//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaTimelineTrack;

@interface MGMediaTimelineTrackPreview : NSObject
{
    MGMediaTimelineTrack *_timelineTrack;
}

- (id)previewLayer;
- (void)setTimelineTrack:(id)arg1;
- (id)timelineTrack;

@end

