//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGMediaTimelineTrackPreview.h"

@class CALayer;

@interface MGMediaTimelineTrackVideoPreview : MGMediaTimelineTrackPreview
{
    id <MGMediaTimelineTrackVideoPreviewThumbnailProvider> _thumbnailProvider;
    CALayer *_previewLayer;
    struct CGSize _videoNaturalSize;
    struct CGSize _thumbnailSize;
    struct CGSize _lastPreviewLayerBoundsSize;
    CDStruct_900afa40 _mediaDuration;
    CDStruct_900afa40 _mediaTimeOffset;
    BOOL _thumbnailsAreInvalid;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) struct CGSize videoNaturalSize;
- (void)invalidateThumbnails;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)previewLayer;
- (void)setTimelineTrack:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithThumbnailProvider:(id)arg1;

@end

