//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaTimelineView;

@protocol MGMediaTimelineViewDelegate <NSObject>

@optional
- (CDStruct_900afa40)timelineView:(MGMediaTimelineView *)arg1 willStepBackwardCurrentMediaTimeToTime:(CDStruct_900afa40)arg2;
- (CDStruct_900afa40)timelineView:(MGMediaTimelineView *)arg1 willStepForwardCurrentMediaTimeToTime:(CDStruct_900afa40)arg2;
- (CDStruct_900afa40)timelineView:(MGMediaTimelineView *)arg1 willChangeCurrentMediaTimeToTime:(CDStruct_900afa40)arg2;
- (void)timelineViewDidStopTrackingCurrentMediaTime:(MGMediaTimelineView *)arg1;
- (void)timelineViewWillStartTrackingCurrentMediaTime:(MGMediaTimelineView *)arg1;
- (CDStruct_900afa40)timelineView:(MGMediaTimelineView *)arg1 willStepBackwardSelectionEdge:(int)arg2 toTime:(CDStruct_900afa40)arg3;
- (CDStruct_900afa40)timelineView:(MGMediaTimelineView *)arg1 willStepForwardSelectionEdge:(int)arg2 toTime:(CDStruct_900afa40)arg3;
- (CDStruct_900afa40)timelineView:(MGMediaTimelineView *)arg1 willChangeSelectionEdge:(int)arg2 toTime:(CDStruct_900afa40)arg3;
- (void)timelineView:(MGMediaTimelineView *)arg1 didStopTrackingSelectionEdge:(int)arg2;
- (void)timelineView:(MGMediaTimelineView *)arg1 willStartTrackingSelectionEdge:(int)arg2;
@end

