//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CALayer, MGMediaTrackLayer, MGMediaTrackViewController, NSArray, NSMutableArray, NSTrackingArea;

@interface MGMediaTrackView : NSView
{
    MGMediaTrackViewController *_viewController;
    NSArray *_mediaTrackViewItems;
    NSMutableArray *_addedMediaTrackViewItems;
    NSMutableArray *_removedMediaTrackViewItems;
    MGMediaTrackLayer *_mediaTrackLayer;
    CALayer *_spaceAvailableIndicatorLayer;
    NSTrackingArea *_viewBoundsTrackingArea;
    double _relativeScrollPosition;
    unsigned int _didCreateLayers:1;
    unsigned int _mediaTrackLayerNeedsUpdate:1;
    unsigned int _playheadLayerNeedsUpdate:1;
}

@property(readonly, nonatomic) NSTrackingArea *viewBoundsTrackingArea; // @synthesize viewBoundsTrackingArea=_viewBoundsTrackingArea;
@property(nonatomic) MGMediaTrackViewController *viewController; // @synthesize viewController=_viewController;
- (struct CGRect)mediaTrackViewItemFrameInView:(id)arg1;
- (struct CGRect)mediaTrackViewItemFrameInMediaTrackLayer:(id)arg1;
- (struct CGRect)mediaTrackLayerFrameInView;
- (id)mediaTrackViewItemAtLocationInView:(struct CGPoint)arg1;
- (CDStruct_1b6d18a9)timeAtLocationInView:(struct CGPoint)arg1;
- (struct CGRect)playheadLayerFrameInView;
- (BOOL)isPlayheadLayerAtLocationInView:(struct CGPoint)arg1;
- (void)bounceMediaTrackViewItems:(id)arg1;
- (void)scrollToRelativePosition:(double)arg1 animated:(BOOL)arg2;
- (void)updatePlayheadLayerIfNeeded;
- (void)setPlayheadLayerNeedsUpdate;
- (void)updateMediaTrackLayerIfNeeded;
- (void)setMediaTrackLayerNeedsUpdate;
- (void)showMediaTrackViewItems:(id)arg1 animated:(BOOL)arg2;
- (void)hideMediaTrackViewItems:(id)arg1 animated:(BOOL)arg2;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (BOOL)mouseDownCanMoveWindow;
- (void)updateTrackingAreas;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;
- (void)viewDidMoveToWindow;
@property(readonly, nonatomic) double viewHeight;
@property(retain, nonatomic) NSArray *mediaTrackViewItems;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)spaceAvailableIndicatorImage;
- (void)windowDidChangeBackingProperties:(id)arg1;
- (double)relativeSizeOfMediaTrackViewItemAtIndex:(unsigned long long)arg1;
- (double)mediaTrackViewItemThumbnailsWidth;
- (double)mediaTrackViewItemLayerHeight;
- (BOOL)showsOutOfRangeIndicator;
- (BOOL)showsSpaceAvailableIndicator;
- (void)scrollMediaTrackLayerToRelativePosition:(double)arg1 animated:(BOOL)arg2;
- (void)positionPlayheadLayer;
- (void)scrollMediaTrackLayer;
- (void)layoutMediaTrackLayer;
- (void)assignMediaTrackLayer;
- (id)accessibilityHitTest:(struct CGPoint)arg1;

@end

