//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGPlayerDocument;

@interface MGMediaClipPreviewProvider : NSObject
{
    MGPlayerDocument *_document;
}

- (id)audioPreviewForMediaClip:(id)arg1;
- (id)videoPreviewForMediaClip:(id)arg1;
- (id)playerItemFromMediaClip:(id)arg1 withDuration:(CDStruct_1b6d18a9)arg2 atEnd:(BOOL)arg3;
- (void)dealloc;
- (id)initWithDocument:(id)arg1;

@end

