//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MGMediaTimelineTracksView, MGSimpleBinder, NSArray, NSSet;

@interface MGMediaTimelineView : NSView
{
    CDStruct_900afa40 _mediaDuration;
    CDStruct_900afa40 _mediaTimeOffset;
    double _minimumPointsPerSecond;
    MGMediaTimelineTracksView *_tracksView;
    BOOL _hasEnclosingScrollView;
    BOOL _pinAtMinimumPointsPerSecond;
    BOOL _mutatingTracksViewTimes;
    MGSimpleBinder *_selectionStartBinder;
    MGSimpleBinder *_selectionEndBinder;
    MGSimpleBinder *_currentMediaTimeBinder;
    id <MGMediaTimelineViewDelegate> _delegate;
}

+ (CDStruct_900afa40)mediaTimeForPosition:(double)arg1 outOfMediaDuration:(CDStruct_900afa40)arg2 timeOffset:(CDStruct_900afa40)arg3 inViewWithWidth:(double)arg4;
+ (double)positionForMediaTime:(CDStruct_900afa40)arg1 outOfMediaDuration:(CDStruct_900afa40)arg2 timeOffset:(CDStruct_900afa40)arg3 inViewWithWidth:(double)arg4;
@property(nonatomic) id <MGMediaTimelineViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unbind:(id)arg1;
- (void)bind:(id)arg1 toObject:(id)arg2 withKeyPath:(id)arg3 options:(id)arg4;
- (void)rescalePointsPerSecond;
@property(readonly, nonatomic) BOOL canChangePointsPerSecond;
@property(readonly, nonatomic) double maximumPointsPerSecond;
@property(readonly, nonatomic) double minimumPointsPerSecond;
@property double pointsPerSecond;
@property(nonatomic) BOOL showsAdditionalMediaTrack;
@property(nonatomic) BOOL showsRangeMarkers;
@property(copy, nonatomic) NSSet *rangeMarkers;
@property(nonatomic) CDStruct_900afa40 currentMediaTime;
@property(nonatomic) BOOL usesSelectionDetents;
@property(copy, nonatomic) NSArray *selectionDetents;
@property(nonatomic) CDStruct_900afa40 maximumSelectionDuration;
@property(nonatomic) CDStruct_900afa40 minimumSelectionDuration;
@property(nonatomic) CDStruct_900afa40 selectionEnd;
@property(nonatomic) CDStruct_900afa40 selectionStart;
@property(nonatomic) CDStruct_900afa40 mediaTimeOffset;
@property(nonatomic) CDStruct_900afa40 mediaDuration;
@property(nonatomic) BOOL showsTrackPreviews;
- (void)removeObjectFromTimelineTracksAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inTimelineTracksAtIndex:(unsigned long long)arg2;
- (id)timelineTracks;
- (unsigned long long)countForTimelineTracks;
- (void)superviewFrameDidChange:(id)arg1;
- (void)viewDidMoveToSuperview;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

