//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaComposition, MGMediaTrack, NSArray, NSMutableArray;

@interface MGMediaCompositionSelectionController : NSObject
{
    MGMediaComposition *_mediaComposition;
    NSMutableArray *_mediaClipSelection;
    MGMediaTrack *_mediaTrackSelection;
}

@property(readonly, nonatomic) MGMediaTrack *mediaTrackSelection; // @synthesize mediaTrackSelection=_mediaTrackSelection;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unbind:(id)arg1;
- (id)audioMediaClips;
- (id)videoMediaClips;
- (id)audioMediaTrack;
- (id)videoMediaTrack;
- (void)deselectAllMediaClips;
- (void)selectAllMediaClipsInMediaTrack:(id)arg1;
- (void)selectMediaClip:(id)arg1 optionKeyDown:(BOOL)arg2 shiftKeyDown:(BOOL)arg3;
- (BOOL)isMediaClipSelected:(id)arg1;
- (unsigned long long)numberOfSelectedMediaClips;
@property(readonly, nonatomic) NSArray *mediaClipSelection;
@property(retain, nonatomic) MGMediaComposition *mediaComposition;
- (void)dealloc;
- (id)init;

@end

