//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, AVVideoComposition, MGMediaClip;

@interface MGMediaTimelineTrackPreviewMediaClipContainer : NSObject
{
    MGMediaClip *_mediaClip;
    AVAsset *_asset;
    AVVideoComposition *_videoComposition;
    struct CGSize _mediaCompositionNaturalSize;
}

@property(nonatomic) struct CGSize mediaCompositionNaturalSize; // @synthesize mediaCompositionNaturalSize=_mediaCompositionNaturalSize;
@property(retain, nonatomic) AVVideoComposition *videoComposition; // @synthesize videoComposition=_videoComposition;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(retain, nonatomic) MGMediaClip *mediaClip; // @synthesize mediaClip=_mediaClip;
- (void)dealloc;

@end

