//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "MGAccessibilityFauxUIElementParent.h"

@class MGMediaCompositionViewController, NSMutableArray;

@interface MGMediaCompositionView : NSView <MGAccessibilityFauxUIElementParent>
{
    MGMediaCompositionViewController *_viewController;
    NSMutableArray *_mediaTrackViews;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeMediaTrackViews:(id)arg1;
- (void)addMediaTrackViews:(id)arg1;
- (id)tracksContainerView;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) MGMediaCompositionViewController *viewController;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutMediaTrackViews;
- (void)accessibilityAttributeValueDidChangeForKeyPath:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (void)fauxUIElement:(id)arg1 setValue:(id)arg2 forAdditionalAttribute:(id)arg3;
- (BOOL)fauxUIElement:(id)arg1 isAdditionalAttributeSettable:(id)arg2;
- (id)fauxUIElement:(id)arg1 additionalAttributeValue:(id)arg2;
- (id)fauxUIElementAdditionalAccessiblityAttributeNames:(id)arg1;
- (void)fauxUIElement:(id)arg1 performAction:(id)arg2;
- (id)fauxUIElement:(id)arg1 descriptionForAction:(id)arg2;
- (id)fauxUIElementActionNames:(id)arg1;
- (BOOL)fauxUIElementIsEnabled:(id)arg1;
- (BOOL)fauxUIElementIsFocused:(id)arg1;
- (void)fauxUIElement:(id)arg1 setFocus:(id)arg2;
- (BOOL)isFauxUIElementFocusable:(id)arg1;
- (struct CGSize)fauxUIElementSize:(id)arg1;
- (struct CGPoint)fauxUIElementPosition:(id)arg1;
- (id)fauxUIElementChildren:(id)arg1;
- (BOOL)fauxUIElementHasChildren:(id)arg1;
- (id)fauxUIElementDescription:(id)arg1;
- (id)fauxUIElementRole:(id)arg1;
- (void)stepBackwardCurrentTime;
- (void)stepForwardCurrentTime;
- (id)mediaTrackViewItemForMediaClip:(id)arg1 inMediaTrackView:(id)arg2;

@end

