//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGMediaClipPreview.h"

@class CALayer, CATiledLayer, MGAudioAmplitudeExtractionSession, MGDataPool;

@interface MGMediaClipAudioPreview : MGMediaClipPreview
{
    MGAudioAmplitudeExtractionSession *_audioAmplitudeExtractionSession;
    CATiledLayer *_waveformLayer;
    CALayer *_centerLineLayer;
    struct CGSize _lastPreviewLayerBoundsSize;
    MGDataPool *_rectListPool;
    struct CGRect _pendingDirtyRect;
}

- (void)audioAmplitudeSamplesDidBecomeAvailable:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)previewLayer;
- (void)setInLiveResize:(BOOL)arg1;
@property(retain, nonatomic) MGAudioAmplitudeExtractionSession *audioAmplitudeExtractionSession;
- (void)dealloc;
- (id)initWithMediaClip:(id)arg1;

@end

