//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSPasteboardReading.h"
#import "NSPasteboardWriting.h"

@class NSString, NSURL;

@interface MGMediaClip : NSObject <NSPasteboardReading, NSPasteboardWriting, NSCoding, NSCopying>
{
    NSURL *_URL;
    unsigned long long _mediaType;
    struct CGSize _naturalSize;
    CDStruct_1b6d18a9 _naturalDuration;
    struct CGAffineTransform _naturalTransform;
    CDStruct_e83c9415 _timeRange;
    unsigned long long _alignment;
    unsigned long long _rotation;
    unsigned long long _flipping;
    BOOL _naturalDurationPrecise;
    NSString *_fileWrapperFilename;
}

+ (id)keyPathsForValuesAffectingHasOriginalTransform;
+ (id)keyPathsForValuesAffectingOutPoint;
+ (id)keyPathsForValuesAffectingInPoint;
+ (id)keyPathsForValuesAffectingDuration;
+ (unsigned long long)readingOptionsForType:(id)arg1 pasteboard:(id)arg2;
+ (id)readableTypesForPasteboard:(id)arg1;
+ (unsigned long long)mediaClipMediaTypeForAsset:(id)arg1;
+ (id)assetKeysForValuesNeededToCreateMediaClip;
@property(nonatomic) unsigned long long flipping; // @synthesize flipping=_flipping;
@property(nonatomic) unsigned long long rotation; // @synthesize rotation=_rotation;
@property(nonatomic) unsigned long long alignment; // @synthesize alignment=_alignment;
@property(readonly, nonatomic) struct CGAffineTransform naturalTransform; // @synthesize naturalTransform=_naturalTransform;
@property(readonly, nonatomic, getter=isNaturalDurationPrecise) BOOL naturalDurationPrecise; // @synthesize naturalDurationPrecise=_naturalDurationPrecise;
@property(readonly, nonatomic) CDStruct_1b6d18a9 naturalDuration; // @synthesize naturalDuration=_naturalDuration;
@property(readonly, nonatomic) struct CGSize naturalSize; // @synthesize naturalSize=_naturalSize;
@property(readonly, nonatomic) unsigned long long mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (id)description;
@property(nonatomic) CDStruct_e83c9415 timeRange;
@property(readonly, nonatomic) NSString *localizedName;
- (id)mediaClipWithPreciseNaturalDuration:(CDStruct_1b6d18a9)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithURL:(id)arg1 mediaType:(unsigned long long)arg2 naturalSize:(struct CGSize)arg3 naturalDuration:(CDStruct_1b6d18a9)arg4 naturalDurationPrecise:(BOOL)arg5 naturalTransform:(struct CGAffineTransform)arg6;
@property(readonly, nonatomic) BOOL hasOriginalTransform;
@property(nonatomic) CDStruct_1b6d18a9 outPoint;
@property(nonatomic) CDStruct_1b6d18a9 inPoint;
@property(readonly, nonatomic) CDStruct_1b6d18a9 duration;
- (void)setURLByAppendingFileWrapperFilenameToDocumentBundleURL:(id)arg1;
- (void)setFileWrapperFilename:(id)arg1;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (struct CGAffineTransform)transformForTargetSize:(struct CGSize)arg1;
- (struct CGAffineTransform)transformForTargetSize:(struct CGSize)arg1 origin:(struct CGPoint)arg2;

@end

