//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGJobController.h"

@class MGMediaDownloadJob, NSError, NSURL;

@interface MGMediaDownloadJobController : MGJobController
{
    MGMediaDownloadJob *_job;
    NSURL *_outputURL;
    NSError *_error;
}

+ (id)keyPathsForValuesAffectingError;
+ (id)keyPathsForValuesAffectingStatusString;
+ (id)keyPathsForValuesAffectingResultURL;
@property(copy, nonatomic) NSURL *outputURL; // @synthesize outputURL=_outputURL;
- (BOOL)restoreFromDictionaryRepresentation:(id)arg1;
- (id)savedDictionaryRepresentation;
- (id)error;
- (id)statusString;
- (id)resultURL;
- (id)icon;
- (id)name;
- (id)activeJob;
- (id)identifier;
- (void)dealloc;
- (id)initWithSourceURL:(id)arg1 destinationURL:(id)arg2 hideExtension:(BOOL)arg3;

@end

