//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class MGMediaClip, MGMediaTrack;

@interface MGMediaComposition : NSObject <NSCoding, NSCopying>
{
    MGMediaTrack *_mainMediaTrack;
    MGMediaTrack *_additionalMediaTrack;
    struct CGSize _naturalSize;
}

+ (id)keyPathsForValuesAffectingPassthroughMediaClip;
+ (id)keyPathsForValuesAffectingPassthroughPossible;
@property(nonatomic) struct CGSize naturalSize; // @synthesize naturalSize=_naturalSize;
@property(readonly, nonatomic) MGMediaTrack *additionalMediaTrack; // @synthesize additionalMediaTrack=_additionalMediaTrack;
@property(readonly, nonatomic) MGMediaTrack *mainMediaTrack; // @synthesize mainMediaTrack=_mainMediaTrack;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)replacementObjectForPortCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithMainMediaTrackMediaType:(unsigned long long)arg1 naturalSize:(struct CGSize)arg2;
- (id)mediaTrackContainingMediaClip:(id)arg1;
- (void)trimToTimeRange:(CDStruct_e83c9415)arg1;
@property(readonly, nonatomic) MGMediaClip *passthroughMediaClip;
@property(readonly, nonatomic, getter=isPassthroughPossible) BOOL passthroughPossible;

@end

