//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaTimelineTrackPreview, MGMediaTimelineView;

@interface MGMediaTimelineTrack : NSObject
{
    id _identifier;
    MGMediaTimelineView *_timelineView;
    id _representedObject;
    MGMediaTimelineTrackPreview *_preview;
}

@property(retain, nonatomic) id representedObject; // @synthesize representedObject=_representedObject;
@property(nonatomic) MGMediaTimelineView *timelineView; // @synthesize timelineView=_timelineView;
@property(readonly, nonatomic) id identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) MGMediaTimelineTrackPreview *preview;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;
- (id)init;

@end

