//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "MGAccessibilityFauxUIElementParent.h"

@class CALayer, MGFocusRingLayer, NSArray, NSMutableArray, NSSet, NSTrackingArea;

@interface MGMediaTimelineTracksView : NSView <MGAccessibilityFauxUIElementParent>
{
    NSMutableArray *_timelineTracks;
    CDStruct_900afa40 _mediaDuration;
    CDStruct_900afa40 _mediaTimeOffset;
    CDStruct_900afa40 _selectionStart;
    CDStruct_900afa40 _selectionEnd;
    CDStruct_900afa40 _minimumSelectionDuration;
    CDStruct_900afa40 _maximumSelectionDuration;
    CDStruct_900afa40 _currentMediaTime;
    NSArray *_selectionDetents;
    struct __CFDictionary *_layersForRangeMarkers;
    CALayer *_selectionBorderLayer;
    CALayer *_selectionBorderUnderlayLayer;
    CALayer *_tracksLayer;
    CALayer *_trackPreviewsContainerLayer;
    CALayer *_trackPreviewsUnselectedRangeOverlayContainerLayer;
    CALayer *_trackPreviewsUnselectedStartRangeOverlayLayer;
    CALayer *_trackPreviewsUnselectedEndRangeOverlayLayer;
    CALayer *_leftSelectionHandleLayer;
    CALayer *_rightSelectionHandleLayer;
    CALayer *_playheadLayer;
    CALayer *_initialFocusedLayer;
    CALayer *_focusedLayer;
    MGFocusRingLayer *_focusRingLayer;
    NSTrackingArea *_selectionLeftEdgeTrackingArea;
    NSTrackingArea *_selectionRightEdgeTrackingArea;
    unsigned int _didCreateLayers:1;
    unsigned int _isTrackingSelection:1;
    unsigned int _showsTrackPreviews:1;
    unsigned int _showsRangeMarkers:1;
    unsigned int _usesSelectionDetents:1;
    unsigned int _showsAdditionalMediaTrack:1;
}

+ (CDStruct_900afa40)mediaTimeForPosition:(double)arg1 outOfMediaDuration:(CDStruct_900afa40)arg2 timeOffset:(CDStruct_900afa40)arg3 inViewWithWidth:(double)arg4;
+ (double)positionForMediaTime:(CDStruct_900afa40)arg1 outOfMediaDuration:(CDStruct_900afa40)arg2 timeOffset:(CDStruct_900afa40)arg3 inViewWithWidth:(double)arg4;
+ (long long)suggestedTimeScaleForMediaDuration:(CDStruct_900afa40)arg1 inViewWithWidth:(double)arg2;
+ (void)initialize;
@property(copy) NSArray *selectionDetents; // @synthesize selectionDetents=_selectionDetents;
@property(nonatomic) CDStruct_900afa40 maximumSelectionDuration; // @synthesize maximumSelectionDuration=_maximumSelectionDuration;
@property(nonatomic) CDStruct_900afa40 minimumSelectionDuration; // @synthesize minimumSelectionDuration=_minimumSelectionDuration;
- (void)setFocusedLayer:(id)arg1;
- (id)focusedLayer;
- (void)keyDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (BOOL)mouseDownCanMoveWindow;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)layoutSublayersOfLayer:(id)arg1;
- (CDStruct_900afa40)mediaTimeForPosition:(double)arg1;
- (double)positionForMediaTime:(CDStruct_900afa40)arg1;
@property(nonatomic) BOOL showsAdditionalMediaTrack;
@property(nonatomic) BOOL showsRangeMarkers;
@property(copy, nonatomic) NSSet *rangeMarkers;
- (void)stepBackwardCurrentMediaTime;
- (void)stepForwardCurrentMediaTime;
@property(nonatomic) CDStruct_900afa40 currentMediaTime;
@property(nonatomic) BOOL usesSelectionDetents;
- (void)stepBackwardSelectionEnd;
- (void)stepForwardSelectionEnd;
- (CDStruct_900afa40)maxSelectionEnd;
- (CDStruct_900afa40)minSelectionEnd;
@property(nonatomic) CDStruct_900afa40 selectionEnd;
- (void)stepBackwardSelectionStart;
- (void)stepForwardSelectionStart;
- (CDStruct_900afa40)maxSelectionStart;
- (CDStruct_900afa40)minSelectionStart;
@property(nonatomic) CDStruct_900afa40 selectionStart;
@property(nonatomic) CDStruct_900afa40 mediaTimeOffset;
@property(nonatomic) CDStruct_900afa40 mediaDuration;
@property(nonatomic) BOOL showsTrackPreviews;
- (void)viewDidEndLiveResize;
- (void)removeObjectFromTimelineTracksAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inTimelineTracksAtIndex:(unsigned long long)arg2;
- (id)timelineTracks;
- (unsigned long long)countForTimelineTracks;
- (id)delegate;
- (void)viewDidMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)fauxUIElement:(id)arg1 additionalAttributeValue:(id)arg2;
- (id)fauxUIElementAdditionalAccessiblityAttributeNames:(id)arg1;
- (void)fauxUIElement:(id)arg1 performAction:(id)arg2;
- (id)fauxUIElement:(id)arg1 descriptionForAction:(id)arg2;
- (id)fauxUIElementActionNames:(id)arg1;
- (BOOL)fauxUIElementIsEnabled:(id)arg1;
- (BOOL)fauxUIElementIsFocused:(id)arg1;
- (void)fauxUIElement:(id)arg1 setFocus:(id)arg2;
- (BOOL)isFauxUIElementFocusable:(id)arg1;
- (struct CGSize)fauxUIElementSize:(id)arg1;
- (struct CGPoint)fauxUIElementPosition:(id)arg1;
- (id)fauxUIElementChildren:(id)arg1;
- (BOOL)fauxUIElementHasChildren:(id)arg1;
- (id)fauxUIElementDescription:(id)arg1;
- (id)fauxUIElementRole:(id)arg1;
- (id)accessibilityFocusedUIElement;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;

@end

