//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSTimer;

@interface MGMediaCompositionEditControllerInternal : NSObject
{
    NSTimer *makeKeyAndOrderFrontTimer;
    BOOL isValidDraggingOperation;
    BOOL optionKeyWasDown;
    BOOL endDraggingDestinationSessionInDraggingEndedMethod;
    struct CGPoint draggingDestinationSessionMouseLocation;
    NSArray *draggingAssetLoaders;
    id <NSDraggingInfo> draggingInfoThatInitiatedAssetLoading;
    NSArray *draggingMediaClips;
    id <MGMediaClipAssetProvider> draggingPreloadedAssetProvider;
    NSArray *draggingPreloadingErrors;
    BOOL wasMouseInsideMainMediaTrackView;
    BOOL wasMouseInsideAdditionalMediaTrackView;
}

@end

