//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGMediaClipPreview.h"

@class AVAssetImageGenerator, CALayer, MGMediaComposition;

@interface MGMediaClipVideoPreview : MGMediaClipPreview
{
    MGMediaComposition *_mediaComposition;
    AVAssetImageGenerator *_imageGenerator;
    CALayer *_containerLayer;
    struct CGSize _mediaCompositionNaturalSize;
    struct CGSize _lastPreviewLayerBoundsSize;
    BOOL _forceImageGeneration;
    id _asset;
}

@property(retain, nonatomic) id asset; // @synthesize asset=_asset;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)previewLayer;
- (void)setInLiveResize:(BOOL)arg1;
@property(retain, nonatomic) AVAssetImageGenerator *imageGenerator;
- (void)dealloc;
- (id)initWithMediaClip:(id)arg1;
- (id)initWithMediaClip:(id)arg1 mediaComposition:(id)arg2;

@end

