//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol MGMediaTimelineTrackVideoPreviewThumbnailProvider <NSObject>
- (void)cancelAllTHumbnailRequests;
- (void)provideThumbnailWithSize:(struct CGSize)arg1 forMediaTime:(CDStruct_900afa40)arg2 returningToBlock:(void (^)(NSImage *))arg3;
@end

