//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaComposition, NSUndoManager;

@interface MGMediaCompositionUndoController : NSObject
{
    MGMediaComposition *_mediaComposition;
    NSUndoManager *_undoManager;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unbind:(id)arg1;
- (void)removeMediaClipObserver:(id)arg1;
- (void)addMediaClipObserver:(id)arg1;
@property(retain, nonatomic) MGMediaComposition *mediaComposition;
- (void)dealloc;
- (id)initWithUndoManager:(id)arg1;

@end

