//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGJob.h"

#import "NSURLDownloadDelegate.h"

@class NSError, NSOperation, NSURL;

@interface MGMediaDownloadJob : MGJob <NSURLDownloadDelegate>
{
    NSOperation *_resolveRefMovieURLOperation;
    NSOperation *_downloadOperation;
    NSURL *_resolvedSourceURL;
    NSURL *_destinationURL;
    struct __CFRunLoop *_downloadCFRunLoop;
    long long _expectedContentLength;
    long long _receivedDataLength;
    NSError *_error;
    BOOL _downloadIsFinished;
    BOOL _hideExtension;
}

- (id)error;
- (void)cancel;
- (id)resultURL;
- (id)runningStatusString;
- (float)progress;
- (id)operations;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (BOOL)download:(id)arg1 shouldDecodeSourceDataOfMIMEType:(id)arg2;
- (void)download:(id)arg1 didReceiveDataOfLength:(unsigned long long)arg2;
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;
- (void)download:(id)arg1 decideDestinationWithSuggestedFilename:(id)arg2;
- (void)dealloc;
- (id)initWithSourceURL:(id)arg1 destinationURL:(id)arg2 hideExtension:(BOOL)arg3;

@end

