//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaClip;

@interface MGMediaClipPreview : NSObject
{
    MGMediaClip *_mediaClip;
    BOOL _isInLiveResize;
}

@property(nonatomic, getter=isInLiveResize) BOOL inLiveResize; // @synthesize inLiveResize=_isInLiveResize;
@property(readonly, nonatomic) MGMediaClip *mediaClip; // @synthesize mediaClip=_mediaClip;
- (id)previewLayer;
- (void)dealloc;
- (id)init;
- (id)initWithMediaClip:(id)arg1;

@end

