//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGMediaTimelineTrackPreview.h"

@class CALayer, CATiledLayer, MGDataPool;

@interface MGMediaTimelineTrackAudioPreview : MGMediaTimelineTrackPreview
{
    CATiledLayer *_previewLayer;
    CALayer *_centerLineLayer;
    MGDataPool *_rectListPool;
    CDStruct_900afa40 _mediaDuration;
    CDStruct_900afa40 _mediaTimeOffset;
    struct CGSize _lastPreviewLayerSize;
    struct CGRect _pendingDirtyRect;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)amplitudeSamplesDidBecomeAvailable:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)previewLayer;
- (void)setTimelineTrack:(id)arg1;
- (void)dealloc;

@end

