//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, QTMovie;

@interface MGMovieErrorReporter : NSObject
{
    QTMovie *_movie;
    NSArray *_missingComponents;
    BOOL _hasCheckedMissingComponents;
}

+ (id)presentableErrorForError:(id)arg1 loadingMovieAtURL:(id)arg2;
+ (id)presentableMissingSoftwareErrorForMissingComponents:(id)arg1 loadingMovieAtURL:(id)arg2;
- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;
- (id)error;
- (void)dealloc;
- (id)initWithMovie:(id)arg1;

@end

