//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QTMovie;

@interface MGMovieCompatibilityConformer : NSObject
{
    QTMovie *_movie;
    int _compatibilityLevel;
}

@property(readonly) int compatibilityLevel; // @synthesize compatibilityLevel=_compatibilityLevel;
@property(readonly) QTMovie *movie; // @synthesize movie=_movie;
- (void)dealloc;
- (id)initAndConformMovie:(id)arg1;
- (id)init;

@end

