//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocument.h"

#import "MGInspectionAttributeContainer.h"

@class MGDocumentViewController<MGVisualContentContainer>, MGMovieChapterController, MGMovieCompatibilityConformer, MGMovieErrorReporter, MGMovieInspectionAttributes, MGMovieLanguageController, NSArray, NSTimer, QTMovie;

@interface MGMovieDocument : MGDocument <MGInspectionAttributeContainer>
{
    QTMovie *_movie;
    MGMovieCompatibilityConformer *_movieCompatibilityConformer;
    MGMovieErrorReporter *_movieErrorReporter;
    MGDocumentViewController<MGVisualContentContainer> *_mainViewController;
    MGMovieChapterController *_chapterController;
    struct __CFRunLoopSource *_loadingRunLoopSource;
    MGMovieInspectionAttributes *_movieInspectionAttributes;
    MGMovieLanguageController *_audioLanguageController;
    MGMovieLanguageController *_subtitleLanguageController;
    MGMovieLanguageController *_chapterLanguageController;
    NSTimer *_profileFPSTimer;
    double _profileAvgFrameRate;
    double _profileFPSCount;
    unsigned int _movieIsLoaded:1;
    unsigned int _isClosing:1;
    unsigned int _isTearingDownMovie:1;
    unsigned int _isObservingLoadState:1;
    unsigned int _areClosedCaptionVisible:1;
    unsigned int _DRMCheckDone:1;
    unsigned int _needToRunMovieOpenProfileTests:1;
    unsigned int _isForcingAudioOnlyUI:1;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingInspectionInformation;
+ (id)keyPathsForValuesAffectingInpsectionAttributes;
@property(readonly, nonatomic) QTMovie *movie; // @synthesize movie=_movie;
- (void)playerPlaybackTest:(id)arg1;
- (void)profileSampleCurrentFPS:(id)arg1;
- (void)profileFPS;
- (void)runAllMovieOpenProfileTestsIfNeeeded;
- (void)showWindows;
- (void)mainMenuNeedsUpdate:(id)arg1;
- (void)updateSubtitlesMenu:(id)arg1;
- (void)updateAudioLanguageMenu:(id)arg1;
- (void)takeSubtitleLanguageFromRepresentedObjectOf:(id)arg1;
- (void)disableSubtitles:(id)arg1;
- (void)takeLanguageFromRepresentedObjectOf:(id)arg1;
- (void)setTextLanguageToSystemLanguageIfAvailable;
- (void)takeChapterLanguageFromRepresentedObjectOf:(id)arg1;
- (id)audioLanguageController;
- (id)subtitleLanguageController;
- (id)chapterLanguageController;
- (void)displayDRMAuthorizationAlertWithDescription:(id)arg1 message:(id)arg2 buttonTitle:(id)arg3 waitForAuthorization:(BOOL)arg4;
- (void)checkForDRM;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)movieEdited:(id)arg1;
- (void)movieRateChanged:(id)arg1;
- (void)toggleForcedAudioOnly:(id)arg1;
- (void)toggleClosedCaption:(id)arg1;
- (void)loop:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)canShare;
@property(readonly, nonatomic) MGMovieChapterController *chapterController;
- (void)updateMainViewControllerForMovieWithoutKVONotification;
- (id)mainViewController;
- (void)movieStatusStringPosted:(id)arg1;
- (id)movieLoadError;
- (id)displayName;
- (void)movieLoadStateDidChange:(id)arg1;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)dealloc;
- (void)close;
- (void)tearDownMovie;
- (id)init;
@property(readonly, nonatomic) NSArray *inspectionInformation;
@property(readonly, nonatomic) NSArray *inspectionAttributes;
- (id)movieInspectionAttributes;
- (void)updateMovieInspectionAttributesCurrentSize;
- (id)handleShowRemoteHUDCommand:(id)arg1;
- (id)currentScreenCompression;
- (id)currentMovieCompression;
- (id)currentAudioCompression;
- (id)currentVideoRecordingDevice;
- (id)currentAudioRecordingDevice;
- (id)handleExportCommand:(id)arg1;
- (void)setVolume:(float)arg1;
- (float)volume;
- (void)setRate:(float)arg1;
- (float)rate;
- (BOOL)playing;
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (void)setLoops:(BOOL)arg1;
- (BOOL)loops;
- (id)naturalDimensions;
- (id)dataSize;
- (id)dataRate;
- (id)durationInSeconds;
- (void)setCurrentTimeInSeconds:(id)arg1;
- (id)currentTimeInSeconds;
- (id)handleTrimCommand:(id)arg1;
- (id)handleStepForwardCommand:(id)arg1;
- (id)handleStepBackwardCommand:(id)arg1;
- (void)handleStopCommand:(id)arg1;
- (void)handlePauseCommand:(id)arg1;
- (void)handlePlayCommand:(id)arg1;

@end

