//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QTMovie;

@interface MGMovieStatusStringController : NSObject
{
    QTMovie *_movie;
    NSString *_statusString;
}

@property(copy, nonatomic) NSString *statusString; // @synthesize statusString=_statusString;
- (void)movieEdited:(id)arg1;
- (void)movieRateDidChange:(id)arg1;
- (void)movieDidPostStatusString:(id)arg1;
- (void)movieDidPostMessageString:(id)arg1;
- (void)resetStatusString;
@property(retain) QTMovie *movie;
- (void)dealloc;

@end

