//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MGInspectionAttributeContainer.h"

@class NSArray, NSTimer, QTMovie;

@interface MGMovieInspectionAttributes : NSObject <MGInspectionAttributeContainer>
{
    QTMovie *_movie;
    NSArray *_attributes;
    NSArray *_annotationStrings;
    struct CGSize _currentSize;
    NSTimer *_attributeTimer;
}

+ (void)initialize;
- (id)mediaStackString;
- (id)playingFPSString;
- (void)updateAnnotationStrings;
- (id)normalSizeString;
- (id)currentSizeString;
- (id)fpsString;
- (id)formatString;
- (id)qualityString;
- (id)dataSizeString;
- (id)bitRateString;
- (id)dataRateString;
- (id)chapterFormatString;
- (id)sourceString;
- (double)dynamicFrameRate;
- (float)staticFrameRate;
- (id)annotations;
- (long long)loadState;
- (unsigned long long)dataRate;
- (unsigned long long)dataSize;
- (BOOL)isStreaming;
- (BOOL)isPlaying;
- (BOOL)usesVisualContext;
- (BOOL)hasVideo;
- (BOOL)hasDuration;
- (BOOL)hasFrameRate;
- (BOOL)hasChapters;
- (id)stringForMovieDisplaySize:(struct CGSize)arg1;
- (BOOL)isTrackOfInterest:(id)arg1;
@property(nonatomic) struct CGSize currentSize;
- (void)updateDynamicAttributes;
- (void)updateStaticAttributes;
@property(readonly, nonatomic) NSArray *inspectionInformation;
@property(readonly, nonatomic) NSArray *inspectionAttributes;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)movieEdited:(id)arg1;
- (void)updateDynamicAttributesTimer:(id)arg1;
- (void)movieRateChanged:(id)arg1;
- (void)dealloc;
- (id)initWithMovie:(id)arg1;

@end

