//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTMoviePlaybackController.h"

@interface MGMoviePlaybackController : QTMoviePlaybackController
{
    unsigned long long _flags;
    double _jogRate;
    double _rateBeforeJogging;
}

+ (id)moviePlaybackControllerWithMovie:(id)arg1;
- (BOOL)handleScrollWheel:(id)arg1;
- (BOOL)handleBeginGestureWithEvent:(id)arg1;
- (BOOL)wouldHandleBeginGestureWithEvent:(id)arg1;
- (BOOL)handleSwipeWithEvent:(id)arg1;
- (BOOL)handleKeyDown:(id)arg1 eventResponse:(unsigned long long *)arg2;
- (void)gotoEndOfPlaybackRange:(id)arg1;
- (void)gotoBeginningOfPlaybackRange:(id)arg1;
- (void)joggingDidStop;
@property double jogRate;
@property(readonly, getter=isJogging) BOOL jogging;

@end

