//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGChapter.h"

@class MGMovieThumbnailExtractionSession, NSDictionary;

@interface MGMovieChapter : MGChapter
{
    NSDictionary *_chapterDescription;
    MGMovieThumbnailExtractionSession *_thumbnailExtractionSession;
}

- (void)extractMetadataImageAsynchronouslyReturningToBlock:(CDUnknownBlockType)arg1;
- (void)extractImageAsynchronouslyForTime:(CDStruct_1b6d18a9)arg1 returningToBlock:(CDUnknownBlockType)arg2;
- (id)name;
- (CDStruct_1b6d18a9)startTime;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithChapterDescription:(id)arg1 thumbnailExtractionSession:(id)arg2;

@end

