//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGMediaComposition, NSDictionary;

@protocol MGMovieExportSessionHelper <NSObject>
- (void)cancel;
- (id)initWithMediaComposition:(MGMediaComposition *)arg1 exportParameters:(NSDictionary *)arg2 sessionDelegate:(id)arg3;
@end

