//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSInputStream.h"

@class NSMutableArray, NSString;

@interface MGMultipartInputStream : NSInputStream
{
    NSInputStream *mCurrentStream;
    unsigned int mStreamIndex;
    NSString *mTemporaryFile;
    NSString *mBoundary;
    NSMutableArray *mParts;
    NSMutableArray *mPartStreams;
    unsigned long long mLength;
    NSString *vendorID;
}

@property(copy, nonatomic) NSString *vendorID; // @synthesize vendorID;
- (id)inputStreamWithTemporaryFile;
- (id)tempFileWithName:(id)arg1;
- (void)dd_readIntoFile:(id)arg1;
- (BOOL)getBuffer:(char **)arg1 length:(unsigned long long *)arg2;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (BOOL)hasBytesAvailable;
- (void)close;
- (void)open;
- (id)partStreams;
- (unsigned long long)length;
- (void)buildBody;
- (void)addPartWithName:(id)arg1 fileAtPath:(id)arg2;
- (void)addPartWithName:(id)arg1 intValue:(int)arg2;
- (void)addPartWithName:(id)arg1 string:(id)arg2;
- (void)addPartWithName:(id)arg1 data:(id)arg2;
- (id)boundary;
- (void)dealloc;
- (id)init;
- (id)initWithVendorID:(id)arg1;

@end

