//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@class NSArray, NSNib, NSView;

@interface MGNibViewMenuItem : NSMenuItem
{
    NSNib *_nib;
    NSArray *_topLevelObjects;
}

- (void)menuDidEndTracking:(id)arg1;
- (void)menuDidBeginTracking:(id)arg1;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 action:(SEL)arg2 keyEquivalent:(id)arg3;
- (id)initWithNib:(id)arg1 title:(id)arg2 action:(SEL)arg3 keyEquivalent:(id)arg4;

// Remaining properties
@property(retain, nonatomic) NSView *view; // @dynamic view;

@end

