//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class IKImageBrowserView, NSArray, NSIndexSet, NSOperationQueue;

@interface MGOpenClipWindowController : NSWindowController
{
    NSOperationQueue *_assetInformationQueue;
    NSArray *_assetInformation;
    NSIndexSet *_selectionIndexes;
    IKImageBrowserView *_imageBrowserView;
    unsigned long long _assetCount;
}

@property(readonly) unsigned long long assetCount; // @synthesize assetCount=_assetCount;
@property(retain) IKImageBrowserView *imageBrowserView; // @synthesize imageBrowserView=_imageBrowserView;
@property(retain) NSIndexSet *selectionIndexes; // @synthesize selectionIndexes=_selectionIndexes;
@property(retain) NSArray *assetInformation; // @synthesize assetInformation=_assetInformation;
- (void)imageBrowser:(id)arg1 cellWasDoubleClickedAtIndex:(unsigned long long)arg2;
- (void)close;
- (void)cancel:(id)arg1;
- (void)open:(id)arg1;
@property(readonly) NSArray *selectedAssetInformation;
- (id)windowNibName;
- (void)dealloc;
- (id)initWithAssetCollection:(id)arg1;

@end

