//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "MGAccessibilityFauxUIElementParent.h"

@class NSMutableDictionary;

@interface MGPageControl : NSView <MGAccessibilityFauxUIElementParent>
{
    unsigned long long _currentPage;
    unsigned long long _numberOfPages;
    NSMutableDictionary *_binders;
}

+ (void)initialize;
@property(nonatomic) unsigned long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) unsigned long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
- (void)keyDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (unsigned long long)pageAtPoint:(struct CGPoint)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (BOOL)needsPanelToBecomeKey;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)unbind:(id)arg1;
- (void)bind:(id)arg1 toObject:(id)arg2 withKeyPath:(id)arg3 options:(id)arg4;
- (id)infoForBinding:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)rectForPage:(unsigned long long)arg1;
- (struct CGPoint)drawingOrigin;
- (struct CGSize)sizeForNumberOfPages:(long long)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)fauxUIElement:(id)arg1 additionalAttributeValue:(id)arg2;
- (id)fauxUIElementAdditionalAccessiblityAttributeNames:(id)arg1;
- (void)fauxUIElement:(id)arg1 performAction:(id)arg2;
- (id)fauxUIElement:(id)arg1 descriptionForAction:(id)arg2;
- (id)fauxUIElementActionNames:(id)arg1;
- (BOOL)fauxUIElementIsEnabled:(id)arg1;
- (BOOL)fauxUIElementIsFocused:(id)arg1;
- (void)fauxUIElement:(id)arg1 setFocus:(id)arg2;
- (BOOL)isFauxUIElementFocusable:(id)arg1;
- (struct CGSize)fauxUIElementSize:(id)arg1;
- (struct CGPoint)fauxUIElementPosition:(id)arg1;
- (struct CGRect)fauxUIElementRect:(id)arg1;
- (id)fauxUIElementChildren:(id)arg1;
- (BOOL)fauxUIElementHasChildren:(id)arg1;
- (id)fauxUIElementDescription:(id)arg1;
- (id)fauxUIElementRole:(id)arg1;
- (unsigned long long)accessibilityIndexOfChild:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;

@end

