//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MGPlayerController, NSButton, NSResponder, NSSlider;

@interface MGPlayPauseShuttleControllerView : NSView
{
    MGPlayerController *_playerController;
    NSView *_containerView;
    NSButton *_playPauseButton;
    NSSlider *_shuttleSlider;
    NSResponder *_firstResponder;
}

@property(retain, nonatomic) NSSlider *shuttleSlider; // @synthesize shuttleSlider=_shuttleSlider;
@property(retain, nonatomic) NSButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)mouseDownCanMoveWindow;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)hitTest:(struct CGPoint)arg1;
@property(retain, nonatomic) MGPlayerController *playerController;
- (void)dealloc;

@end

