//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

@class MGPlayerController, QTHUDTimeFormatter;

@interface MGPlayerDocumentRemoteHUDViewController : MGDocumentViewController
{
    MGPlayerController *_playerController;
    QTHUDTimeFormatter *_timeFormatter;
}

+ (double)defaultAutohideTimeout;
+ (unsigned long long)defaultViewAutoresizingMask;
+ (struct CGRect)defaultViewFrameForSuperviewBounds:(struct CGRect)arg1;
- (void)dealloc;
- (void)close;
- (void)loadView;

@end

