//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGTrimViewController.h"

@class AVPlayer, CALayer, MGAudioAnalyzer, MGMediaTimelineTrack, MGPlayerController;

@interface MGPlayerDocumentTrimViewController : MGTrimViewController
{
    MGMediaTimelineTrack *_videoTimelineTrack;
    MGMediaTimelineTrack *_audioTimelineTrack;
    AVPlayer *_player;
    MGPlayerController *_playerController;
    CALayer *_playerLayer;
    MGAudioAnalyzer *_audioAnalyzer;
    CDStruct_e83c9415 _savedPlaybackRange;
    CDStruct_1b6d18a9 _commitEditingCurrentTime;
    unsigned int _isShowingAlternateMediaTrackPreview:1;
    unsigned int _updatePlayerItemPlaybackRange:1;
    unsigned int _disablePlayerItemPlaybackRangeSync:1;
    unsigned int _disablePlayerItemCurrentTimeSync:1;
}

+ (void)initialize;
- (CDStruct_1b6d18a9)commitEditingCurrentTime;
@property(readonly, nonatomic) CALayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(readonly, nonatomic) MGPlayerController *playerController; // @synthesize playerController=_playerController;
@property(readonly, nonatomic) AVPlayer *player; // @synthesize player=_player;
- (void)invalidateRestorableState;
- (void)restoreStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)toggleAudioTrackShown:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)canPerformSelector:(SEL)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)commitEditing;
- (CDStruct_e83c9415)selectionRangeExcludingSilence;
- (void)viewWillHide;
- (void)viewWillShow;
- (void)close;
- (void)loadView;
- (CDStruct_1b6d18a9)mediaClipOffsetInMediaTrack:(id)arg1;
- (void)updatePlayerItemPlaybackRange:(CDStruct_e83c9415)arg1;
- (id)mediaClipContainerWithMediaClip:(id)arg1 asset:(id)arg2 videoComposition:(id)arg3 mediaComposition:(id)arg4;
- (CDStruct_900afa40)minimumSelectionDurationForAsset:(id)arg1;
- (BOOL)isMediaClipOnAdditionalMediaTrack:(id)arg1;

@end

