//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayerItem, MGPlayerDocument, NSAlert;

@interface MGPlayerDocumentDRMHandler : NSObject
{
    MGPlayerDocument *_playerDocument;
    AVPlayerItem *_playerItem;
    NSAlert *_authorizationInProgressAlert;
    CDUnknownBlockType _completionHandler;
    unsigned int _needsToShowDRMAlerts:1;
    unsigned int _needsToWaitForAuthorization:1;
}

- (void)DRMAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)waitForAuthorization;
- (void)confirmAuthorization;
- (void)authorizationFailedWithStatus:(long long)arg1;
- (void)displayDRMAuthorizationAlertWithDescription:(id)arg1 message:(id)arg2 buttonTitle:(id)arg3 waitForAuthorization:(BOOL)arg4;
- (BOOL)needsToShowDRMAlerts;
- (void)validateDRMWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)completionHandler;
- (void)dealloc;
- (void)invalidate;
- (id)initWithDocument:(id)arg1 playerItem:(id)arg2;

@end

