//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGVideoView.h"

@class AVPlayer, AVPlayerLayer;

@interface MGPlayerView : MGVideoView
{
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
}

@property(readonly, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) AVPlayer *player;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

