//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGKeyValueProxy.h"

@interface MGPlayerControllerPlayerProxy : MGKeyValueProxy
{
    long long _retainCount;
    float _nominalRate;
    float _nominalRateBeforeJogging;
    long long _nominalActionAtItemEnd;
    long long _preventAdvancingToNextItemCount;
    long long _scrubCount;
    long long _jogCount;
    long long _preventIdleSleepCount;
    long long _pauseWhenInactiveCount;
    unsigned int _playing:1;
    unsigned int _shouldPlayWhenLikelyToKeepUp:1;
    unsigned int _playingBeforeJogging:1;
    unsigned int _scrubbing:1;
    unsigned int _loops:1;
    unsigned int _disabledIdleSystemSleep:1;
    unsigned int _disabledIdleDisplaySleep:1;
}

+ (BOOL)automaticallyNotifiesObserversOfActionAtItemEnd;
+ (BOOL)shouldProxyValueForActionAtItemEnd;
+ (BOOL)shouldProxyValueForLoops;
+ (BOOL)shouldProxyValueForPlaying;
+ (BOOL)automaticallyNotifiesObserversOfRate;
+ (BOOL)shouldProxyValueForRate;
+ (id)proxyForPlayer:(id)arg1;
+ (void)initialize;
- (void)itemDidPlayToEndTime:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)disablePauseWhenSessionResignsActive;
- (void)enablePauseWhenSessionResignsActive;
- (void)_sessionDidResignActive:(id)arg1;
- (void)allowIdleSleepWhilePlaying;
- (void)preventIdleSleepWhilePlaying;
- (void)endJogging;
- (void)beginJogging;
- (void)endScrubbing;
- (void)beginScrubbing;
- (void)allowAdvancingToNextItem;
- (void)preventAdvancingToNextItem;
- (void)setActionAtItemEnd:(long long)arg1;
- (long long)actionAtItemEnd;
- (void)updateNominalActionAtItemEnd:(long long)arg1;
- (void)setLoops:(BOOL)arg1;
- (BOOL)loops;
- (void)autoplay;
- (void)setPlaying:(BOOL)arg1;
- (BOOL)isPlaying;
- (void)setRate:(float)arg1;
- (float)rate;
- (void)updateNominalRate:(float)arg1;
- (void)updateIdleAndDisplaySleep;
- (void)dealloc;
- (unsigned long long)retainCount;
- (oneway void)release;
- (id)retain;
- (id)initWithTarget:(id)arg1 queue:(id)arg2;

@end

