//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGKeyValueProxy.h"

@class MGPlayerControllerPlayerProxy;

@interface MGPlayerControllerSelectionPlayerItem : MGKeyValueProxy
{
    MGPlayerControllerPlayerProxy *_playerProxy;
    CDStruct_1b6d18a9 _nonProxiedCurrentTime;
    CDStruct_1b6d18a9 _seekToTimeResolution;
    unsigned int _scrubbing:1;
    unsigned int _automaticallyScrubs:1;
    unsigned int _proxiesCurrentTime:1;
}

+ (BOOL)shouldProxyValueForCurrentTimeAtEndOfSeekableTimeRanges;
+ (id)keyPathsForValuesAffectingCurrentTimeAtEndOfSeekableTimeRanges;
+ (BOOL)shouldProxyValueForTimeAtEndOfSeekableTimeRanges;
+ (id)keyPathsForValuesAffectingTimeAtEndOfSeekableTimeRanges;
+ (BOOL)shouldProxyValueForThirtySecondsBeforeCurrentTimeWithinSeekableTimeRanges;
+ (id)keyPathsForValuesAffectingThirtySecondsBeforeCurrentTimeWithinSeekableTimeRanges;
+ (BOOL)shouldProxyValueForThirtySecondsBeforeCurrentTime;
+ (id)keyPathsForValuesAffectingThirtySecondsBeforeCurrentTime;
+ (BOOL)shouldProxyValueForDurationWithinEndTimes;
+ (id)keyPathsForValuesAffectingDurationWithinEndTimes;
+ (BOOL)shouldProxyValueForRemainingTimeWithinEndTimes;
+ (id)keyPathsForValuesAffectingRemainingTimeWithinEndTimes;
+ (BOOL)shouldProxyValueForCurrentTimeWithinEndTimes;
+ (id)keyPathsForValuesAffectingCurrentTimeWithinEndTimes;
+ (BOOL)shouldProxyValueForRemainingTime;
+ (id)keyPathsForValuesAffectingRemainingTime;
+ (BOOL)shouldProxyValueForCurrentTime;
+ (BOOL)shouldProxyValueForAutomaticallyScrubs;
+ (void)initialize;
@property(nonatomic) CDStruct_1b6d18a9 seekToTimeResolution; // @synthesize seekToTimeResolution=_seekToTimeResolution;
- (BOOL)isCurrentTimeAtEndOfSeekableTimeRanges;
- (CDStruct_1b6d18a9)timeAtEndOfSeekableTimeRanges;
- (BOOL)isThirtySecondsBeforeCurrentTimeWithinSeekableTimeRanges;
- (CDStruct_1b6d18a9)thirtySecondsBeforeCurrentTime;
- (BOOL)isTimeWithinSeekableTimeRanges:(CDStruct_1b6d18a9)arg1;
- (id)durationWithinEndTimes;
- (id)remainingTimeWithinEndTimes;
- (void)setCurrentTimeWithinEndTimes:(id)arg1;
- (id)currentTimeWithinEndTimes;
- (id)remainingTime;
- (void)setCurrentTime:(id)arg1;
- (id)currentTime;
- (void)updateNonProxiedCurrentTime:(CDStruct_1b6d18a9)arg1;
@property BOOL proxiesCurrentTime;
@property(nonatomic) BOOL automaticallyScrubs;
- (void)_stopScrubbing;
- (void)_startScrubbingIfAppropriate;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 queue:(id)arg2;
- (id)initWithTarget:(id)arg1 queue:(id)arg2 playerProxy:(id)arg3;

@end

