//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGKeyValueProxy.h"

@class MGPlayerControllerSelectionPlayerItem;

@interface MGPlayerControllerSelection : MGKeyValueProxy
{
    MGPlayerControllerSelectionPlayerItem *_currentItem;
    id _playerPeriodicTimeObserver;
    CDStruct_1b6d18a9 _timeUpdateInterval;
    unsigned int _periodicallyUpdatesTime:1;
    unsigned int _jogging:1;
    unsigned int _automaticallyScrubs:1;
    unsigned int _automaticallyPreventsIdleSleep:1;
    unsigned int _automaticallyPausesWhenSessionResignsActive:1;
}

+ (BOOL)shouldProxyValueForCurrentItem;
+ (BOOL)shouldProxyValueForAutomaticallyPausesWhenSessionResignsActive;
+ (BOOL)shouldProxyValueForAutomaticallyPreventsIdleSleep;
+ (BOOL)shouldProxyValueForAutomaticallyScrubs;
+ (BOOL)shouldProxyValueForTimeUpdateInterval;
+ (BOOL)shouldProxyValueForPeriodicallyUpdatesTime;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)currentItem;
@property(nonatomic) BOOL automaticallyPausesWhenSessionResignsActive;
@property(nonatomic) BOOL automaticallyPreventsIdleSleep;
@property(nonatomic) BOOL automaticallyScrubs;
@property(nonatomic, getter=isJogging) BOOL jogging;
@property(nonatomic) CDStruct_1b6d18a9 timeUpdateInterval;
@property(nonatomic) BOOL periodicallyUpdatesTime;
- (void)updatePlayerPeriodicTimeObserver;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 queue:(id)arg2;

@end

