//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class CATextLayer, NSString;

@interface MGPopUpLabelLayer : CALayer
{
    CATextLayer *_labelTextLayer;
    struct CGRect _constraintFrame;
    int _arrowEdge;
    double _scaleFactor;
    int _lastArrowEdge;
    double _lastArrowOffset;
    struct CGSize _lastPreferredFrameSize;
}

+ (id)defaultActionForKey:(id)arg1;
+ (struct CGImage *)newPopUpImageForPreferredFrameSize:(struct CGSize)arg1 cornerRadius:(double)arg2 arrowLength:(double)arg3 arrowWidth:(double)arg4 arrowOffset:(double)arg5 arrowEdge:(int)arg6 scaleFactor:(double)arg7;
+ (id)popUpPathWithBounds:(struct CGRect)arg1 cornerRadius:(double)arg2 arrowLength:(double)arg3 arrowWidth:(double)arg4 arrowOffset:(double)arg5 arrowEdge:(int)arg6;
@property(nonatomic) double scaleFactor;
@property(nonatomic) int arrowEdge;
@property(nonatomic) struct CGRect constraintFrame;
@property(copy, nonatomic) NSString *labelString;
- (void)setPosition:(struct CGPoint)arg1;
- (void)resizeSublayersWithOldSize:(struct CGSize)arg1;
- (void)sizeToFit;
- (struct CGSize)preferredFrameSize;
- (double)textInsetMarginY;
- (double)textInsetMarginX;
- (double)arrowWidth;
- (double)arrowLength;
- (double)scaledCornerRadius;
- (id)init;

@end

