//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MGPopUpPlayerLayer;

@interface MGPopUpPlayerView : NSView
{
    MGPopUpPlayerLayer *_leftPlayerLayer;
    MGPopUpPlayerLayer *_rightPlayerLayer;
    double _leftPosition;
    double _rightPosition;
}

- (void)layoutSublayersOfLayer:(id)arg1;
@property(nonatomic) double rightPosition;
@property(nonatomic) double leftPosition;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 leftPlayerItem:(id)arg2 rightPlayerItem:(id)arg3;

@end

