//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class AVPlayer, AVPlayerLayer, CAGradientLayer;

@interface MGPopUpPlayerLayer : CALayer
{
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    CAGradientLayer *_borderLayer;
    struct CGRect _constraintFrame;
    unsigned long long _alignment;
    double _scaleFactor;
    double _lastArrowOffset;
}

+ (id)popUpPathWithBounds:(struct CGRect)arg1 cornerRadius:(double)arg2 arrowLength:(double)arg3 arrowWidth:(double)arg4 arrowOffset:(double)arg5 arrowEdge:(int)arg6;
+ (struct CGImage *)newPopUpImageForPreferredFrameSize:(struct CGSize)arg1 arrowLength:(double)arg2 arrowWidth:(double)arg3 arrowOffset:(double)arg4 arrowEdge:(int)arg5 scaleFactor:(double)arg6;
+ (id)defaultActionForKey:(id)arg1;
+ (id)layerWithPlayerItem:(id)arg1;
- (void)itemDidPlayToEndTime:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)displayAndLayoutIfNeeded;
- (struct CGRect)playerLayerFrameForBounds:(struct CGRect)arg1;
- (struct CGRect)boundsForPlayerLayerSize:(struct CGSize)arg1;
- (struct CGSize)playerLayerSize;
- (double)insetMargin;
- (double)arrowWidth;
- (double)arrowLength;
@property(nonatomic) double scaleFactor;
@property(nonatomic) unsigned long long alignment;
@property(nonatomic) struct CGRect constraintFrame;
- (void)dealloc;
- (id)initWithPlayerItem:(id)arg1;

@end

