//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MGPopUpLabelLayer, NSString;

@interface MGPopUpLabelView : NSView
{
    struct CGRect _oldBounds;
    MGPopUpLabelLayer *_labelLayer;
    double _labelPosition;
}

@property(copy, nonatomic) NSString *labelString;
@property(nonatomic) double labelPosition;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

