//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

@class MGQuartzComposerView;

@interface MGQuartzComposerDocumentViewController : MGDocumentViewController
{
    MGQuartzComposerView *_qcView;
}

- (BOOL)prefersBorderedOverlays;
- (BOOL)prefersUnobscuredContent;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
- (void)close;
- (void)loadView;

@end

