//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@class MGAppendableData;

@interface MGReadOnlyRangeOfAppendableData : NSData
{
    MGAppendableData *_sourceData;
    struct _NSRange _range;
}

- (const void *)bytes;
- (unsigned long long)length;
- (void)dealloc;
- (id)init;
- (id)initWithRange:(struct _NSRange)arg1 ofData:(id)arg2;

@end

