//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocument.h"

#import "AVCaptureFileOutputDelegate.h"
#import "AVCaptureFileOutputRecordingDelegate.h"

@class AVCaptureFileOutput, AVCaptureSession, MGFormatDescription, NSError, NSInvocation, NSURL;

@interface MGRecordingDocument : MGDocument <AVCaptureFileOutputDelegate, AVCaptureFileOutputRecordingDelegate>
{
    AVCaptureSession *_captureSession;
    AVCaptureFileOutput *_captureFileOutput;
    NSURL *_outputDirectory;
    NSURL *_outputFile;
    MGFormatDescription *_outputVideoFormat;
    struct opaqueCMFormatDescription *_lastOutputVideoFormat;
    MGFormatDescription *_outputAudioFormat;
    struct opaqueCMFormatDescription *_lastOutputAudioFormat;
    NSError *_recordingError;
    NSInvocation *_closeAfterRecordingInvocation;
    unsigned int _flags;
}

+ (BOOL)autosavesInPlace;
@property(retain, nonatomic) MGFormatDescription *outputAudioFormat; // @synthesize outputAudioFormat=_outputAudioFormat;
@property(retain, nonatomic) MGFormatDescription *outputVideoFormat; // @synthesize outputVideoFormat=_outputVideoFormat;
@property(copy, nonatomic) NSError *recordingError; // @synthesize recordingError=_recordingError;
@property(readonly, nonatomic) NSURL *outputFile; // @synthesize outputFile=_outputFile;
@property(readonly, nonatomic) AVCaptureFileOutput *captureFileOutput; // @synthesize captureFileOutput=_captureFileOutput;
@property(readonly, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
- (void)commitEditingWithDelegate:(id)arg1 didCommitSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (id)writableTypesForSaveOperation:(unsigned long long)arg1;
- (BOOL)canAsynchronouslyWriteToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3;
- (void)invokeCompletionBlock:(CDUnknownBlockType)arg1;
- (void)runModalSavePanelForSaveOperation:(unsigned long long)arg1 delegate:(id)arg2 didSaveSelector:(SEL)arg3 contextInfo:(void *)arg4;
- (void)saveDocumentWithDelegate:(id)arg1 didSaveSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)recordingDocumentWorkspaceWillSleep:(id)arg1;
- (void)recordingDocumentWorkspaceSessionDidResignActive:(id)arg1;
- (void)captureSessionRuntimeErrorDidOccur:(id)arg1;
- (void)canCloseDocumentAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)canCloseDocumentWithDelegate:(id)arg1 shouldCloseSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (void)recordingDidFinish;
- (void)finishRecordingAndOpenDocumentWithURL:(id)arg1;
- (id)willPresentError:(id)arg1;
- (void)captureOutput:(id)arg1 didFinishRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3 error:(id)arg4;
- (void)fileOutputWillFinishRecording;
- (void)captureOutput:(id)arg1 willFinishRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3 error:(id)arg4;
- (BOOL)captureOutputShouldProvideSampleAccurateRecordingStart:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureFileOutputDidOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 fromConnection:(id)arg2;
- (void)stopWritingData;
- (BOOL)startWritingDataToURL:(id)arg1 error:(id *)arg2;
- (void)resumeRecording;
- (void)pauseRecording;
- (BOOL)isPaused;
- (void)stopRecording;
- (void)startRecording;
- (BOOL)isFinishingRecording;
- (BOOL)isRecording;
- (BOOL)isReady;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)outputFileType;
- (id)baseOutputFileName;
@property(copy, nonatomic) NSURL *outputDirectory;
- (id)displayName;
- (void)close;
- (void)dealloc;
- (id)initWithRecordingType:(int)arg1;
- (id)init;
- (void)handleStopCommand:(id)arg1;
- (void)applyDocumentErrorsToScriptCommand:(id)arg1;
- (void)handleStartCommand:(id)arg1;

@end

