//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSFileManagerDelegate.h"

@class NSDictionary, NSError, NSURL;

@interface MGReadMeOperation : NSOperation <NSFileManagerDelegate>
{
    NSDictionary *_saveParameters;
    NSError *_error;
    NSURL *_revealURL;
}

@property(copy) NSURL *revealURL; // @synthesize revealURL=_revealURL;
@property(copy) NSError *error; // @synthesize error=_error;
- (void)main;
- (BOOL)fileManager:(id)arg1 shouldProceedAfterError:(id)arg2 copyingItemAtPath:(id)arg3 toPath:(id)arg4;
- (void)dealloc;
- (id)initWithParameters:(id)arg1;

@end

