//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MGExportPreset, MGPlayerDocument, NSArray, NSIndexSet, NSPopUpButton;

@interface MGSaveAsAccessoryViewController : NSViewController
{
    NSPopUpButton *_presetPopUpButton;
    NSArray *_exportPresets;
    NSIndexSet *_separatorIndexes;
    NSArray *_passthroughFileTypes;
    long long _selectedIndex;
    MGPlayerDocument *_document;
}

+ (id)keyPathsForValuesAffectingSelectedFileTypes;
+ (id)keyPathsForValuesAffectingCurrentExportPreset;
+ (BOOL)automaticallyNotifiesObserversOfCurrentExportPreset;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(readonly, nonatomic) NSArray *selectedFileTypes;
@property(retain, nonatomic) MGExportPreset *currentExportPreset;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithExportPresets:(id)arg1 separatorIndexes:(id)arg2 passthroughFileTypes:(id)arg3 nibName:(id)arg4 bundle:(id)arg5 document:(id)arg6;

@end

