//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSArray, NSIndexSet, NSPopUpButton, NSString, NSTextField, NSURL;

@interface MGSaveForWebWindowController : NSWindowController
{
    NSPopUpButton *_folderPopup;
    NSTextField *_nameField;
    NSArray *_exportPresets;
    NSIndexSet *_selectionIndexes;
    NSURL *_outputFolder;
    NSString *_name;
}

+ (id)keyPathsForValuesAffectingCanSave;
+ (id)saveForWebWindowController;
+ (void)initialize;
@property(copy, nonatomic) NSIndexSet *selectionIndexes; // @synthesize selectionIndexes=_selectionIndexes;
@property(readonly, nonatomic) NSArray *exportPresets; // @synthesize exportPresets=_exportPresets;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSURL *outputFolder;
- (void)updateFolderPopup;
- (void)chooseFolder:(id)arg1;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
- (id)referenceMovieParametersForConfig:(id)arg1 destinationURL:(id)arg2;
- (id)exportParametersForConfig:(id)arg1 sourceURL:(id)arg2 destinationURL:(id)arg3;
- (id)readMeNameForBaseName:(id)arg1;
- (id)referenceMovieNameForBaseName:(id)arg1;
- (id)posterImageNameForBaseName:(id)arg1;
- (id)exportNameForBaseName:(id)arg1 exportPreset:(id)arg2;
- (void)exportAndShare;
- (BOOL)checkForExistingOutputFiles;
- (void)setDocument:(id)arg1;
@property(readonly, nonatomic) BOOL canSave;
- (void)windowDidLoad;
- (void)dealloc;
- (id)init;

@end

