//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGVisualContentContainer.h"

@class MGAudioLevelIndicator, MGCaptureDeviceAndInputSourceSelectionController, NSButton, NSPopUpButton, NSString, NSTextField, NSTimer, NSView;

@interface MGScreenRecordingDocumentViewController : MGDocumentViewController <MGVisualContentContainer>
{
    NSButton *_theOneButtonToRuleThemAll;
    MGAudioLevelIndicator *_audioLevelIndicator;
    NSTextField *_recordingTimeView;
    NSTextField *_recordingSizeView;
    NSPopUpButton *_optionsPopUp;
    NSView *_finishingView;
    struct CGSize _initialViewSize;
    MGCaptureDeviceAndInputSourceSelectionController *_deviceSelectionController;
    NSTimer *_audioLevelIndicatorTimer;
    NSTimer *_recordingTimeAndSizeTimer;
    unsigned int _isOptionPressed:1;
}

+ (id)keyPathsForValuesAffectingMaximumContentSize;
+ (id)keyPathsForValuesAffectingMinimumContentSize;
+ (id)keyPathsForValuesAffectingFixedContentSize;
+ (void)initialize;
@property(readonly, nonatomic) MGCaptureDeviceAndInputSourceSelectionController *deviceSelectionController; // @synthesize deviceSelectionController=_deviceSelectionController;
- (void)workspaceSessionDidBecomeActive:(id)arg1;
- (void)workspaceSessionDidResignActive:(id)arg1;
@property(readonly, nonatomic) NSString *audioDeviceErrorString;
- (void)updateRecordingTimeAndSize:(id)arg1;
- (void)stopRecordingTimeAndSizeTimer;
- (void)startRecordingTimeAndSizeTimer;
- (void)updateAudioLevelIndicator:(id)arg1;
- (void)stopAudioLevelIndicatorTimer;
- (void)startAudioLevelIndicatorTimer;
- (void)changeAudioPreviewVolumeToMinimum:(id)arg1;
- (void)changeAudioPreviewVolumeToMaximum:(id)arg1;
- (void)chooseOutputDirectory:(id)arg1;
- (void)takeSelectedCompressionPresetFromRepresentedObjectOf:(id)arg1;
- (void)takeSelectedAudioDeviceFromRepresentedObjectOf:(id)arg1;
- (void)changeRecordingState:(id)arg1;
- (void)startRecording:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)flagsChanged:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)syncUIWithRecordingState;
- (BOOL)isShowingDocumentModalInterface;
- (void)menuNeedsUpdate:(id)arg1;
- (struct CGSize)maximumContentSize;
- (struct CGSize)minimumContentSize;
- (struct CGSize)fixedContentSize;
- (BOOL)prefersConstrainedContentAspectRatio;
- (struct CGSize)naturalContentSize;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
- (void)close;
- (void)loadView;

@end

