//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGRecordingDocument.h"

#import "MGInspectionAttributeContainer.h"
#import "MGScreenSelectorDelegate.h"

@class AVCaptureScreenInput, MGCaptureAudioPreviewOutput, MGCaptureCompressionPreset, MGCaptureDeviceSelectionController, MGScreenRecordingDocumentViewController, MGScreenSelector, NSArray, NSOperationQueue, NSScreen, NSURL;

@interface MGScreenRecordingDocument : MGRecordingDocument <MGInspectionAttributeContainer, MGScreenSelectorDelegate>
{
    MGScreenRecordingDocumentViewController *_mainViewController;
    MGCaptureDeviceSelectionController *_captureDeviceSelectionController;
    AVCaptureScreenInput *_captureScreenInput;
    MGCaptureAudioPreviewOutput *_captureAudioPreviewOutput;
    NSArray *_availableCompressionPresets;
    MGCaptureCompressionPreset *_compressionPreset;
    MGScreenSelector *_screenSelector;
    NSScreen *_selectedScreen;
    struct CGRect _cropRect;
    id _hotKeyMonitor;
    NSURL *_outputFileURL;
    unsigned long long _startHostTime;
    unsigned long long _stopHostTime;
    BOOL _isInitiallySetup;
    BOOL _isClosing;
    BOOL _isWorkspaceInactive;
    id _hideObserver;
    NSOperationQueue *_hideShowQueue;
    id _unhideObserver;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingInspectionAttributes;
@property id unhideObserver; // @synthesize unhideObserver=_unhideObserver;
@property(retain) NSOperationQueue *hideShowQueue; // @synthesize hideShowQueue=_hideShowQueue;
@property id hideObserver; // @synthesize hideObserver=_hideObserver;
@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect=_cropRect;
@property(retain, nonatomic) NSScreen *selectedScreen; // @synthesize selectedScreen=_selectedScreen;
@property(readonly, nonatomic) NSArray *availableCompressionPresets; // @synthesize availableCompressionPresets=_availableCompressionPresets;
@property(readonly, nonatomic) MGCaptureAudioPreviewOutput *captureAudioPreviewOutput; // @synthesize captureAudioPreviewOutput=_captureAudioPreviewOutput;
@property(readonly, nonatomic) MGCaptureDeviceSelectionController *captureDeviceSelectionController; // @synthesize captureDeviceSelectionController=_captureDeviceSelectionController;
- (void)workspaceSessionDidBecomeActive:(id)arg1;
- (void)workspaceSessionDidResignActive:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateCaptureSessionRunningState;
- (void)captureFileOutputDidOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 fromConnection:(id)arg2;
- (void)stopWritingData;
- (BOOL)startWritingDataToURL:(id)arg1 error:(id *)arg2;
- (void)screenSelectorDidCancel:(id)arg1;
- (void)screenSelector:(id)arg1 didSelectRect:(struct CGRect)arg2 ofScreen:(id)arg3;
- (void)prepareToStartRecording;
- (void)cleanUpRecording;
- (id)baseOutputFileName;
@property(retain, nonatomic) MGCaptureCompressionPreset *compressionPreset;
- (void)applyCompressionOptionsToCaptureSession;
- (void)close;
- (void)viewControllerDidLoadView:(id)arg1;
- (id)mainViewController;
- (void)dealloc;
- (id)init;
@property(readonly, nonatomic) NSArray *inspectionInformation;
@property(readonly, nonatomic) NSArray *inspectionAttributes;
- (void)setRate:(float)arg1;
- (float)rate;
- (BOOL)playing;
- (void)setVolume:(float)arg1;
- (float)volume;
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (void)setLoops:(BOOL)arg1;
- (BOOL)loops;
- (id)naturalDimensions;
- (void)setCurrentTimeInSeconds:(id)arg1;
- (id)currentTimeInSeconds;
- (id)durationInSeconds;
- (unsigned long long)dataRate;
- (unsigned long long)dataSize;
- (void)setCurrentScreenCompression:(id)arg1;
- (void)setCurrentMovieCompression:(id)arg1;
- (void)setCurrentAudioCompression:(id)arg1;
- (void)setCurrentVideoRecordingDevice:(id)arg1;
- (void)setCurrentAudioRecordingDevice:(id)arg1;
- (id)currentScreenCompression;
- (id)currentMovieCompression;
- (id)currentAudioCompression;
- (id)currentVideoRecordingDevice;
- (id)currentAudioRecordingDevice;
- (void)handleResumeCommand:(id)arg1;
- (void)handlePauseCommand:(id)arg1;

@end

