//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CALayer, CAShapeLayer, MGStatusOverlayView, NSButton, NSString, NSTrackingArea;

@interface MGScreenSelectorOverlayView : NSView
{
    MGStatusOverlayView *_statusOverlayView;
    CAShapeLayer *_selectionMarchingAntsBackgroundLayer;
    CAShapeLayer *_selectionMarchingAntsLayer;
    CALayer *_selectionLayer;
    CALayer *_darkeningLayer;
    CALayer *_darkeningPunchOutLayer;
    NSTrackingArea *_selectionTrackingArea;
    NSTrackingArea *_selectionHandleTrackingAreas[8];
    NSButton *_OKButton;
    struct CGRect _visibleSelectionRect;
    struct CGRect _selectionRect;
    NSString *_selectionString;
    NSString *_confirmationString;
    struct CGSize _minimumSelectionSize;
    id <MGScreenSelectorOverlayViewDelegate> _delegate;
    unsigned int _isTrackingNewSelectionRect:1;
    unsigned int _hasSelectionRect:1;
    unsigned int _fullViewSelected:1;
    unsigned int _selectionLocked:1;
}

@property(nonatomic) id <MGScreenSelectorOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGSize minimumSelectionSize; // @synthesize minimumSelectionSize=_minimumSelectionSize;
@property(copy, nonatomic) NSString *confirmationString; // @synthesize confirmationString=_confirmationString;
@property(nonatomic) struct CGRect selectionRect;
@property(copy, nonatomic) NSString *selectionString;
@property(nonatomic, getter=isSelectionLocked) BOOL selectionLocked;
- (void)cancel:(id)arg1;
- (void)OK:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)cursorUpdate:(id)arg1;
- (void)updateTrackingAreas;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)cursorForSelectionHandle:(int)arg1;
- (struct CGRect)rectForSelectionHandle:(int)arg1;
- (void)viewDidMoveToWindow;
- (void)updateStatusOverlayView;
- (BOOL)isHighlighted;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;

@end

