//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSArray, NSArrayController, NSImage, NSIndexSet;

@interface MGShareToiTunesWindowController : NSWindowController
{
    NSArrayController *_presetsArrayController;
    NSArray *_exportPresetsArray;
    NSIndexSet *_exportPresetsSelectionIndexSet;
    id _iPodPreset;
    id _iPhone4AndiPadPreset;
    id _macAndPCPreset;
    NSImage *_iTunesIconImage;
}

+ (id)shareToiTunesWindowController;
+ (id)iTunesMusicWatchFolderURL;
@property(copy, nonatomic) NSIndexSet *exportPresetsSelectionIndexSet; // @synthesize exportPresetsSelectionIndexSet=_exportPresetsSelectionIndexSet;
@property(readonly, nonatomic) NSArray *exportPresetsArray; // @synthesize exportPresetsArray=_exportPresetsArray;
- (void)exportAndShare;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
@property(readonly, nonatomic) NSImage *iTunesIconImage; // @dynamic iTunesIconImage;
@property(readonly, nonatomic) id macAndPCPreset;
@property(readonly, nonatomic) id iPhone4AndiPadPreset;
@property(readonly, nonatomic) id iPodPreset;
- (void)setDocument:(id)arg1;
- (void)takeSelectedFrom:(id)arg1;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1;
- (id)init;
- (void)windowDidLoad;

@end

