//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class MGExportPreset, NSArray, NSImage, NSIndexSet, NSMatrix;

@interface MGShareToMailWindowController : NSWindowController <NSWindowDelegate>
{
    NSMatrix *_presetMatrix;
    NSArray *_exportPresets;
    NSIndexSet *_exportPresetsSelectionIndexes;
    NSImage *_mailIconImage;
}

+ (id)keyPathsForValuesAffectingSelectedExportPreset;
+ (id)shareToMailWindowController;
@property(copy, nonatomic) NSIndexSet *exportPresetsSelectionIndexes; // @synthesize exportPresetsSelectionIndexes=_exportPresetsSelectionIndexes;
@property(readonly, nonatomic) NSArray *exportPresets; // @synthesize exportPresets=_exportPresets;
- (void)exportAndShare;
@property(readonly, nonatomic) MGExportPreset *selectedExportPreset;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
@property(readonly, nonatomic) NSImage *mailIconImage; // @dynamic mailIconImage;
- (void)windowDidLoad;
- (void)setDocument:(id)arg1;
- (void)dealloc;
- (id)init;

@end

