//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MGFacebookAccount, NSMutableDictionary, NSString, NSView;

@interface MGShareToFacebookWindowController : NSWindowController
{
    NSView *_uploadView;
    NSView *_statusView;
    NSView *_currentView;
    MGFacebookAccount *_account;
    NSMutableDictionary *_metadata;
    NSString *_userName;
    NSString *_userID;
    BOOL _authenticating;
    BOOL _private;
    BOOL _quota;
}

+ (id)keyPathsForValuesAffectingQuota;
+ (id)keyPathsForValuesAffectingAuthenticating;
+ (unsigned long long)maximumMovieDataSizeForFacebook;
+ (CDStruct_1b6d18a9)maximumMovieDurationForFacebook;
@property(nonatomic, getter=hasQuota) BOOL quota; // @synthesize quota=_quota;
@property(nonatomic, getter=isPrivate) BOOL private; // @synthesize private=_private;
@property(nonatomic) BOOL authenticating; // @synthesize authenticating=_authenticating;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(readonly, nonatomic) NSMutableDictionary *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) MGFacebookAccount *account; // @synthesize account=_account;
- (void)verifyAuthentication;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)handleQuota;
- (void)exportAndShare;
- (void)showErrorDialog:(id)arg1;
- (void)setDocument:(id)arg1;
- (void)makeCurrentView:(id)arg1;
- (void)windowDidLoad;
- (void)cancel:(id)arg1;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithAccount:(id)arg1;

@end

