//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSError, NSImage, NSString, NSURL, NSView;

@interface MGShareToiMovieWindowController : NSWindowController
{
    NSURL *_iMovieWatchFolderURL;
    NSError *_error;
    NSView *_displayView;
    NSView *_currentView;
    NSView *_holderView;
    NSImage *_iMovieIconImage;
}

+ (id)iMovieDropBoxes;
+ (id)shareToiMovieWindowController;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(copy, nonatomic) NSURL *iMovieWatchFolderURL; // @synthesize iMovieWatchFolderURL=_iMovieWatchFolderURL;
- (void)exportAndShare;
- (id)locationForiMovieWatchFolder:(id)arg1 error:(id *)arg2;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
@property(readonly, nonatomic) NSImage *iMovieIconImage; // @dynamic iMovieIconImage;
- (void)setDocument:(id)arg1;
- (void)windowDidLoad;
- (void)makeCurrentView:(id)arg1;
@property(readonly, nonatomic) NSString *displayString;
- (id)keyPathsForValuesAffectingDisplayString;
- (id)localizedErrorString;
- (void)dealloc;
- (id)init;

@end

