//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MGFlickrAccount, MGFlickrRESTInterface, NSArray, NSMutableDictionary, NSString, NSTokenField, NSView;

@interface MGShareToFlickrWindowController : NSWindowController
{
    NSView *_uploadView;
    NSTokenField *_keywordsField;
    NSView *_currentView;
    MGFlickrAccount *_account;
    MGFlickrRESTInterface *_flickrInterface;
    BOOL _authenticating;
    NSMutableDictionary *_metadata;
    BOOL _private;
    NSArray *_keywords;
}

+ (id)keyPathsForValuesAffectingAuthenticating;
+ (id)keyPathsForValuesAffectingUserName;
+ (CDStruct_1b6d18a9)maximumMovieDurationForFlickr;
@property(copy, nonatomic) MGFlickrAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
@property(nonatomic, getter=isPrivate) BOOL private; // @synthesize private=_private;
@property(nonatomic, getter=isAuthenticating) BOOL authenticating; // @synthesize authenticating=_authenticating;
@property(readonly, nonatomic) NSMutableDictionary *metadata; // @synthesize metadata=_metadata;
- (void)exportAndShare;
@property(readonly, nonatomic) NSString *userName;
- (void)verifyAuthenticationWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)showErrorDialog:(id)arg1;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
- (void)setDocument:(id)arg1;
- (void)switchToMetadataView;
- (void)makeCurrentView:(id)arg1;
- (void)windowDidLoad;
@property(readonly, nonatomic) MGFlickrRESTInterface *flickrInterface;
- (void)dealloc;
- (id)init;
- (id)initWithAccount:(id)arg1;

@end

