//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "MGYouTubeAccountAuthenticationDelegate.h"
#import "MGYouTubeAuthenticationViewDelegate.h"
#import "NSURLConnectionDelegate.h"
#import "NSWindowDelegate.h"

@class MGYouTubeAccount, MGYouTubeAuthenticationViewController, NSArray, NSError, NSImage, NSMutableData, NSMutableDictionary, NSURLConnection, NSView;

@interface MGShareToYouTubeWindowController : NSWindowController <NSWindowDelegate, NSURLConnectionDelegate, MGYouTubeAccountAuthenticationDelegate, MGYouTubeAuthenticationViewDelegate>
{
    NSView *_authView;
    NSView *_authViewFirstResponder;
    NSView *_metadataView;
    NSView *_metadataViewFirstResponder;
    NSView *_termsOfServiceView;
    MGYouTubeAccount *_youTubeAccount;
    NSView *_currentView;
    NSArray *_categories;
    NSURLConnection *_fetchCategoriesConnection;
    NSMutableData *_fetchCategoriesDownloadedData;
    NSError *_fetchingStandardCategoriesError;
    NSMutableDictionary *_metadata;
    MGYouTubeAuthenticationViewController *_authViewController;
}

+ (id)keyPathsForValuesAffectingMetadataContainsInvalidTags;
+ (unsigned long long)maximumMovieDataSizeForYouTube;
+ (CDStruct_1b6d18a9)maximumMovieDurationForYouTube;
@property(readonly, nonatomic) NSMutableDictionary *metadata; // @synthesize metadata=_metadata;
@property(copy, nonatomic) NSError *fetchingStandardCategoriesError; // @synthesize fetchingStandardCategoriesError=_fetchingStandardCategoriesError;
@property(copy, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(retain, nonatomic) MGYouTubeAccount *youTubeAccount; // @synthesize youTubeAccount=_youTubeAccount;
- (void)shouldCloseAuthenticationWindow:(id)arg1;
- (void)exportAndShare;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)startFetchingStandardCategories;
- (void)cancelAuthentication;
- (void)accountAuthenticationDidFail:(id)arg1;
- (void)accountAuthenticationDidSucceed:(id)arg1;
- (void)showMetadata:(id)arg1;
- (void)showTermsOfService:(id)arg1;
- (void)authenticate:(id)arg1;
- (void)changeUser:(id)arg1;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
- (void)setDocument:(id)arg1;
@property(readonly) NSImage *warningImage; // @dynamic warningImage;
@property(readonly, nonatomic) BOOL metadataContainsInvalidTags;
@property(readonly, nonatomic, getter=isFetchingStandardCategories) BOOL fetchingStandardCategories;
- (void)switchToMetadataView;
- (void)switchToAuthView;
- (void)makeCurrentView:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)init;

@end

