//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class MGVimeoAccount, NSImage, NSMutableDictionary, NSString, NSView;

@interface MGShareToVimeoWindowController : NSWindowController <NSWindowDelegate>
{
    NSView *_authView;
    NSView *_authViewFirstResponder;
    NSView *_metadataView;
    NSView *_metadataViewFirstResponder;
    NSView *_termsOfServiceView;
    MGVimeoAccount *_account;
    NSView *_currentView;
    NSString *_presetName;
    NSMutableDictionary *_metadata;
}

+ (unsigned long long)maximumMovieDataSizeForVimeo;
@property(copy, nonatomic) NSString *presetName; // @synthesize presetName=_presetName;
@property(copy, nonatomic) MGVimeoAccount *account; // @synthesize account=_account;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)handleQuotaInfo;
- (id)exportPresetForShareEncoding:(id *)arg1;
- (void)exportAndShare;
- (void)cancelAuthentication;
- (void)showMetadata:(id)arg1;
- (void)showTermsOfService:(id)arg1;
- (void)closeShareWindow:(id)arg1;
- (void)beginShare:(id)arg1;
- (void)setDocument:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *metadata;
@property(readonly) NSImage *warningImage; // @dynamic warningImage;
- (void)switchToMetadataView;
- (void)makeCurrentView:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)init;
- (id)initWithAccount:(id)arg1;

@end

