//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface MGShuttleSliderValueTransformer : NSValueTransformer
{
    unsigned int _joggingEnabled:1;
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;
@property(nonatomic, getter=isJoggingEnabled) BOOL joggingEnabled;

@end

