//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface MGSimpleBinder : NSObject
{
    id _target;
    NSString *_binding;
    id _observable;
    NSString *_keyPath;
    NSDictionary *_options;
    BOOL _modifyingTarget;
    BOOL _modifyingObservable;
}

@property(readonly) NSDictionary *options; // @synthesize options=_options;
@property(readonly) NSString *keyPath; // @synthesize keyPath=_keyPath;
@property(readonly) id observable; // @synthesize observable=_observable;
@property(readonly) NSString *binding; // @synthesize binding=_binding;
@property(readonly) id target; // @synthesize target=_target;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)infoForBinding;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 binding:(id)arg2 observable:(id)arg3 keyPath:(id)arg4 options:(id)arg5;
- (id)init;

@end

