//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocument.h"

#import "MGInspectionAttributeContainer.h"

@class MGDocumentViewController<MGVisualContentContainer>, MGMovieErrorReporter, MGMovieInspectionAttributes, NSArray, QTMovie;

@interface MGSlideshowMovieDocument : MGDocument <MGInspectionAttributeContainer>
{
    QTMovie *_movie;
    MGDocumentViewController<MGVisualContentContainer> *_mainViewController;
    struct __CFRunLoopSource *_loadingRunLoopSource;
    MGMovieErrorReporter *_movieErrorReporter;
    MGMovieInspectionAttributes *_movieInspectionAttributes;
    unsigned int _movieIsLoaded:1;
    unsigned int _isClosing:1;
    unsigned int _isTearingDownMovie:1;
    unsigned int _isObservingLoadState:1;
}

+ (id)keyPathsForValuesAffectingInspectionInformation;
+ (id)keyPathsForValuesAffectingInpsectionAttributes;
@property(readonly, nonatomic) QTMovie *movie; // @synthesize movie=_movie;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)movieEdited:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)updateMainViewControllerWithoutKVONotification;
- (id)mainViewController;
- (id)movieLoadError;
- (id)displayName;
- (void)movieLoadStateDidChange:(id)arg1;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)dealloc;
- (void)close;
- (void)tearDownMovie;
@property(readonly, nonatomic) NSArray *inspectionInformation;
@property(readonly, nonatomic) NSArray *inspectionAttributes;
- (id)movieInspectionAttributes;
- (void)updateMovieInspectionAttributesCurrentSize;

@end

