//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTMovieView.h"

@class NSEvent;

@interface MGSlideshowMovieView : QTMovieView
{
    NSEvent *_mouseDownEventToHandle;
}

@property(retain, nonatomic) NSEvent *mouseDownEventToHandle; // @synthesize mouseDownEventToHandle=_mouseDownEventToHandle;
- (void)keyDown:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (id)menuForEvent:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (void)dealloc;

@end

