//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGAutovisibilityControllerOwner.h"
#import "MGVisualContentContainer.h"

@class MGAutovisibilityController, MGMoviePlaybackController, QTMovieView;

@interface MGSlideshowMovieDocumentViewController : MGDocumentViewController <MGAutovisibilityControllerOwner, MGVisualContentContainer>
{
    QTMovieView *_movieView;
    MGMoviePlaybackController *_moviePlaybackController;
    MGAutovisibilityController *_autovisibilityController;
    struct CGSize _movieNaturalSize;
    struct CGSize _currentVideoSize;
    BOOL _prefersUnobscuredContent;
}

@property(readonly, nonatomic) struct CGSize currentVideoSize; // @synthesize currentVideoSize=_currentVideoSize;
- (BOOL)prefersBorderedOverlays;
- (void)setPrefersUnobscuredContent:(BOOL)arg1;
- (BOOL)prefersUnobscuredContent;
- (void)movieViewDidResize:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)hideForAutovisibilityController:(id)arg1 dueToTimeout:(BOOL)arg2;
- (void)showForAutovisibilityController:(id)arg1;
- (void)_updateCurrentSize;
- (struct CGSize)minimumContentSize;
- (struct CGSize)naturalContentSize;
- (BOOL)prefersConstrainedContentAspectRatio;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
- (void)close;
- (void)resignMainViewControllerForWindowController:(id)arg1;
- (void)becomeMainViewControllerForWindowController:(id)arg1;
- (void)loadView;

@end

