//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImage, NSString, NSTextFieldCell;

@interface MGStatusOverlayView : NSView
{
    NSTextFieldCell *_textFieldCell;
    double _textFieldCellHeight;
    NSImage *_image;
    unsigned long long _alignment;
    double _contentsPadding;
    double _cornerRadius;
}

@property(nonatomic) double cornerRadius;
@property(nonatomic) double contentsPadding;
@property(nonatomic) unsigned long long alignment;
@property(retain, nonatomic) NSImage *image;
@property(copy, nonatomic) NSString *stringValue;
- (void)drawRect:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

