//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface MGSuperlayerBoundedContainerLayer : CALayer
{
    double _padding[4];
    double _margin[4];
}

- (void)setMarginForMinX:(double)arg1 minY:(double)arg2 maxX:(double)arg3 maxY:(double)arg4;
- (void)setPaddingForMinX:(double)arg1 minY:(double)arg2 maxX:(double)arg3 maxY:(double)arg4;
- (struct CGSize)preferredFrameSize;

@end

