//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSUndoManager;

@interface MGTrimViewControllerState : NSObject
{
    CDStruct_e83c9415 _selectionRange;
    NSUndoManager *_undoManager;
    NSString *_nextUndoManagerActionName;
}

+ (id)keyPathsForValuesAffectingSelectionEnd;
+ (BOOL)automaticallyNotifiesObserversOfSelectionEnd;
+ (id)keyPathsForValuesAffectingSelectionStart;
+ (BOOL)automaticallyNotifiesObserversOfSelectionStart;
@property(copy, nonatomic) NSString *nextUndoManagerActionName; // @synthesize nextUndoManagerActionName=_nextUndoManagerActionName;
@property(readonly, nonatomic) NSUndoManager *undoManager; // @synthesize undoManager=_undoManager;
@property(nonatomic) CDStruct_1b6d18a9 selectionEnd;
@property(nonatomic) CDStruct_1b6d18a9 selectionStart;
@property(nonatomic) CDStruct_e83c9415 selectionRange;
- (void)dealloc;
- (id)init;

@end

