//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGMediaTimelineViewDelegate.h"

@class MGMediaClip, MGMediaTimelineView, MGTrimViewControllerState, NSString;

@interface MGTrimViewController : MGDocumentViewController <MGMediaTimelineViewDelegate>
{
    MGMediaTimelineView *_timelineView;
    id <MGTrimViewControllerDelegate> _delegate;
    MGMediaClip *_mediaClip;
    CDStruct_e83c9415 _inputRange;
    CDStruct_1b6d18a9 _maximumSelectionDuration;
    CDStruct_e83c9415 _initialSelectionRange;
    NSString *_trimButtonTitle;
    MGTrimViewControllerState *_state;
    BOOL _isEditing;
    BOOL _isAlwaysEditing;
}

+ (id)undoTrimActionNameForSelectionEdge:(int)arg1;
+ (id)keyPathsForValuesAffectingTimelineUpdateResolution;
+ (id)keyPathsForValuesAffectingUndoManager;
+ (id)keyPathsForValuesAffectingSelectionRange;
+ (BOOL)automaticallyNotifiesObserversOfSelectionRange;
@property(copy, nonatomic) NSString *trimButtonTitle; // @synthesize trimButtonTitle=_trimButtonTitle;
@property(nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_isEditing;
@property(nonatomic) MGMediaClip *mediaClip; // @synthesize mediaClip=_mediaClip;
@property(nonatomic) id <MGTrimViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) MGMediaTimelineView *timelineView; // @synthesize timelineView=_timelineView;
- (id)copyWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (CDStruct_e83c9415)selectionRangeExcludingSilence;
- (void)selectAllExcludingSilence:(id)arg1;
- (void)selectAll:(id)arg1;
- (CDStruct_900afa40)timelineView:(id)arg1 willStepBackwardCurrentMediaTimeToTime:(CDStruct_900afa40)arg2;
- (CDStruct_900afa40)timelineView:(id)arg1 willStepForwardCurrentMediaTimeToTime:(CDStruct_900afa40)arg2;
- (CDStruct_900afa40)timelineView:(id)arg1 willChangeCurrentMediaTimeToTime:(CDStruct_900afa40)arg2;
- (void)timelineViewDidStopTrackingCurrentMediaTime:(id)arg1;
- (void)timelineViewWillStartTrackingCurrentMediaTime:(id)arg1;
- (CDStruct_900afa40)timelineView:(id)arg1 willStepBackwardSelectionEdge:(int)arg2 toTime:(CDStruct_900afa40)arg3;
- (CDStruct_900afa40)timelineView:(id)arg1 willStepForwardSelectionEdge:(int)arg2 toTime:(CDStruct_900afa40)arg3;
- (CDStruct_900afa40)timelineView:(id)arg1 willChangeSelectionEdge:(int)arg2 toTime:(CDStruct_900afa40)arg3;
- (void)timelineView:(id)arg1 didStopTrackingSelectionEdge:(int)arg2;
- (void)timelineView:(id)arg1 willStartTrackingSelectionEdge:(int)arg2;
- (id)playerLayer;
- (id)player;
@property(readonly, nonatomic) double timelineUpdateResolution;
- (void)undoManagerDidRedoChange:(id)arg1;
- (void)undoManagerDidUndoChange:(id)arg1;
- (void)undoManagerWillCloseUndoGroup:(id)arg1;
- (void)commitEditingAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)commitEditingWithDelegate:(id)arg1 didCommitSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (BOOL)commitEditing;
- (void)discardEditing;
- (void)resetState;
- (id)undoManager;
- (void)setState:(id)arg1;
- (id)state;
@property(readonly, nonatomic) CDStruct_1b6d18a9 commitEditingCurrentTime;
@property(nonatomic) CDStruct_e83c9415 selectionRange;
@property(nonatomic) CDStruct_1b6d18a9 maximumSelectionDuration;
@property(nonatomic) CDStruct_e83c9415 initialSelectionRange;
@property(nonatomic) CDStruct_e83c9415 inputRange;
- (void)viewWillHide;
- (void)viewWillShow;
- (void)close;
- (void)loadView;
- (id)initWithDocument:(id)arg1 nibName:(id)arg2 bundle:(id)arg3;

@end

