//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface MGURLComponent : NSObject
{
    NSURL *_URL;
}

+ (id)URLComponentWithURL:(id)arg1;
- (id)iconAsAttributedString;
- (id)presentableName;
- (id)containerComponent;
- (id)name;
- (id)URL;
- (void)dealloc;
- (id)init;
- (id)initWithURL:(id)arg1;

@end

