//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class MGMultipartInputStream, MGVimeoAccount, NSDictionary, NSError, NSMutableData, NSString, NSURL, NSURLConnection;

@interface MGVimeoPublishOperation : NSOperation <NSURLConnectionDelegate>
{
    MGVimeoAccount *_account;
    NSDictionary *_publishParameters;
    BOOL _finished;
    BOOL _executing;
    float _progress;
    NSError *_error;
    unsigned long long _dataSize;
    NSString *_ticketID;
    NSURL *_revealURL;
    NSMutableData *_downloadedData;
    NSURLConnection *_uploadConfirmationConnection;
    NSURLConnection *_uploadTicketConnection;
    NSURLConnection *_postVideoConnection;
    NSURLConnection *_currentConnection;
    MGMultipartInputStream *_mppInputStream;
}

+ (id)publishOperationWithParameters:(id)arg1 account:(id)arg2;
@property(retain, nonatomic) NSMutableData *downloadedData; // @synthesize downloadedData=_downloadedData;
@property(copy) NSString *ticketID; // @synthesize ticketID=_ticketID;
@property(copy) NSURL *revealURL; // @synthesize revealURL=_revealURL;
@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) NSString *localizedStatusMessage;
@property(readonly) float progress;
- (void)cancel;
@property(readonly, nonatomic) NSString *mimeBoundary;
- (void)handleUploadDidFinish;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)setMetadataForVideoID:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)startUploadConfirmation;
- (void)postVideoToURL:(id)arg1;
- (void)startUploadTicketOperation;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (void)start;
- (void)dealloc;
- (id)initWithParameters:(id)arg1 account:(id)arg2;

@end

