//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CALayer, MGPassThroughAnimator, NSArray;

@interface MGVideoView : NSView
{
    CALayer *_videoLayer;
    CALayer *_overlayLayer;
    MGPassThroughAnimator *_animator;
    int _contentFillMode;
    struct CGSize _fixedContentSize;
    struct CGSize _videoNaturalSize;
    NSArray *_intersectingDisplayIDs;
    unsigned int _excludesVideoRegionFromScreenCapture:1;
    unsigned int _tracksIntersectingDisplays:1;
    unsigned int _ExcludedVideoRegionNeedsUpdate:1;
    unsigned int _intersectingDisplaysNeedUpdate:1;
}

+ (id)keyPathsForValuesAffectingVideoFrame;
@property(readonly, nonatomic) NSArray *intersectingDisplayIDs; // @synthesize intersectingDisplayIDs=_intersectingDisplayIDs;
- (void)windowDidChangeID:(id)arg1;
- (void)renewGState;
- (void)updateIntersectingDisplays;
- (void)updateIntersectingDisplaysIfNeeded;
- (void)setIntersectingDisplaysNeedUpdate;
- (void)updateExcludedVideoRegion;
- (void)updateExcludedVideoRegionIfNeeded;
- (void)setExcludedVideoRegionNeedsUpdate;
@property(nonatomic) BOOL tracksIntersectingDisplays;
@property(nonatomic) BOOL excludesVideoRegionFromScreenCapture;
- (void)layoutSublayersOfLayer:(id)arg1;
@property(nonatomic) CALayer *overlayLayer;
- (struct CGRect)videoFrameForBoundsSize:(struct CGSize)arg1 contentFillMode:(int)arg2;
@property(readonly, nonatomic) struct CGRect videoFrame;
@property(nonatomic) struct CGSize videoNaturalSize;
@property(nonatomic) struct CGSize fixedContentSize;
@property(nonatomic) int contentFillMode;
- (BOOL)mouseDownCanMoveWindow;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)animator;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 videoLayer:(id)arg2;

@end

