//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGDocumentViewController.h"

#import "MGAutovisibilityControllerOwner.h"
#import "MGChapterMenuControllerDelegate.h"
#import "MGChapterViewControllerDelegate.h"
#import "MGFullScreenChapterViewControllerDelegate.h"
#import "MGTrimViewControllerDelegate.h"
#import "MGViewLayoutManager.h"
#import "MGVisualContentContainer.h"

@class MGAnimatedTabView, MGAutovisibilityController, MGBackgroundColorView, MGChapterMenuController, MGChapterViewController, MGDraggableView, MGEditViewController, MGFullScreenChapterViewController, MGGroupViewTextFieldPairResizer, MGHUDBackgroundView, MGMediaClip, MGMovieStatusStringController, MGPlayPauseShuttleControllerView, MGPlayerController, MGPopUpLabelView, MGStatusOverlayView, MGTrimViewController, MGVideoView, NSButton, NSImage, NSNumberFormatter, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSPopUpButton, NSString, NSTextField, NSTimer, NSView, NSWindowController, QTHUDGroupViewItem, QTHUDTimeFormatter;

@interface MGVideoPlaybackViewController : MGDocumentViewController <MGViewLayoutManager, MGAutovisibilityControllerOwner, MGTrimViewControllerDelegate, MGChapterViewControllerDelegate, MGFullScreenChapterViewControllerDelegate, MGChapterMenuControllerDelegate, MGVisualContentContainer>
{
    MGPlayerController *_playerControllerForTextFields;
    MGPlayerController *_playerControllerForSlider;
    MGVideoView *_videoView;
    MGDraggableView *_controlsView;
    MGHUDBackgroundView *_controlsBackgroundView;
    MGHUDBackgroundView *_shrinkedControlsBackgroundView;
    NSView *_playbackControlsContainerView;
    MGAnimatedTabView *_timelineAndStatusStringTabView;
    MGStatusOverlayView *_statusOverlayView;
    NSTextField *_elapsedTimeTextField;
    NSTextField *_remainingTimeTextField;
    NSTextField *_durationTextField;
    QTHUDGroupViewItem *_elapsedTimeGroupViewItem;
    QTHUDGroupViewItem *_remainingTimeAndDurationGroupViewItem;
    NSPopUpButton *_chapterPopUpButton;
    MGPlayPauseShuttleControllerView *_playPauseShuttleControllerView;
    NSButton *_shareButton;
    NSWindowController *_parentWindowController;
    MGGroupViewTextFieldPairResizer *_textFieldPairResizer;
    id _playerController;
    MGMovieStatusStringController *_movieStatusStringController;
    MGChapterMenuController *_chapterMenuController;
    MGAutovisibilityController *_autovisibilityController;
    MGChapterViewController *_chapterViewController;
    MGFullScreenChapterViewController *_fullScreenChapterViewController;
    MGEditViewController *_editViewController;
    MGTrimViewController *_trimViewController;
    MGDocumentViewController *_remoteHUDController;
    MGMediaClip *_trimMediaClip;
    NSTimer *_trimFocusTimeoutTimer;
    MGPopUpLabelView *_trimFocusPopUpLabelView;
    QTHUDTimeFormatter *_trimFocusTimeFormatter;
    CDUnknownBlockType _trimCompletionHandler;
    CDStruct_1b6d18a9 _trimMaximumDuration;
    NSString *_trimLocalizedActionName;
    NSString *_trimSavedLocalizedActionName;
    int _fullScreenContentFillMode;
    struct CGSize _controlsNaturalFrameSize;
    struct CGSize _movieNaturalSize;
    struct CGSize _currentVideoSize;
    struct CGRect _savedControlsFrame;
    struct CGRect _boundsWhenControlsFrameWasSaved;
    double _savedBackgroundViewContentBorderPosition;
    double _editControlsNaturalHeight;
    double _trimControlsNaturalHeight;
    NSNumberFormatter *_rateStatusOverlayFormatter;
    NSTimer *_transientStatusOverlayTimeoutTimer;
    NSString *_persistentStatusOverlayString;
    NSImage *_persistentStatusOverlayImage;
    MGBackgroundColorView *_HDCPAlertView;
    long long _externalProtectionStatus;
    NSObject<OS_dispatch_queue> *_HDCPTimerQueue;
    NSObject<OS_dispatch_source> *_HDCPTimer;
    long long _HUDHideCount;
    unsigned int _excludesVideoRegionFromScreenCapture:1;
    unsigned int _isShowingEditControls:1;
    unsigned int _hideEditControlsAfterDraggingDestinationOperation:1;
    unsigned int _doNotOverridePrefersUnobscuredContent:1;
    unsigned int _prefersUnobscuredTimeline:1;
    unsigned int _isShowingTrimControls:1;
    unsigned int _isAnimatingControls:1;
    unsigned int _isShowingTrimFocus:1;
    unsigned int _prefersUnobscuredContent:1;
    unsigned int _shouldHandleMouseUp:1;
    unsigned int _showChapterExposeButton:1;
    unsigned int _isZoomed:1;
    unsigned int _canZoomHorizontally:1;
    unsigned int _canZoomVertically:1;
    unsigned int _zoomUpdateIsScheduled:1;
    unsigned int _isAnimatingFullScreen:1;
    unsigned int _didPauseForSheet:1;
    unsigned int _needsToUpdateCurrentSize:1;
    unsigned int _isObservingExternalProtectionStatus:1;
    unsigned int _inStateRestore:1;
}

+ (void)initialize;
@property(readonly, nonatomic) struct CGSize currentVideoSize; // @synthesize currentVideoSize=_currentVideoSize;
@property(readonly, nonatomic) MGMovieStatusStringController *movieStatusStringController; // @synthesize movieStatusStringController=_movieStatusStringController;
@property(readonly, nonatomic) NSWindowController *parentWindowController; // @synthesize parentWindowController=_parentWindowController;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)draggingEnded:(id)arg1;
- (void)concludeDragOperation:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)invalidateRestorableState;
- (void)restoreStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)mainWindowDidEndSheet:(id)arg1;
- (void)mainWindowWillBeginSheet:(id)arg1;
- (void)flagsChanged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)beginGestureWithEvent:(id)arg1;
- (void)copy:(id)arg1;
- (void)updateExternalProtectionStatus:(id)arg1;
- (void)updateHDCPAlertView;
- (void)hideStatusOverlayString;
- (void)showStatusOverlayString;
- (void)clearTransientStatusOverlayString;
- (void)setTransientStatusOverlayString:(id)arg1 image:(id)arg2;
- (void)clearPersistentStatusOverlayString;
- (void)setPersistentStatusOverlayString:(id)arg1 image:(id)arg2;
- (void)gotoPreviousChapter:(id)arg1;
- (void)gotoNextChapter:(id)arg1;
- (void)showCurrentChapterOverlay;
- (void)chapterMenuController:(id)arg1 didSelectChapter:(id)arg2;
- (void)chapterPopUpButtonWillPopup:(id)arg1;
- (void)toggleChapterExposeMode:(id)arg1;
- (void)hideChaptersWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)showChapters;
- (void)fullScreenChapterViewController:(id)arg1 didSelectChapter:(id)arg2;
- (void)chapterViewController:(id)arg1 didSelectChapter:(id)arg2;
- (void)chapterViewControllerDidSelectChapter:(id)arg1;
- (void)hideFullScreenChapters;
- (void)showFullScreenChapters;
- (BOOL)isShowingFullScreenChapters;
- (void)hideWindowedChaptersWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)showWindowedChapters;
- (BOOL)isShowingWindowedChapters;
- (BOOL)isShowingChapterExpose;
- (BOOL)canShowChapters;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepBackwardCurrentMediaTimeToTime:(CDStruct_1b6d18a9)arg2;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepForwardCurrentMediaTimeToTime:(CDStruct_1b6d18a9)arg2;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willChangeCurrentMediaTimeToTime:(CDStruct_1b6d18a9)arg2;
- (void)trimViewControllerDidStopTrackingCurrentMediaTime:(id)arg1;
- (void)trimViewControllerWillStartTrackingCurrentMediaTime:(id)arg1;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepBackwardSelectionEdge:(int)arg2 toTime:(CDStruct_1b6d18a9)arg3;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willStepForwardSelectionEdge:(int)arg2 toTime:(CDStruct_1b6d18a9)arg3;
- (CDStruct_1b6d18a9)trimViewController:(id)arg1 willChangeSelectionEdge:(int)arg2 toTime:(CDStruct_1b6d18a9)arg3;
- (void)trimViewController:(id)arg1 didStopTrackingSelectionEdge:(int)arg2;
- (void)trimViewController:(id)arg1 willStartTrackingSelectionEdge:(int)arg2;
- (void)hideTrimFocus;
- (void)showTrimFocusWithTimeout:(BOOL)arg1 forMediaTime:(CDStruct_1b6d18a9)arg2;
- (void)trimDidEndWithResult:(BOOL)arg1;
- (void)trimViewControllerDidCommitEditing:(id)arg1;
- (void)presentTrimDidFailErrorForMediaClip:(id)arg1 dueToUnloadedAssetForMediaClip:(id)arg2;
- (void)cancelTrim:(id)arg1;
- (void)confirmTrim:(id)arg1;
- (void)startTrimWithMaximumDuration:(CDStruct_1b6d18a9)arg1 localizedActionName:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)startTrim:(id)arg1;
- (void)startTrimForMediaClip:(id)arg1 withMaximumDuration:(CDStruct_1b6d18a9)arg2 localizedActionName:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
@property(nonatomic, getter=isShowingTrimControls) BOOL showingTrimControls;
- (BOOL)canTrim;
- (void)setPrefersUnobscuredTimeline:(BOOL)arg1;
@property(nonatomic, getter=isShowingEditControls) BOOL showingEditControls;
- (BOOL)canEdit;
- (void)hideEditControls:(id)arg1;
- (void)showEditControls:(id)arg1;
- (void)windowControllerDidFinishFullScreenAnimation:(id)arg1;
- (void)windowControllerDidStartFullScreenAnimation:(id)arg1;
- (void)toggleZoom:(id)arg1;
@property(readonly, nonatomic) BOOL canZoomVertically;
@property(readonly, nonatomic) BOOL canZoomHorizontally;
@property(readonly, nonatomic, getter=isZoomed) BOOL zoomed;
@property(readonly, nonatomic) BOOL showChapterExposeButton;
- (void)_setNeedsZoomPropertiesUpdate;
- (void)_updateZoomProperties;
- (int)_contentFillModeForZoom;
- (void)panoramicStretchToScreen:(id)arg1;
- (void)stretchToScreen:(id)arg1;
- (void)fillScreen:(id)arg1;
- (void)fitToScreen:(id)arg1;
- (void)actualSize:(id)arg1;
- (void)_sendActionToWindowController:(SEL)arg1 from:(id)arg2;
- (void)_setFullScreenContentFillModeUsingDurationFromCurrentEvent:(int)arg1;
- (void)setFullScreenContentFillMode:(int)arg1;
- (int)fullScreenContentFillMode;
- (BOOL)isFullScreen;
- (void)hideRemoteHUD;
- (void)showRemoteHUD;
- (BOOL)isShowingRemoteHUD;
- (void)_setNeedsToUpdateCurrentSize;
- (void)_updateCurrentSizeIfNeeded;
@property(readonly, nonatomic, getter=isHUDVisible) BOOL HUDVisible;
@property(nonatomic) BOOL excludesVideoRegionFromScreenCapture;
- (BOOL)isShowingModalUserInterface;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)playbackStateWasActivelyChanged;
- (void)resetAutovisibilityController;
- (BOOL)autovisibilityController:(id)arg1 shouldAutomaticallyShowDueToKeyDownEvent:(id)arg2 inView:(id)arg3;
- (void)hideForAutovisibilityController:(id)arg1 dueToTimeout:(BOOL)arg2;
- (void)showForAutovisibilityController:(id)arg1;
- (BOOL)prefersBorderedOverlays;
- (void)setPrefersUnobscuredContent:(BOOL)arg1;
- (BOOL)prefersUnobscuredContent;
- (void)controlsViewFrameDidChange:(id)arg1;
- (void)layoutSubviewsOfView:(id)arg1 resizedFromOldSize:(struct CGSize)arg2;
- (unsigned long long)preferredAutoresizeBehaviorFlags;
- (struct CGRect)defaultControlsFrameForBounds:(struct CGRect)arg1;
- (struct CGSize)minimumContentSize;
- (struct CGSize)naturalContentSize;
- (BOOL)prefersConstrainedContentAspectRatio;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
- (void)close;
- (void)resignMainViewControllerForWindowController:(id)arg1;
- (void)becomeMainViewControllerForWindowController:(id)arg1;
- (void)loadView;
- (void)dealloc;

@end

