//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class NSError, NSMutableData, NSString, NSURLConnection;

@interface MGVimeoUnpublishOperation : NSOperation <NSURLConnectionDelegate>
{
    NSError *_error;
    NSString *_authToken;
    NSString *_authTokenSecret;
    NSString *_userID;
    NSString *_videoID;
    NSURLConnection *_deleteConnection;
    NSMutableData *_deleteResponseData;
    BOOL _finished;
    BOOL _executing;
}

@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) NSString *localizedStatusMessage;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)handleDeletionRequestDidFinish;
- (void)cancel;
- (void)start;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (void)dealloc;
- (id)initWithUserID:(id)arg1 videoID:(id)arg2 authorizationToken:(id)arg3 authorizationTokenSecret:(id)arg4;

@end

