//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol MGVisualContentContainer <NSObject>

@optional
- (unsigned long long)preferredAutoresizeBehaviorFlags;
- (BOOL)prefersBorderedOverlays;
- (BOOL)prefersUnobscuredContent;
- (struct CGSize)maximumContentSize;
- (struct CGSize)minimumContentSize;
- (BOOL)prefersUserResizableContent;
- (BOOL)prefersConstrainedContentAspectRatio;
- (struct CGSize)naturalContentSize;
- (struct CGRect)contentFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)contentFrame;
@end

