//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MGJobController.h"

@class MGJob, MGVimeoAccount, NSError, NSString, NSURL;

@interface MGVimeoJobController : MGJobController
{
    MGJob *_activeJob;
    NSURL *_resultURL;
    NSError *_error;
    BOOL _reallyFinished;
    NSString *_name;
    NSString *_videoID;
    MGVimeoAccount *_account;
}

@property(copy) MGVimeoAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) NSString *videoID; // @synthesize videoID=_videoID;
@property(retain, nonatomic) MGJob *activeJob; // @synthesize activeJob=_activeJob;
- (id)description;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)handleUnpublishFailedOnAuthenticationFailure;
- (BOOL)restoreFromDictionaryRepresentation:(id)arg1;
- (id)savedDictionaryRepresentation;
- (BOOL)isFinished;
- (void)unpublish;
- (BOOL)canUnpublish;
- (void)reveal;
- (id)error;
- (id)statusString;
- (id)resultURL;
- (id)icon;
- (id)name;
- (id)identifier;
- (void)dealloc;
- (id)init;
- (id)initActiveJobWithMediaComposition:(id)arg1 name:(id)arg2 publishParameters:(id)arg3 account:(id)arg4;

@end

