//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MGVimeoRestInterface : NSObject
{
}

+ (id)authenticationHeaderParamsWithTokenSecret:(id)arg1;
+ (id)errorResponse:(id)arg1;
+ (id)stringForParameters:(id)arg1 URLEncode:(BOOL)arg2;
+ (id)stringByURLEncodingString:(id)arg1;

@end

