//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "MGYouTubeAccountAuthenticationDelegate.h"
#import "MGYouTubeAuthenticationViewDelegate.h"
#import "NSWindowDelegate.h"

@class MGYouTubeAccount, MGYouTubeAuthenticationViewController, NSView;

@interface MGYouTubeUnpublishWindowController : NSWindowController <NSWindowDelegate, MGYouTubeAccountAuthenticationDelegate, MGYouTubeAuthenticationViewDelegate>
{
    NSView *_currentView;
    MGYouTubeAccount *_youTubeAccount;
    MGYouTubeAuthenticationViewController *_authViewController;
}

@property(retain, nonatomic) MGYouTubeAccount *youTubeAccount; // @synthesize youTubeAccount=_youTubeAccount;
- (void)shouldCloseAuthenticationWindow:(id)arg1;
- (void)accountAuthenticationDidFail:(id)arg1;
- (void)accountAuthenticationDidSucceed:(id)arg1;
- (void)makeCurrentView:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithUserName:(id)arg1;

@end

