//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class NSError, NSMutableData, NSString, NSTimer, NSURL, NSURLConnection, NSURLRequest, NSURLResponse;

@interface MGYouTubePublishStatusOperation : NSOperation <NSURLConnectionDelegate>
{
    unsigned int _didRecieveUploadResponse:1;
    unsigned int _finished:1;
    unsigned int _executing:1;
    NSError *_error;
    NSTimer *_timer;
    NSURL *_statusCheckURL;
    NSURL *_revealURL;
    NSMutableData *_downloadedData;
    NSURLResponse *_response;
    NSURLRequest *_request;
    NSURLConnection *_currentConnection;
    NSString *_authToken;
}

+ (id)publishStatusOperationWithURL:(id)arg1 authorizationToken:(id)arg2;
@property(retain, nonatomic) NSMutableData *downloadedData; // @synthesize downloadedData=_downloadedData;
@property(copy, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(copy, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(copy) NSString *authToken; // @synthesize authToken=_authToken;
@property(copy) NSURL *revealURL; // @synthesize revealURL=_revealURL;
@property(copy) NSURL *statusCheckURL; // @synthesize statusCheckURL=_statusCheckURL;
@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) NSString *localizedStatusMessage;
@property(readonly) float progress;
@property(readonly) NSString *mimeBoundary;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (id)processResponseXML:(id)arg1;
- (void)startStatusCheckOperation:(id)arg1;
- (void)makeRequestedConnection:(id)arg1;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (void)cancel;
- (void)handleUploadDidFinish;
- (void)start;
- (void)dealloc;
- (id)initPublishStatusOperationWithURL:(id)arg1 authorizationToken:(id)arg2;
- (id)init;

@end

