//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDelegate.h"

@class NSError, NSMutableData, NSString, NSURLConnection;

@interface MGYouTubeAccount : NSObject <NSURLConnectionDelegate>
{
    NSString *_authToken;
    NSString *_userName;
    NSString *_password;
    id <MGYouTubeAccountAuthenticationDelegate> _delegate;
    NSURLConnection *_authenticationConnection;
    NSMutableData *_authenticationDownloadedData;
    NSError *_error;
    BOOL _authenticationCancelled;
    BOOL _shouldStorePasswordInKeychain;
}

+ (id)keyPathsForValuesAffectingAuthenticating;
+ (id)storedAccountWithUserName:(id)arg1;
@property(retain, nonatomic) NSURLConnection *authenticationConnection; // @synthesize authenticationConnection=_authenticationConnection;
@property(nonatomic) BOOL shouldStorePasswordInKeychain; // @synthesize shouldStorePasswordInKeychain=_shouldStorePasswordInKeychain;
@property(copy, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) id <MGYouTubeAccountAuthenticationDelegate> delegate; // @synthesize delegate=_delegate;
- (id)description;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)cancelAuthentication;
- (void)authenticate;
@property(readonly, nonatomic, getter=isAuthenticationCancelled) BOOL authenticationCancelled;
@property(readonly, nonatomic, getter=isAuthenticating) BOOL authenticating;
- (void)dealloc;
- (id)init;
- (id)initWithUserName:(id)arg1 password:(id)arg2;

@end

