//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class MGFileInputStream, MGMultipartInputStream, NSData, NSDictionary, NSError, NSMutableData, NSString, NSURL, NSURLConnection, NSURLRequest, NSURLResponse;

@interface MGYouTubePublishOperation : NSOperation <NSURLConnectionDelegate>
{
    NSDictionary *_publishParameters;
    BOOL _didRecieveUploadResponse;
    BOOL _finished;
    BOOL _executing;
    BOOL _shouldKeepRunning;
    float _progress;
    NSError *_error;
    unsigned long long _dataSize;
    NSURL *_statusCheckURL;
    NSURL *_revealURL;
    NSString *_authToken;
    NSMutableData *_downloadedData;
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSURLConnection *_currentConnection;
    MGFileInputStream *_tempFileInputStream;
    MGMultipartInputStream *_mppInputStream;
}

+ (id)youTubeUploadURLForUserID:(id)arg1 clientID:(id)arg2;
+ (id)publishOperationWithParameters:(id)arg1 authorizationToken:(id)arg2;
@property(retain, nonatomic) NSMutableData *downloadedData; // @synthesize downloadedData=_downloadedData;
@property(copy, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(copy, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(copy) NSURL *revealURL; // @synthesize revealURL=_revealURL;
@property(copy) NSURL *statusCheckURL; // @synthesize statusCheckURL=_statusCheckURL;
@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) NSString *localizedStatusMessage;
@property(readonly) float progress;
@property(readonly, nonatomic) NSString *mimeBoundary;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (id)processUploadResponseXML:(id)arg1;
- (void)uploadVideoFile:(id)arg1 withRequest:(id)arg2;
@property(readonly, nonatomic) NSData *settingsMetaData;
- (void)startUploadOperation;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (void)cancel;
- (void)handleUploadDidFinish;
- (void)start;
- (void)dealloc;
- (id)initWithParameters:(id)arg1 authorizationToken:(id)arg2;

@end

