//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@interface NSApplication (MGApplicationScripting)
- (id)screenCompressionPresets;
- (id)movieCompressionPresets;
- (id)audioCompressionPresets;
- (id)videoRecordingDevices;
- (id)audioRecordingDevices;
- (id)handleNewScreenRecording:(id)arg1;
- (id)handleNewAudioRecording:(id)arg1;
- (id)handleNewMovieRecording:(id)arg1;
- (id)handleOpenURLScriptCommand:(id)arg1;
@end

