//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (NSString_MGAdditions)
- (id)replaceWithLocalizedDecimialPtStr;
- (id)dictionaryWithResponseString;
- (id)dictionaryWithResponseStringUsingSeparator:(id)arg1;
- (id)SHA1HMACWithKey:(id)arg1;
- (id)md5HashString;
- (id)stringByRemovingCharactersInSet:(id)arg1;
- (id)stringByURLEscapingCharactersInString:(id)arg1 forEncoding:(unsigned long long)arg2;
- (id)stringByBackslashEscapingCharactersInSet:(id)arg1;
@end

