//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWorkspace.h"

@interface NSWorkspace (NSWorkspace_MGAdditions)
- (long long)compare:(id)arg1 withShortVersionString:(id)arg2;
- (id)shortVersionStringForApplicationWithBundleIdentifier:(id)arg1;
@end

