//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTHUDPopUpButtonCell.h"

@interface QTHUDPopUpButtonCell (MGHUDPopUpButtonCell)
- (void)mg_setMenuItem:(id)arg1;
@end

