//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTMovie.h"

@interface QTMovie (MGAdditions)
+ (id)keyPathsForValuesAffectingCurrentTimeAtEndOfAvailableRanges;
+ (id)keyPathsForValuesAffectingThirtySecondsBeforeCurrentTimeWithinAvailableRanges;
+ (id)keyPathsForValuesAffectingChaptersWithinPlaybackRange;
- (id)rainForestExportData;
- (BOOL)isPhotoSlideshow;
- (BOOL)wasAuthoredBySoftwareWithPrefix:(id)arg1;
- (id)rainforestMediaIndexesForMediaType:(id)arg1;
- (BOOL)isCurrentTimeAtEndOfAvailableRanges;
- (CDStruct_900afa40)timeAtEndOfAvailableRanges;
- (BOOL)isThirtySecondsBeforeCurrentTimeWithinAvailableRanges;
- (CDStruct_900afa40)thirtySecondsBeforeCurrentTime;
- (BOOL)isTimeWithinAvailableRanges:(CDStruct_900afa40)arg1;
- (id)chaptersWithinPlaybackRange;
@end

