//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface QTPerfCollector : NSObject
{
    struct _QTTestInfo *_testInfo;
    BOOL _collecting;
    NSMutableDictionary *_taskTimes;
    NSString *_resultsPath;
}

+ (void)collectSubProcessResourceUsageForPerfCollector:(id)arg1;
+ (void)setCollector:(id)arg1 forTest:(id)arg2;
+ (id)collectorForTest:(id)arg1;
- (void)setDoubleTestValue:(double)arg1 forKey:(id)arg2;
- (void)setLongLongTestValue:(long long)arg1 forKey:(id)arg2;
- (void)setLongTestValue:(long long)arg1 forKey:(id)arg2;
- (void)setTestValue:(id)arg1 forKey:(id)arg2;
- (void)terminateApp;
- (void)writeResults;
- (void)collectMemoryUsageWithLabel:(id)arg1;
- (void)stopMeasurementOfTask:(id)arg1;
- (void)startMeasurementOfTask:(id)arg1 fromEnvVar:(const char *)arg2;
- (void)startMeasurementOfTask:(id)arg1;
- (id)taskTimeForTaskID:(id)arg1;
- (void)stopMeasurementOfMainTask;
- (void)startMeasurementOfMainTaskFromEnvVar:(const char *)arg1;
- (void)startMeasurementOfMainTask;
- (void)cleanup;
- (void)setup;
- (id)resultsPath;
- (void)setResultsPathFromEnvVar:(const char *)arg1;
- (void)setResultsPath:(id)arg1;
- (void)dealloc;
- (id)initTestingEnvVar:(const char *)arg1;
- (id)init;

@end

